// ─── ECON STUDIO · pipeline/exporter.js ──────────────────────────────────────
// Script generation for pipeline export.
//
// Two entry points:
//   generateCleanScript({ language, datasetName, filename, pipeline, allDatasets })
//     → single-dataset script (used by Clean tab export bar)
//
//   generateWorkspaceScript({ language, datasets, globalPipeline })
//     → multi-dataset script with topological DAG ordering (used by full export)
//
// Pure JS, no React imports.

import { toR, toStata, toPython } from "./stepTranslators.js";
import { buildRLoadLine, buildPyLoadLine, buildStataLoadLine } from "../services/export/loadLine.js";
import { emitMode } from "./lineage.js";

// ─── LANGUAGE METADATA ───────────────────────────────────────────────────────

const LANG = {
  r:      { ext: "R",    comment: "#",  blockComment: (s) => `# ${"─".repeat(70)}\n# ${s}\n# ${"─".repeat(70)}` },
  stata:  { ext: "do",  comment: "*",  blockComment: (s) => `* ${"─".repeat(70)}\n* ${s}\n* ${"─".repeat(70)}` },
  python: { ext: "py",  comment: "#",  blockComment: (s) => `# ${"─".repeat(70)}\n# ${s}\n# ${"─".repeat(70)}` },
};

// ─── HEADERS ─────────────────────────────────────────────────────────────────

function rHeader(datasetName) {
  return [
    `# ${"─".repeat(70)}`,
    `# Litux — Replication Script (R)`,
    `# Dataset: ${datasetName}`,
    `# Generated: ${new Date().toISOString().slice(0, 10)}`,
    `# ${"─".repeat(70)}`,
    ``,
    `library(dplyr)`,
    `library(tidyr)`,
    `library(stringr)`,
    `library(lubridate)`,
    `library(readr)`,
    ``,
  ].join("\n");
}

function stataHeader(datasetName) {
  return [
    `* ${"─".repeat(70)}`,
    `* Litux — Replication Script (Stata)`,
    `* Dataset: ${datasetName}`,
    `* Generated: ${new Date().toISOString().slice(0, 10)}`,
    `* ${"─".repeat(70)}`,
    ``,
    `version 17`,
    `set more off`,
    ``,
  ].join("\n");
}

function pythonHeader(datasetName) {
  return [
    `# ${"─".repeat(70)}`,
    `# Litux — Replication Script (Python)`,
    `# Dataset: ${datasetName}`,
    `# Generated: ${new Date().toISOString().slice(0, 10)}`,
    `# ${"─".repeat(70)}`,
    ``,
    `import pandas as pd`,
    `import numpy as np`,
    ``,
  ].join("\n");
}

// ─── SAFE IDENTIFIER HELPERS ──────────────────────────────────────────────────

export function toDfVar(name) {
  // Convert dataset name to a safe R/Python variable name.
  // Strips the file extension first so "data.csv" → df_data, not df_data_csv.
  const base = String(name ?? "dataset").replace(/\.[^.]+$/, "");
  return "df_" + base.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^[0-9]/, "_");
}

function toStataFile(name) {
  return name.replace(/[^a-zA-Z0-9_]/g, "_") + ".dta";
}

// Datasets created in-app (spatial outputs, no-recipe derivatives) have bare
// names like "grid_cells" — normalize to "<name>.csv" so the emitted load line
// references a real exportable file. Placeholders (<path_to_…>) pass through.
function toLoadFile(ds) {
  const f = ds.filename ?? `<path_to_${ds.name.replace(/\s+/g, "_")}.csv>`;
  return f.startsWith("<") || /\.[A-Za-z0-9]+$/.test(f) ? f : `${f}.csv`;
}

// A dataset is "in-app" when something in the workspace REBUILDS it: a G-step
// whose output it is. That is a fact about the graph, not about whether its name
// happens to end in ".csv" — the old filename heuristic (no extension ⇒ spatial
// output) declared "joined_data" regenerated by a Spatial section that did not
// exist, then contradicted itself with a read_csv on the very next line. And a
// bare-named dataset that nothing produces must still be LOADED, or the script
// references an undefined variable.
export function isInAppDataset(ds, globalPipeline = []) {
  return (globalPipeline ?? []).some(g => (g.outputDatasetId ?? null) === ds.id);
}

// ─── CROSS-DATASET EMISSION ───────────────────────────────────────────────────
//
// Three cases, decided by lineage.emitMode (see pipeline/lineage.js):
//   identical / prefix / legacy → the live df variable
//   diverged                    → a private `.name_at_join` rebuilt from the raw
//                                 file with the FROZEN pipeline only
//
// `toStep` and `loadLine` are the per-language translator and load-line builder,
// so one function serves R, Stata and Python. For Stata the operand is a FILE,
// not a variable, because every Stata op is `use`-based.
function emitOperand(frozen, liveDs, lang, allDatasets, toStep, loadLine) {
  const mode = emitMode(frozen, liveDs?.pipeline ?? []);
  const name = frozen?.name ?? liveDs?.name ?? "right";
  if (mode !== "diverged") {
    return lang === "stata"
      ? { expr: toStataFile(name), pre: [], mode }
      : { expr: toDfVar(name), pre: [], mode };
  }

  const safe = String(name).replace(/[^a-zA-Z0-9_]/g, "_");
  const cm   = lang === "stata" ? "*" : "#";
  const file = frozen.filename ?? `${name}.csv`;
  const note = `${cm} NOTE: ${name} changed after this dataset was built — rebuilding its state as of then.`;

  if (lang === "stata") {
    const tmp = `_${safe}_at_join.dta`;
    return {
      expr: tmp,
      pre: [
        note,
        loadLine(file, frozen.loadOpts ?? null),
        ...(frozen.snapshot ?? []).map(s => toStep(s, "df", allDatasets)),
        `save "${tmp}", replace`,
      ],
      mode,
    };
  }

  const tmp = `.${safe}_at_join`;
  return {
    expr: tmp,
    pre: [
      note,
      loadLine(file, frozen.loadOpts ?? null).replace(/^df\b/, tmp),
      ...(frozen.snapshot ?? []).map(s => toStep(s, tmp, allDatasets)),
    ],
    mode,
  };
}

// One cross-dataset G-step, in R. Returns the lines to emit. Used both inline
// (prefix mode, mid-chain) and in the trailing Cross-dataset section.
function emitCrossStepR(g, datasets, allDatasets) {
  const out = [];
  const outId = g.outputDatasetId ?? g.leftDatasetId;
  const outDs = datasets[outId];
  const leftLive  = datasets[g.leftDatasetId];
  const rightLive = datasets[g.rightDatasetId];
  if (!outDs && !leftLive) return out;
  const outDf = toDfVar(outDs?.name ?? leftLive?.name ?? "result");

  const L  = emitOperand(g.left,  leftLive,  "r", allDatasets, toR, buildRLoadLine);
  const R2 = emitOperand(g.right, rightLive, "r", allDatasets, toR, buildRLoadLine);
  out.push(...L.pre, ...R2.pre);

  const lk  = g.params?.leftKey  ? `"${g.params.leftKey}"`  : "<left_key>";
  const rk  = g.params?.rightKey ? `"${g.params.rightKey}"` : "<right_key>";
  const sfx = `suffix = c("", "${g.params?.suffix ?? "_r"}")`;

  if (/_join$/.test(g.opType ?? "")) {
    const fn = `${g.opType.replace(/_join$/, "")}_join`;
    out.push(`${outDf} <- dplyr::${fn}(${L.expr}, ${R2.expr}, by = c(${lk} = ${rk}), ${sfx})`);
  } else if (g.opType === "lookup") {
    out.push(`${outDf} <- dplyr::left_join(${L.expr}, ${R2.expr}, by = c(${lk} = ${rk}), ${sfx}, relationship = "many-to-one")`);
  } else if (g.opType === "append") {
    out.push(`${outDf} <- dplyr::bind_rows(${L.expr}, ${R2.expr})`);
  } else if (g.opType === "derive") {
    // A derive has ONE parent, frozen in `right`. Optional staged joins ran on
    // top of it (Clean's "Save as dataset" after a forma-1 join).
    out.push(`# Derived dataset: ${outDs?.name ?? outId} from ${g.right?.name ?? "parent"}`);
    out.push(`${outDf} <- ${R2.expr}`);
    for (const j of (g.params?.joins ?? [])) {
      const jr = emitOperand(j.right, datasets[j.right?.datasetId], "r", allDatasets, toR, buildRLoadLine);
      out.push(...jr.pre);
      const fn = `${j.how || "left"}_join`;
      out.push(`${outDf} <- dplyr::${fn}(${outDf}, ${jr.expr}, by = c("${j.leftKey}" = "${j.rightKey}"), suffix = c("", "${j.suffix ?? "_r"}"))`);
    }
    if (g.params?.recipe) out.push(toR(g.params.recipe, outDf, allDatasets));
    for (const step of (outDs?.pipeline ?? []).filter(s => !s.gStepId)) {
      out.push(toR(step, outDf, allDatasets));
    }
  } else {
    out.push(`# G-step: ${g.opType} — ${outDs?.name ?? outId}`);
  }
  out.push(``);
  return out;
}

// One cross-dataset G-step, in Python. Same structure as emitCrossStepR.
function emitCrossStepPython(g, datasets, allDatasets) {
  const out = [];
  const outId = g.outputDatasetId ?? g.leftDatasetId;
  const outDs = datasets[outId];
  const leftLive  = datasets[g.leftDatasetId];
  const rightLive = datasets[g.rightDatasetId];
  if (!outDs && !leftLive) return out;
  const outDf = toDfVar(outDs?.name ?? leftLive?.name ?? "result");

  const L  = emitOperand(g.left,  leftLive,  "python", allDatasets, toPython, buildPyLoadLine);
  const R2 = emitOperand(g.right, rightLive, "python", allDatasets, toPython, buildPyLoadLine);
  out.push(...L.pre, ...R2.pre);

  const lk  = g.params?.leftKey  ? `"${g.params.leftKey}"`  : `"<left_key>"`;
  const rk  = g.params?.rightKey ? `"${g.params.rightKey}"` : `"<right_key>"`;
  const sfx = `suffixes=("", "${g.params?.suffix ?? "_r"}")`;

  if (/_join$/.test(g.opType ?? "")) {
    const how = g.opType.replace(/_join$/, "");
    const pyHow = { left: "left", inner: "inner", right: "right", full: "outer" }[how] ?? "left";
    out.push(`${outDf} = pd.merge(${L.expr}, ${R2.expr}, left_on=${lk}, right_on=${rk}, how="${pyHow}", ${sfx})`);
  } else if (g.opType === "lookup") {
    out.push(`${outDf} = pd.merge(${L.expr}, ${R2.expr}, left_on=${lk}, right_on=${rk}, how="left", ${sfx}, validate="m:1")`);
  } else if (g.opType === "append") {
    out.push(`${outDf} = pd.concat([${L.expr}, ${R2.expr}], ignore_index=True)`);
  } else if (g.opType === "derive") {
    out.push(`# Derived dataset: ${outDs?.name ?? outId} from ${g.right?.name ?? "parent"}`);
    out.push(`${outDf} = ${R2.expr}.copy()`);
    for (const j of (g.params?.joins ?? [])) {
      const jr = emitOperand(j.right, datasets[j.right?.datasetId], "python", allDatasets, toPython, buildPyLoadLine);
      out.push(...jr.pre);
      const pyHow = { left: "left", inner: "inner", right: "right", full: "outer" }[j.how] ?? "left";
      out.push(`${outDf} = pd.merge(${outDf}, ${jr.expr}, left_on="${j.leftKey}", right_on="${j.rightKey}", how="${pyHow}", suffixes=("", "${j.suffix ?? "_r"}"))`);
    }
    if (g.params?.recipe) out.push(toPython(g.params.recipe, outDf, allDatasets));
    for (const step of (outDs?.pipeline ?? []).filter(s => !s.gStepId)) {
      out.push(toPython(step, outDf, allDatasets));
    }
  } else {
    out.push(`# G-step: ${g.opType} — ${outDs?.name ?? outId}`);
  }
  out.push(``);
  return out;
}

// One cross-dataset G-step, in Stata. Every op is `use`-based, so the operands
// are FILES and the result is saved back to a .dta rather than held in a variable.
function emitCrossStepStata(g, datasets, allDatasets) {
  const out = [];
  const outId = g.outputDatasetId ?? g.leftDatasetId;
  const outDs = datasets[outId];
  const leftLive  = datasets[g.leftDatasetId];
  const rightLive = datasets[g.rightDatasetId];
  if (!outDs && !leftLive) return out;
  const outFile = toStataFile(outDs?.name ?? leftLive?.name ?? "result");

  const L  = emitOperand(g.left,  leftLive,  "stata", allDatasets, toStata, buildStataLoadLine);
  const R2 = emitOperand(g.right, rightLive, "stata", allDatasets, toStata, buildStataLoadLine);
  out.push(...L.pre, ...R2.pre);

  const lk = g.params?.leftKey ?? "<left_key>";

  if (/_join$/.test(g.opType ?? "")) {
    const inner = g.opType === "inner_join";
    out.push(`use "${L.expr}", clear`);
    // See stepTranslators.js: Stata cannot express a true many-to-many merge.
    // 1:m assumes the key is unique in the master; joinby is the general form
    // but has no suffixes(). UNVERIFIED against a real Stata run.
    out.push(`* 1:m — assumes '${lk}' is unique in the master. If both sides repeat it,`);
    out.push(`* use: joinby ${lk} using "${R2.expr}", unmatched(master)`);
    out.push(`merge 1:m ${lk} using "${R2.expr}"`);
    out.push(inner ? `keep if _merge == 3` : `drop if _merge == 2`);
    out.push(`drop _merge`);
    out.push(`save "${outFile}", replace`);
  } else if (g.opType === "lookup") {
    out.push(`use "${L.expr}", clear`);
    out.push(`* m:1 errors out if the right key is not unique — same contract as Litux`);
    out.push(`merge m:1 ${lk} using "${R2.expr}"`);
    out.push(`drop if _merge == 2`);
    out.push(`drop _merge`);
    out.push(`save "${outFile}", replace`);
  } else if (g.opType === "append") {
    out.push(`use "${L.expr}", clear`);
    out.push(`append using "${R2.expr}"`);
    out.push(`save "${outFile}", replace`);
  } else if (g.opType === "derive") {
    out.push(`* Derived dataset: ${outDs?.name ?? outId} from ${g.right?.name ?? "parent"}`);
    out.push(`use "${R2.expr}", clear`);
    for (const j of (g.params?.joins ?? [])) {
      const jr = emitOperand(j.right, datasets[j.right?.datasetId], "stata", allDatasets, toStata, buildStataLoadLine);
      out.push(...jr.pre);
      out.push(`merge 1:m ${j.leftKey} using "${jr.expr}"`);
      out.push(`drop if _merge == 2`);
      out.push(`drop _merge`);
    }
    if (g.params?.recipe) out.push(toStata(g.params.recipe, "df", allDatasets));
    for (const step of (outDs?.pipeline ?? []).filter(s => !s.gStepId)) {
      out.push(toStata(step, "df", allDatasets));
    }
    out.push(`save "${outFile}", replace`);
  } else {
    out.push(`* G-step: ${g.opType} — ${outDs?.name ?? outId}`);
  }
  out.push(``);
  return out;
}

// A local cross-dataset step is emitted from the global section ONLY if its
// G-step is still there. An ORPHANED gStepId — undo restored the step but not
// the G-step, since undo/redo track `pipeline` and not `globalPipeline` — falls
// back to emitting the step inline. Never nowhere.
function localStepsOf(ds, globalPipeline) {
  const gIds = new Set(globalPipeline.map(g => g.id));
  return (ds.pipeline ?? []).filter(s => !s.gStepId || !gIds.has(s.gStepId));
}

// ─── SINGLE-DATASET SCRIPT ────────────────────────────────────────────────────

/**
 * Generate a script for a single dataset's local pipeline.
 *
 * @param {object} opts
 * @param {"r"|"stata"|"python"} opts.language
 * @param {string} opts.datasetName   - Human-readable name
 * @param {string} opts.filename      - Original filename (csv/xlsx/dta…)
 * @param {object[]} opts.pipeline    - Array of step objects
 * @param {object}  opts.allDatasets  - { id: { name, filename } } — for resolving join/append names
 * @param {boolean} opts.preview      - emit the trailing head()/list preview (default true).
 *                                      Off when this script is a PREAMBLE to more code
 *                                      (e.g. a plot body), where the preview is just noise.
 * @returns {string}
 */
export function generateCleanScript({ language, datasetName, filename, pipeline, allDatasets = {}, loadOpts = null, preview = true }) {
  const lang = LANG[language];
  if (!lang) throw new Error(`Unknown language: ${language}`);

  if (language === "r") {
    const df   = toDfVar(datasetName);
    const lines = [
      rHeader(datasetName),
      `# ── Load dataset ──`,
      buildRLoadLine(filename, loadOpts).replace(/^df/, df),
      ``,
    ];
    if (pipeline.length) {
      lines.push(`# ── Pipeline steps ──`);
      for (const step of pipeline) {
        lines.push(toR(step, df, allDatasets));
      }
      lines.push(``);
    }
    if (preview) {
      lines.push(`# ── Result ──`);
      lines.push(`head(${df})`);
    }
    return lines.join("\n").trimEnd();
  }

  if (language === "stata") {
    const lines = [
      stataHeader(datasetName),
      `* ── Load dataset ──`,
      buildStataLoadLine(filename, loadOpts),
      ``,
    ];
    if (pipeline.length) {
      lines.push(`* ── Pipeline steps ──`);
      for (const step of pipeline) {
        lines.push(toStata(step, "df", allDatasets));
      }
      lines.push(``);
    }
    if (preview) {
      lines.push(`* ── Preview ──`);
      lines.push(`list in 1/5`);
    }
    return lines.join("\n").trimEnd();
  }

  if (language === "python") {
    const df   = toDfVar(datasetName);
    const lines = [
      pythonHeader(datasetName),
      `# ── Load dataset ──`,
      buildPyLoadLine(filename, loadOpts).replace(/^df/, df),
      ``,
    ];
    if (pipeline.length) {
      lines.push(`# ── Pipeline steps ──`);
      for (const step of pipeline) {
        lines.push(toPython(step, df, allDatasets));
      }
      lines.push(``);
    }
    if (preview) {
      lines.push(`# ── Preview ──`);
      lines.push(`print(${df}.head())`);
    }
    return lines.join("\n").trimEnd();
  }

  return "";
}

// ─── TOPOLOGICAL SORT ─────────────────────────────────────────────────────────

/**
 * Return dataset IDs in topological order based on G-step dependencies.
 * A dataset that is used as the "right" operand in a join must be available
 * before the left dataset can be joined.
 *
 * @param {object[]} datasets      - Array of { id, name }
 * @param {object[]} globalPipeline - G-steps with leftDatasetId / rightDatasetId
 * @returns {string[]} ordered dataset IDs
 */
export function topoSort(datasets, globalPipeline) {
  const ids = datasets.map(d => d.id);
  const idSet = new Set(ids);

  // deps[id] = the ids `id` must wait for. The CONSUMER is the G-step's output
  // dataset (which for an in-place join is the left operand).
  const deps = {};
  for (const id of ids) deps[id] = new Set();
  for (const g of globalPipeline) {
    const consumer = g.outputDatasetId ?? g.leftDatasetId;
    if (!deps[consumer]) continue;
    for (const src of [g.leftDatasetId, g.rightDatasetId]) {
      if (src && src !== consumer && idSet.has(src)) deps[consumer].add(src);
    }
  }

  // Kahn: repeatedly take every node whose dependencies are already emitted.
  // The previous version counted DEPENDENTS rather than in-degree, so the queue
  // started with the nodes nobody depends on — i.e. the consumer — and a join's
  // left operand was emitted before the right one it consumes.
  const remaining = new Set(ids);
  const result = [];
  let progress = true;
  while (remaining.size && progress) {
    progress = false;
    for (const id of ids) {
      if (!remaining.has(id)) continue;
      let ready = true;
      for (const d of deps[id]) if (remaining.has(d)) { ready = false; break; }
      if (ready) { result.push(id); remaining.delete(id); progress = true; }
    }
  }
  // Cycles are possible under the in-place model (two datasets joined into each
  // other) — append what is left, in insertion order, rather than dropping it.
  for (const id of ids) if (remaining.has(id)) result.push(id);
  return result;
}

// ─── MULTI-DATASET (WORKSPACE) SCRIPT ────────────────────────────────────────

/**
 * Generate a workspace-level script with all datasets in topological order.
 *
 * @param {object} opts
 * @param {"r"|"stata"|"python"} opts.language
 * @param {object}  opts.datasets        - { id: { id, name, filename, pipeline, loadOpts? } }
 * @param {object[]} opts.globalPipeline - G-steps array
 * @returns {string}
 */
export function generateWorkspaceScript({ language, datasets, globalPipeline = [] }) {
  const dsList = Object.values(datasets);
  if (!dsList.length) return { perDataset: `# No datasets in session`, crossDataset: "" };

  const allDatasets = Object.fromEntries(dsList.map(d => [d.id, { name: d.name, filename: d.filename }]));

  // Datasets that a G-step BUILDS are emitted only in the cross-dataset section.
  const producedIds = new Set(globalPipeline.map(g => g.outputDatasetId).filter(Boolean));

  // Topological order
  const orderedIds = topoSort(dsList, globalPipeline);
  const ordered    = orderedIds.map(id => datasets[id]).filter(Boolean);

  // A G-step whose frozen LEFT snapshot is a prefix of that dataset's current
  // pipeline was taken partway through: emit it inline at that point, before the
  // steps the user added afterwards. Otherwise the child would appear to consume
  // state that did not exist yet. Tracked so the trailing section skips them.
  const emittedInline = new Set();
  const prefixStepsFor = (ds) => globalPipeline
    .filter(g => g.left?.datasetId === ds.id && emitMode(g.left, ds.pipeline ?? []) === "prefix")
    .map(g => ({ at: g.left.snapshot.length, g }));

  // ── R ──
  if (language === "r") {
    const lines = [rHeader("Workspace — All Datasets")];
    for (const ds of ordered) {
      if (producedIds.has(ds.id)) continue;
      const df   = toDfVar(ds.name);
      const file = toLoadFile(ds);
      lines.push(`# ${"─".repeat(60)}`);
      lines.push(`# Dataset: ${ds.name}`);
      lines.push(`# ${"─".repeat(60)}`);
      lines.push(buildRLoadLine(file, ds.loadOpts ?? null).replace(/^df\b/, df));
      const local = localStepsOf(ds, globalPipeline);
      const inline = prefixStepsFor(ds);
      for (let i = 0; i <= local.length; i++) {
        for (const { at, g } of inline) {
          if (at !== i || emittedInline.has(g.id)) continue;
          emittedInline.add(g.id);
          lines.push(...emitCrossStepR(g, datasets, allDatasets));
        }
        if (i < local.length) lines.push(toR(local[i], df, allDatasets));
      }
      lines.push(``);
    }
    const crossLines = [];
    const trailing = globalPipeline.filter(g => !emittedInline.has(g.id));
    if (trailing.length) {
      crossLines.push(`# ${"─".repeat(60)}`);
      crossLines.push(`# Cross-dataset interactions`);
      crossLines.push(`# ${"─".repeat(60)}`);
      for (const g of trailing) crossLines.push(...emitCrossStepR(g, datasets, allDatasets));
    }
    return { perDataset: lines.join("\n"), crossDataset: crossLines.join("\n") };
  }

  // ── Stata ──
  if (language === "stata") {
    const lines = [stataHeader("Workspace — All Datasets")];
    // Stata needs to pre-save all datasets, then use them in order
    lines.push(`* Pre-materialization pass — save all cleaned datasets to .dta`);
    lines.push(``);

    for (const ds of ordered) {
      if (producedIds.has(ds.id)) continue;
      const file    = toLoadFile(ds);
      const dtaFile = toStataFile(ds.name);
      lines.push(`* ${"─".repeat(60)}`);
      lines.push(`* Dataset: ${ds.name}`);
      lines.push(`* ${"─".repeat(60)}`);
      lines.push(buildStataLoadLine(file, ds.loadOpts ?? null));
      const local = localStepsOf(ds, globalPipeline);
      const inline = prefixStepsFor(ds);
      for (let i = 0; i <= local.length; i++) {
        for (const { at, g } of inline) {
          if (at !== i || emittedInline.has(g.id)) continue;
          emittedInline.add(g.id);
          // Stata operands are files: save what we have so far, emit the
          // interaction, then reload to keep applying the remaining steps.
          lines.push(`save "${dtaFile}", replace`);
          lines.push(...emitCrossStepStata(g, datasets, allDatasets));
          lines.push(`use "${dtaFile}", clear`);
        }
        if (i < local.length) lines.push(toStata(local[i], "df", allDatasets));
      }
      lines.push(`save "${dtaFile}", replace`);
      lines.push(``);
    }

    const crossLines = [];
    const trailing = globalPipeline.filter(g => !emittedInline.has(g.id));
    if (trailing.length) {
      crossLines.push(`* ${"─".repeat(60)}`);
      crossLines.push(`* Cross-dataset interactions`);
      crossLines.push(`* ${"─".repeat(60)}`);
      for (const g of trailing) crossLines.push(...emitCrossStepStata(g, datasets, allDatasets));
    }
    return { perDataset: lines.join("\n"), crossDataset: crossLines.join("\n") };
  }

  // ── Python ──
  if (language === "python") {
    const lines = [pythonHeader("Workspace — All Datasets")];
    for (const ds of ordered) {
      if (producedIds.has(ds.id)) continue;
      const df   = toDfVar(ds.name);
      const file = toLoadFile(ds);
      lines.push(`# ${"─".repeat(60)}`);
      lines.push(`# Dataset: ${ds.name}`);
      lines.push(`# ${"─".repeat(60)}`);
      lines.push(buildPyLoadLine(file, ds.loadOpts ?? null).replace(/^df\b/, df));
      const local = localStepsOf(ds, globalPipeline);
      const inline = prefixStepsFor(ds);
      for (let i = 0; i <= local.length; i++) {
        for (const { at, g } of inline) {
          if (at !== i || emittedInline.has(g.id)) continue;
          emittedInline.add(g.id);
          lines.push(...emitCrossStepPython(g, datasets, allDatasets));
        }
        if (i < local.length) lines.push(toPython(local[i], df, allDatasets));
      }
      lines.push(``);
    }

    const crossLines = [];
    const trailing = globalPipeline.filter(g => !emittedInline.has(g.id));
    if (trailing.length) {
      crossLines.push(`# ${"─".repeat(60)}`);
      crossLines.push(`# Cross-dataset interactions`);
      crossLines.push(`# ${"─".repeat(60)}`);
      for (const g of trailing) crossLines.push(...emitCrossStepPython(g, datasets, allDatasets));
    }
    return { perDataset: lines.join("\n"), crossDataset: crossLines.join("\n") };
  }

  return { perDataset: "", crossDataset: "" };
}
