// ─── ECON STUDIO · services/export/latexTable.js ─────────────────────────────
// Stargazer-style LaTeX table generator.
// Pure JS, no React, no side effects.
//
// buildStargazer(models) → string
//   models: [{ label: string, result: EstimationResult, yVar: string }]
//
// Produces a \begin{table} ... \end{table} block ready to paste into LaTeX.
// Requires \usepackage{booktabs} if \toprule is desired; uses \hline by default.

import { stars } from "../../math/index.js";

/**
 * Generate a Stargazer-style LaTeX table for one or more models.
 *
 * @param {Array<{label: string, result: object, yVar: string}>} models
 * @returns {string} LaTeX table source
 */
export function buildStargazer(models) {
  // Collect union of varNames across all models (minus Intercept, added at bottom)
  const allVars = [];
  models.forEach(({ result: r }) => {
    (r.varNames ?? []).forEach(v => {
      if (v !== "(Intercept)" && !allVars.includes(v)) allVars.push(v);
    });
  });

  const fmtB = (b, p) => {
    if (b == null || !isFinite(b)) return "        N/A";
    return `${b >= 0 ? " " : ""}${b.toFixed(4)}${stars(p ?? 1)}`.padStart(12);
  };
  const fmtSE = se => {
    if (se == null || !isFinite(se)) return "      (N/A)";
    return `(${se.toFixed(4)})`.padStart(12);
  };
  const dash = "            ";

  const colsN  = models.length;
  const colFmt = "l" + " r".repeat(colsN);
  const header = ["Variable", ...models.map((m, i) => `(${i + 1}) ${m.label}`)];
  const sep    = " & ";

  function modelVal(m, varName, key) {
    const idx = m.result.varNames?.indexOf(varName) ?? -1;
    if (idx < 0) return dash;
    const r = m.result;
    const b = r.beta?.[idx], p = r.pVals?.[idx], se = r.se?.[idx];
    if (key === "b")  return fmtB(b, p);
    if (key === "se") return fmtSE(se);
    return dash;
  }

  const rows = [];

  // Regressors (no intercept yet)
  allVars.forEach(v => {
    const label = v.replace(/_/g, "\\_");
    rows.push(`  ${label}${sep}${models.map(m => modelVal(m, v, "b")).join(sep)} \\\\`);
    rows.push(`  ${" ".repeat(label.length)}${sep}${models.map(m => modelVal(m, v, "se")).join(sep)} \\\\`);
  });

  // Intercept always last
  const intV = "(Intercept)";
  rows.push(`  \\hline`);
  rows.push(`  Intercept${sep}${models.map(m => modelVal(m, intV, "b")).join(sep)} \\\\`);
  rows.push(`  ${" ".repeat(9)}${sep}${models.map(m => modelVal(m, intV, "se")).join(sep)} \\\\`);

  // Fit stats
  rows.push(`  \\hline`);
  rows.push(`  $R^2$${sep}${models.map(m =>
    (m.result.R2 != null && isFinite(m.result.R2)) ? m.result.R2.toFixed(4).padStart(12) : dash).join(sep)} \\\\`);
  rows.push(`  Adj. $R^2$${sep}${models.map(m =>
    (m.result.adjR2 != null && isFinite(m.result.adjR2)) ? m.result.adjR2.toFixed(4).padStart(12) : dash).join(sep)} \\\\`);
  rows.push(`  $n$${sep}${models.map(m =>
    m.result.n != null ? String(m.result.n).padStart(12) : dash).join(sep)} \\\\`);

  const yVarDisplay = models.map(m => `\\texttt{${(m.yVar ?? "y").replace(/_/g, "\\_")}}`);
  const caption = colsN === 1
    ? `Regression Results: ${yVarDisplay[0]}`
    : `Regression Results`;

  return [
    `% Generated by Econ Studio · LMU Munich`,
    `\\begin{table}[htbp]`,
    `\\centering`,
    `\\caption{${caption}}`,
    `\\label{tab:results}`,
    `\\begin{tabular}{${colFmt}}`,
    `\\hline\\hline`,
    header.map(h => h.replace(/_/g, "\\_")).join(sep) + " \\\\",
    `\\hline`,
    ...rows,
    `\\hline`,
    `\\multicolumn{${colsN + 1}}{l}{\\textit{Note: }Standard errors in parentheses.} \\\\`,
    `\\multicolumn{${colsN + 1}}{l}{Significance codes: *$p<0.1$, **$p<0.05$, ***$p<0.01$} \\\\`,
    `\\hline`,
    `\\end{tabular}`,
    `\\end{table}`,
  ].join("\n");
}
