// ─── LITUX · services/export/pythonScript.js ───────────────────────────
// Generates a self-contained Python replication script using pandas,
// statsmodels, and linearmodels.
//
// Config shape (same as rScript.js):
//   { filename, pipeline, model, auditTrail, dataDictionary }
//
// model shape:
//   { type, yVar, xVars, wVars, zVars, entityCol, timeCol,
//     postVar, treatVar, runningVar, cutoff, bandwidth, kernel }

import { toPython, jsExprToPython, pyRightLoad } from "../../pipeline/stepTranslators.js";
import { buildPyLoadLine } from "./loadLine.js";

export function generatePythonScript(config = {}) {
  const {
    filename       = "dataset.csv",
    pipeline       = [],
    model          = {},
    dataDictionary = null,
    dataLoadOpts   = null,
    allDatasets    = {},
  } = config;

  const {
    type        = "OLS",
    yVar        = "y",
    xVars       = [],
    wVars       = [],
    zVars       = [],
    entityCol   = null,
    timeCol     = null,
    postVar     = null,
    treatVar    = null,
    runningVar    = null,
    cutoff        = null,
    bandwidth     = null,
    kernel        = "triangular",
    distCol       = null,
    treatmentCol  = null,
    offsetCol     = null,
    seType        = "classical",
    clusterVar    = null,
    clusterVar2   = null,
  } = model;

  const stem    = filename.replace(/\.[^.]+$/, "");
  const pyFile  = filename.replace(/\\/g, "/");   // forward slashes — safe in Python strings
  const allX = [...(xVars ?? []), ...(wVars ?? [])];
  const pkgs = buildPackageList(type, pipeline);

  const lines = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`# ${"─".repeat(72)}`);
  lines.push(`# Replication script — ${stem}`);
  lines.push(`# Generated by Litux · ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`# Estimator: ${type}`);
  lines.push(`# ${"─".repeat(72)}`);
  lines.push("");

  // ── Install hint ─────────────────────────────────────────────────────────────
  const installPkgs = [];
  if (pkgs.has("statsmodels"))  installPkgs.push("statsmodels");
  if (pkgs.has("linearmodels")) installPkgs.push("linearmodels");
  if (pkgs.has("scipy"))        installPkgs.push("scipy");
  if (installPkgs.length) {
    lines.push(`# Install required packages if needed:`);
    lines.push(`#   pip install ${installPkgs.join(" ")}`);
    lines.push("");
  }

  // ── Imports ─────────────────────────────────────────────────────────────────
  lines.push("import pandas as pd");
  lines.push("import numpy as np");
  if (pkgs.has("statsmodels")) {
    lines.push("import statsmodels.formula.api as smf");
    lines.push("import statsmodels.api as sm");
  }
  if (pkgs.has("linearmodels")) {
    lines.push("from linearmodels.panel import PanelOLS, FirstDifferenceOLS, BetweenOLS");
    lines.push("from linearmodels.iv import IV2SLS");
  }
  if (pkgs.has("scipy")) {
    lines.push("from scipy import stats");
  }
  lines.push("");

  // ── Load data ───────────────────────────────────────────────────────────────
  lines.push("# ── Load data ─────────────────────────────────────────────────────────────");
  lines.push(buildPyLoadLine(pyFile, dataLoadOpts));
  lines.push("");

  // ── Data dictionary ─────────────────────────────────────────────────────────
  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push("# ── Variable definitions ──────────────────────────────────────────────────");
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => {
      lines.push(`# ${k}: ${String(v).replace(/\n/g, " ")}`);
    });
    lines.push("");
  }

  // ── Pipeline steps ──────────────────────────────────────────────────────────
  if (pipeline.length) {
    lines.push("# ── Data pipeline ─────────────────────────────────────────────────────────");
    pipeline.forEach(step => {
      const code = transpileStep(step, allDatasets);
      if (code) lines.push(code);
    });
    lines.push("");
  }

  // ── Model ───────────────────────────────────────────────────────────────────
  lines.push("# ── Estimation ─────────────────────────────────────────────────────────────");
  lines.push(...transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, distCol, treatmentCol, factorVars: model.factorVars ?? [], feCols: model.feCols ?? null, offsetCol, cohortCol: model.cohortCol ?? null, periodCol: model.periodCol ?? null, controlMode: model.controlMode ?? null, refPeriod: model.refPeriod ?? null, interactionTerms: model.interactionTerms ?? [], xVarsRaw: model.xVarsRaw ?? null, wVarsRaw: model.wVarsRaw ?? null, seType, clusterVar, clusterVar2, noIntercept: model.noIntercept ?? false }));
  lines.push("");

  return lines.join("\n");
}

// ─── PACKAGE LIST ─────────────────────────────────────────────────────────────
function buildPackageList(modelType, pipeline = []) {
  const pkgs = new Set(["statsmodels"]);
  if (["FE","FD","2SLS","TWFE","GMM","LIML"].includes(modelType)) pkgs.add("linearmodels");
  if (modelType === "RDD" || modelType === "SpatialRDD") pkgs.add("scipy");
  return pkgs;
}

function pyStr(s) {
  return JSON.stringify(String(s ?? ""));
}

function pyList(arr) {
  return `[${(arr ?? []).map(pyStr).join(", ")}]`;
}

function pyValue(v, dtype = null) {
  if (v === null || v === undefined) return "None";
  if (dtype === "number" || typeof v === "number") {
    const n = Number(v);
    return isFinite(n) ? String(n) : "None";
  }
  return pyStr(v);
}

function pyWhere(where) {
  if (!where?.col || !where?.op) return "pd.Series(True, index=df.index)";
  const c = pyStr(where.col);
  const v = where.value;
  switch (where.op) {
    case "equals": return `(df[${c}].astype("string") == ${pyStr(v ?? "")})`;
    case "not_equals": return `(df[${c}].astype("string") != ${pyStr(v ?? "")})`;
    case "contains": return `df[${c}].astype("string").str.contains(${pyStr(v ?? "")}, regex=False, na=False)`;
    case "starts": return `df[${c}].astype("string").str.startswith(${pyStr(v ?? "")}, na=False)`;
    case "ends": return `df[${c}].astype("string").str.endswith(${pyStr(v ?? "")}, na=False)`;
    case "gt": return `(pd.to_numeric(df[${c}], errors="coerce") > ${Number(v)})`;
    case "lt": return `(pd.to_numeric(df[${c}], errors="coerce") < ${Number(v)})`;
    case "between": {
      const lo = Number(Array.isArray(v) ? v[0] : v);
      const hi = Number(Array.isArray(v) ? v[1] : v);
      return `pd.to_numeric(df[${c}], errors="coerce").between(${lo}, ${hi})`;
    }
    case "empty": return `(df[${c}].isna() | (df[${c}].astype("string") == ""))`;
    case "notempty": return `(df[${c}].notna() & (df[${c}].astype("string") != ""))`;
    default: return "pd.Series(True, index=df.index)";
  }
}

function isGridEditStep(step) {
  return ["add_column", "add_row", "set_where", "replace", "str_splice"].includes(step.type);
}

// ─── STEP TRANSPILER ─────────────────────────────────────────────────────────
function transpileStep(step, allDatasets = {}) {
  const { type, params = {} } = step;
  if (typeof type === "string" && type.startsWith("sp_")) return toPython(step, "df", allDatasets);
  switch (type) {
    case "add_column":
      return `df[${pyStr(step.nn)}] = ${pyValue(step.fill, step.dtype)}`;
    case "add_row": {
      const count = Math.max(1, Number(step.count) || 1);
      const values = JSON.stringify(step.values || {});
      return [
        `# add_row: append ${count} synthetic row(s); unspecified columns become NaN`,
        `_new_rows = pd.DataFrame([${values}] * ${count})`,
        `df = pd.concat([df, _new_rows], ignore_index=True)`,
      ].join("\n");
    }
    case "set_where":
      return `df.loc[${pyWhere(step.where)}, ${pyStr(step.col)}] = ${step.action === "clear" ? "None" : pyValue(step.value, step.dtype)}`;
    case "replace": {
      const col = pyStr(step.col);
      const out = pyStr(step.nn || step.col);
      const mode = step.match?.mode || "exact";
      const find = step.match?.find ?? "";
      const repl = step.replaceWith ?? "";
      if (mode === "exact") {
        return [
          ...(step.nn ? [`df[${out}] = df[${col}]`] : []),
          `df[${out}] = df[${out}].replace(${pyStr(find)}, ${pyStr(repl)})`,
        ].join("\n");
      }
      return [
        ...(step.nn ? [`df[${out}] = df[${col}]`] : []),
        `df[${out}] = df[${out}].astype("string").str.replace(${pyStr(find)}, ${pyStr(repl)}, regex=${mode === "regex" ? "True" : "False"})`,
      ].join("\n");
    }
    case "str_splice": {
      const col = pyStr(step.col);
      const out = pyStr(step.nn || step.col);
      return [
        `def _litux_splice(v, position, mode, text="", count=0):`,
        `    if pd.isna(v):`,
        `        return v`,
        `    s = str(v)`,
        `    pos = len(s) if position is None else int(position)`,
        `    pos = max(0, min((len(s) + pos + 1) - 1 if pos < 0 else pos - 1, len(s)))`,
        `    n = max(0, int(count or 0))`,
        `    if mode == "insert": return s[:pos] + text + s[pos:]`,
        `    if mode == "delete": return s[:pos] + s[pos+n:]`,
        `    if mode == "overwrite": return s[:pos] + text + s[pos+n:]`,
        `    return s`,
        `df[${out}] = df[${col}].apply(lambda v: _litux_splice(v, ${Number(step.position) || 1}, ${pyStr(step.mode || "insert")}, ${pyStr(step.text ?? "")}, ${Number(step.count) || 0}))`,
        `df[${out}] = pd.to_numeric(df[${out}], errors="ignore")`,
      ].join("\n");
    }
    case "rename":
      return `df = df.rename(columns={${pyStr(step.col)}: ${pyStr(step.newName)}})`;
    case "drop":
      return `df = df.drop(columns=[${pyStr(step.col)}], errors="ignore")`;
    case "filter": {
      const col = pyStr(step.col);
      const v = step.value;
      switch (step.op) {
        case "notna": return `df = df[df[${col}].notna()]`;
        case "eq":    return `df = df[df[${col}] == ${pyStr(v)}]`;
        case "neq":   return `df = df[df[${col}] != ${pyStr(v)}]`;
        case "gt":    return `df = df[df[${col}] > ${Number(v)}]`;
        case "lt":    return `df = df[df[${col}] < ${Number(v)}]`;
        case "gte":   return `df = df[df[${col}] >= ${Number(v)}]`;
        case "lte":   return `df = df[df[${col}] <= ${Number(v)}]`;
        default:      return `# filter: unsupported op "${step.op}"`;
      }
    }
    case "drop_na":
      if (step.cols?.length) {
        return step.how === "all"
          ? `df = df.dropna(subset=${pyList(step.cols)}, how="all")`
          : `df = df.dropna(subset=${pyList(step.cols)})`;
      }
      return step.how === "all" ? `df = df.dropna(how="all")` : `df = df.dropna()`;
    case "fill_na": {
      const col = pyStr(step.col), c = `df[${col}]`;
      if (step.strategy === "mean")          return `${c} = ${c}.fillna(${c}.mean())`;
      if (step.strategy === "median")        return `${c} = ${c}.fillna(${c}.median())`;
      if (step.strategy === "mode")          return `${c} = ${c}.fillna(${c}.mode()[0])`;
      if (step.strategy === "forward_fill")  return `${c} = ${c}.ffill()`;
      if (step.strategy === "backward_fill") return `${c} = ${c}.bfill()`;
      return `${c} = ${c}.fillna(${pyValue(step.value, "string")})`;
    }
    case "fill_na_grouped": {
      const col = pyStr(step.col), g = pyStr(step.groupCol);
      const stat = step.strategy === "median" ? "median" : "mean";
      return `df[${col}] = df.groupby(${g})[${col}].transform(lambda x: x.fillna(x.${stat}()))`;
    }
    case "type_cast": {
      const col = pyStr(step.col), c = `df[${col}]`;
      if (step.to === "number" || step.to === "number_smart") return `${c} = pd.to_numeric(${c}, errors="coerce")`;
      if (step.to === "string")  return `${c} = ${c}.astype(str)`;
      if (step.to === "boolean") return `${c} = ${c}.astype(bool)`;
      return `${c} = pd.to_numeric(${c}, errors="coerce")`;
    }
    case "log": {
      const col = pyStr(step.col), out = pyStr(step.nn || `log_${step.col}`);
      return `df[${out}] = np.where(df[${col}] > 0, np.log(df[${col}]), np.nan)`;
    }
    case "sq": {
      const col = pyStr(step.col), out = pyStr(step.nn || `${step.col}_sq`);
      return `df[${out}] = df[${col}] ** 2`;
    }
    case "std": {
      const col = pyStr(step.col), out = pyStr(step.nn || `${step.col}_z`);
      // Fixed mu/sd captured at step-creation time (matches the app + R script).
      return `df[${out}] = (df[${col}] - ${Number(step.mu)}) / ${Number(step.sd)}`;
    }
    case "winz": {
      const col = pyStr(step.col), out = pyStr(step.nn && step.nn !== step.col ? step.nn : step.col);
      return `df[${out}] = df[${col}].clip(lower=${Number(step.lo)}, upper=${Number(step.hi)})`;
    }
    case "dummy":
      return `df = pd.get_dummies(df, columns=[${pyStr(step.col)}], prefix=${pyStr(step.pfx || step.col)}, drop_first=False, dtype=int)`;
    case "lag": {
      const col = pyStr(step.col), out = pyStr(step.nn || `${step.col}_lag${step.n ?? 1}`), n = step.n ?? 1;
      if (step.ec && step.tc) {
        return [
          `df = df.sort_values([${pyStr(step.ec)}, ${pyStr(step.tc)}])`,
          `df[${out}] = df.groupby(${pyStr(step.ec)})[${col}].shift(${n})`,
        ].join("\n");
      }
      return `df[${out}] = df[${col}].shift(${n})`;
    }
    case "lead": {
      const col = pyStr(step.col), out = pyStr(step.nn || `${step.col}_lead${step.n ?? 1}`), n = step.n ?? 1;
      if (step.ec && step.tc) {
        return [
          `df = df.sort_values([${pyStr(step.ec)}, ${pyStr(step.tc)}])`,
          `df[${out}] = df.groupby(${pyStr(step.ec)})[${col}].shift(-${n})`,
        ].join("\n");
      }
      return `df[${out}] = df[${col}].shift(-${n})`;
    }
    case "diff": {
      const col = pyStr(step.col), out = pyStr(step.nn || `${step.col}_d`);
      if (step.ec && step.tc) {
        return [
          `df = df.sort_values([${pyStr(step.ec)}, ${pyStr(step.tc)}])`,
          `df[${out}] = df.groupby(${pyStr(step.ec)})[${col}].diff()`,
        ].join("\n");
      }
      return `df[${out}] = df[${col}].diff()`;
    }
    case "ix": {
      const out = pyStr(step.nn || `${step.c1}_x_${step.c2}`);
      return `df[${out}] = df[${pyStr(step.c1)}] * df[${pyStr(step.c2)}]`;
    }
    case "did": {
      const out = pyStr(step.nn || "did");
      return `df[${out}] = df[${pyStr(step.tc)}] * df[${pyStr(step.pc)}]`;
    }
    case "mutate": {
      const nn     = step.nn ?? "newcol";
      const pyExpr = jsExprToPython(step.expr, "df");
      if (pyExpr) return `df[${pyStr(nn)}] = ${pyExpr}`;
      return [
        `# mutate: ${nn} = ${step.expr}`,
        `# NOTE: expression uses JS syntax — translate to Python manually`,
        `# df[${pyStr(nn)}] = <pandas expression>`,
      ].join("\n");
    }
    case "arrange":
      return `df = df.sort_values(${pyStr(step.col)}, ascending=${step.dir === "desc" ? "False" : "True"}).reset_index(drop=True)`;
    case "group_summarize": {
      const aggDict = (step.aggs ?? []).map(a => {
        const fn = a.fn === "sd" ? "std" : a.fn === "count" ? "size" : a.fn;
        return `${pyStr(a.nn)}: (${pyStr(a.col)}, "${fn}")`;
      }).join(", ");
      return `df = df.groupby(${pyList(step.by ?? [])}, as_index=False).agg(**{${aggDict}})`;
    }
    case "group_transform": {
      const by = step.by ?? [];
      const col = step.col ?? by[0] ?? "";
      const out = pyStr(step.nn ?? `${step.fn ?? "mean"}_${col}`);
      const fn = step.fn ?? "mean";
      const group = `df.groupby(${pyList(by)})[${pyStr(col)}]`;
      if (fn === "count") return `df[${out}] = ${group}.transform("size")`;
      if (fn === "sd")    return `df[${out}] = ${group}.transform("std")`;
      if (fn === "rank")  return `df[${out}] = ${group}.transform(lambda s: s.rank(method="min"))`;
      return `df[${out}] = ${group}.transform("${fn}")`;
    }
    case "pivot_longer": {
      const idArg = (step.idCols?.length) ? `id_vars=${pyList(step.idCols)}, ` : "";
      return `df = df.melt(${idArg}value_vars=${pyList(step.cols ?? [])}, var_name=${pyStr(step.namesTo ?? "name")}, value_name=${pyStr(step.valuesTo ?? "value")})`;
    }
    case "pivot_wider": {
      const idCols = pyList(step.idCols ?? []);
      const valsFrom = Array.isArray(step.valuesFrom) ? step.valuesFrom : [step.valuesFrom].filter(Boolean);
      const valArg = valsFrom.length === 1 ? pyStr(valsFrom[0]) : pyList(valsFrom);
      const fill = (step.valuesFill !== undefined && step.valuesFill !== null && step.valuesFill !== "")
        ? `, fill_value=${Number(step.valuesFill)}` : "";
      return `df = df.pivot_table(index=${idCols}, columns=${pyStr(step.namesFrom)}, values=${valArg}${fill}, aggfunc="first").reset_index()`;
    }
    case "date_parse": {
      const col = pyStr(step.col);
      const out = (step.nn && step.nn !== step.col) ? pyStr(step.nn) : col;
      return `df[${out}] = pd.to_datetime(df[${col}], errors="coerce")`;
    }
    case "date_extract": {
      const col = pyStr(step.col);
      const acc = { year: "year", month: "month", dow: "dayofweek", isweekend: "dayofweek" };
      const lines = (step.parts ?? []).map(p => {
        const out = pyStr(step.names?.[p] ?? `${step.col}_${p}`);
        if (p === "isweekend") return `df[${out}] = (pd.to_datetime(df[${col}]).dt.dayofweek >= 5).astype(int)`;
        return `df[${out}] = pd.to_datetime(df[${col}]).dt.${acc[p] ?? "year"}`;
      });
      return lines.length ? lines.join("\n") : `# date_extract: no parts specified`;
    }
    case "recode": {
      const mapStr = JSON.stringify(step.map ?? {});
      return `df[${pyStr(step.col)}] = df[${pyStr(step.col)}].replace(${mapStr})`;
    }
    case "normalize_cats": {
      if (!step.map || !Object.keys(step.map).length) return `# normalize_cats: no mapping specified`;
      return `df[${pyStr(step.col)}] = df[${pyStr(step.col)}].replace(${JSON.stringify(step.map)})`;
    }
    case "trim_outliers":
      // Fixed bounds captured at step-creation time (matches the app + R script).
      return `df = df[(df[${pyStr(step.col)}] >= ${Number(step.lo)}) & (df[${pyStr(step.col)}] <= ${Number(step.hi)})].reset_index(drop=True)`;
    case "flag_outliers": {
      const col = pyStr(step.col), out = pyStr(step.nn || `${step.col}_outlier`);
      if (step.method === "zscore") {
        const thr = Number(step.threshold) || 3;
        return `df[${out}] = (((df[${col}] - df[${col}].mean()) / df[${col}].std()).abs() > ${thr}).astype(int)`;
      }
      return [
        `_q1, _q3 = df[${col}].quantile([0.25, 0.75])`,
        `_iqr = _q3 - _q1`,
        `df[${out}] = ((df[${col}] < _q1 - 1.5 * _iqr) | (df[${col}] > _q3 + 1.5 * _iqr)).astype(int)`,
      ].join("\n");
    }
    case "quickclean": {
      const col = pyStr(step.col), c = `df[${col}].astype("string").str`;
      if (step.mode === "upper") return `df[${col}] = ${c}.upper()`;
      if (step.mode === "title") return `df[${col}] = ${c}.title()`;
      return `df[${col}] = ${c}.lower()`;
    }
    case "clean_strings": {
      const col = pyStr(step.col);
      let expr = `df[${col}].astype("string").str.strip().str.replace(r"\\s+", " ", regex=True)`;
      if (step.case === "lower") expr += ".str.lower()";
      else if (step.case === "upper") expr += ".str.upper()";
      else if (step.case === "title") expr += ".str.title()";
      return `df[${col}] = ${expr}`;
    }
    case "extract_regex": {
      const col = pyStr(step.col), out = pyStr(step.nn || `${step.col}_num`);
      if (step.regex) return `df[${out}] = pd.to_numeric(df[${col}].astype("string").str.extract(r"${step.regex}")[0], errors="coerce")`;
      // locale-aware numeric parse: strip thousands sep, normalize decimal mark.
      if (step.locale === "comma") {
        return `df[${out}] = pd.to_numeric(df[${col}].astype("string").str.replace(r"[^0-9,.-]", "", regex=True).str.replace(".", "", regex=False).str.replace(",", ".", regex=False), errors="coerce")`;
      }
      return `df[${out}] = pd.to_numeric(df[${col}].astype("string").str.replace(r"[^0-9.-]", "", regex=True), errors="coerce")`;
    }
    case "factor_interactions": {
      const cont = pyStr(step.contCol);
      const pfx = step.prefix || `${step.contCol}_x_`;
      const lines = (step.dummyCols ?? []).map(d =>
        `df[${pyStr(pfx + d)}] = df[${cont}] * df[${pyStr(d)}]`);
      return lines.length ? lines.join("\n") : `# factor_interactions: no dummy columns specified`;
    }
    case "if_else": {
      const out = pyStr(step.nn);
      const cond = jsExprToPython(step.cond, "df");
      if (!cond) return `# if_else: ${step.nn} = where(${step.cond}) — translate condition to Python manually`;
      return `df[${out}] = np.where(${cond}, ${pyValue(step.trueVal, "string")}, ${pyValue(step.falseVal, "string")})`;
    }
    case "case_when": {
      const out = pyStr(step.nn);
      const conds = [], choices = [];
      for (const c of (step.cases ?? [])) {
        const cc = jsExprToPython(c.cond, "df");
        if (!cc) continue;
        conds.push(cc); choices.push(pyValue(c.val, "string"));
      }
      if (!conds.length) return `# case_when: no valid conditions — translate manually`;
      return `df[${out}] = np.select([${conds.join(", ")}], [${choices.join(", ")}], default=${pyValue(step.defaultVal, "string")})`;
    }
    case "grouped_mutate": {
      const by = step.by ?? [];
      const out = pyStr(step.newCol || "grouped");
      const fn = step.fn ?? "mean";
      if (!by.length || !step.newCol) return `# grouped_mutate: incomplete config`;
      if (fn === "expr" && step.expr) {
        const pyExpr = jsExprToPython(step.expr, "df");
        return pyExpr
          ? `df[${out}] = df.groupby(${pyList(by)}).apply(lambda g: ${pyExpr}).reset_index(level=${pyList(by)}, drop=True)`
          : `# grouped_mutate (expr): translate "${step.expr}" to Python manually`;
      }
      const aggFn = fn === "sd" ? "std" : fn === "count" ? "size" : fn;
      const group = step.col ? `df.groupby(${pyList(by)})[${pyStr(step.col)}]` : `df.groupby(${pyList(by)})[${pyStr(by[0])}]`;
      return [
        `# grouped_mutate: ${fn} over groups${step.condition?.length ? " (row conditions applied in-app — review)" : ""}`,
        `df[${out}] = ${group}.transform("${aggFn}")`,
      ].join("\n");
    }
    case "balance_panel": {
      const ent = pyStr(step.entityCol), tim = pyStr(step.timeCol);
      const dims = step.slotCol ? `[${ent}, ${tim}, ${pyStr(step.slotCol)}]` : `[${ent}, ${tim}]`;
      const outcomes = step.outcomeCols ?? [];
      const lines = [
        `# Balance panel: complete ${step.entityCol} × ${step.timeCol}${step.slotCol ? ` × ${step.slotCol}` : ""} grid (static cols may need manual carry-forward)`,
        `_dims = ${dims}`,
        `_full = pd.MultiIndex.from_product([df[c].unique() for c in _dims], names=_dims)`,
        `df = df.set_index(_dims).reindex(_full).reset_index()`,
      ];
      if (outcomes.length) lines.push(`df[${pyList(outcomes)}] = df[${pyList(outcomes)}].fillna(${Number(step.fillValue) || 0})`);
      return lines.join("\n");
    }
    case "distinct": {
      const subset = step.subset ?? params.subset ?? [];
      const keep = step.keep ?? params.keep ?? "first";
      const subsetArg = subset.length ? `subset=${pyList(subset)}, ` : "";
      return `df = df.drop_duplicates(${subsetArg}keep=${pyStr(keep)}).reset_index(drop=True)`;
    }
    case "join": {
      const how      = step.how || "left";
      const lk       = step.leftKey  ?? "id";
      const rk       = step.rightKey ?? lk;
      const sfx      = step.suffix   ?? "_r";
      const rightName = allDatasets[step.rightId]?.name ?? step.rightId;
      const byExpr   = lk === rk
        ? `on="${lk}"`
        : `left_on="${lk}", right_on="${rk}"`;
      if (how === "semi" || how === "anti") {
        const keepExpr = how === "semi"
          ? `df["${lk}"].isin(df_right["${rk}"])`
          : `~df["${lk}"].isin(df_right["${rk}"])`;
        return [
          `# ${how} join: filter rows using right dataset "${rightName}"`,
          `df_right = ${pyRightLoad(step.rightId, allDatasets)}`,
          `df = df[${keepExpr}].reset_index(drop=True)`,
        ].join("\n");
      }
      const pyHow = { left:"left", inner:"inner", right:"right", full:"outer" }[how] ?? "left";
      return [
        `# Join: load right dataset "${rightName}" and merge on ${lk}`,
        `df_right = ${pyRightLoad(step.rightId, allDatasets)}`,
        `df = df.merge(df_right, ${byExpr}, how="${pyHow}", suffixes=("", "${sfx}"))`,
      ].join("\n");
    }
    case "append": {
      const rightName = allDatasets[step.rightId]?.name ?? step.rightId;
      return [
        `# Append: stack right dataset "${rightName}" below current`,
        `df_right = ${pyRightLoad(step.rightId, allDatasets)}`,
        `df = pd.concat([df, df_right], ignore_index=True)`,
      ].join("\n");
    }
    case "bind_cols": {
      const rightName = allDatasets[step.rightId]?.name ?? step.rightId;
      return [
        `# bind_cols: align rows by current order from right dataset "${rightName}"`,
        `df_right = ${pyRightLoad(step.rightId, allDatasets)}`,
        `df = pd.concat([df.reset_index(drop=True), df_right.reset_index(drop=True)], axis=1)`,
      ].join("\n");
    }
    case "union":
    case "intersect":
    case "setdiff": {
      const rightName = allDatasets[step.rightId]?.name ?? step.rightId;
      const load = [
        `# ${type}: compare with right dataset "${rightName}"`,
        `df_right = ${pyRightLoad(step.rightId, allDatasets)}`,
      ];
      if (type === "union") {
        return [...load, `df = pd.concat([df, df_right], ignore_index=True).drop_duplicates().reset_index(drop=True)`].join("\n");
      }
      if (type === "intersect") {
        return [...load, `df = df.merge(df_right, how="inner").drop_duplicates().reset_index(drop=True)`].join("\n");
      }
      return [...load, `df = df.merge(df_right, how="left", indicator=True).query('_merge == "left_only"').drop(columns="_merge").reset_index(drop=True)`].join("\n");
    }
    case "vector_assign": {
      const vals = pyList(step.values ?? []);
      const out = step.nn ?? "assigned";
      const seed = Number.isFinite(Number(step.seed)) ? Number(step.seed) : 42;
      if (step.mode === "recycle") return `df["${out}"] = np.resize(${vals}, len(df))`;
      if (step.mode === "conditional") {
        const conds = (step.rules || []).map(r => `df.eval(${pyStr(r.expr)})`).join(", ");
        const choices = (step.rules || []).map(r => pyStr(r.value)).join(", ");
        return `df["${out}"] = np.select([${conds}], [${choices}], default=${pyStr(step.elseValue ?? "")})`;
      }
      const weights = Array.isArray(step.weights) ? step.weights.join(", ") : "";
      const p = weights ? `, p=np.array([${weights}]) / np.sum([${weights}])` : "";
      return `# NOTE: EconSolver uses a seeded mulberry32 RNG; exported values differ but the distribution matches\ndf["${out}"] = np.random.default_rng(${seed}).choice(${vals}, size=len(df)${p})`;
    }
    case "ai_tr": {
      const col    = step.col ?? "col";
      const jsCode = step.js  ?? "";
      const arrowMatch = jsCode.match(/^\s*\(?\s*(\w+)\s*\)?\s*=>\s*([\s\S]+)$/);
      if (arrowMatch) {
        const [, param, body] = arrowMatch;
        const colRef = `df["${col}"]`;
        const substituted = body.trim().replace(new RegExp(`\\b${param}\\b`, "g"), colRef);
        const pyExpr = jsExprToPython(substituted, "df");
        if (pyExpr) return `df["${col}"] = ${pyExpr}`;
      }
      return [
        `# AI transform on "${col}"`,
        `# JS: ${jsCode}`,
        `# df["${col}"] = <Python expression>`,
      ].join("\n");
    }
    case "patch": {
      const col = step.col ?? "column";
      const val = typeof step.value === "string" ? `"${step.value}"` : (step.value ?? "None");
      if (step.rowId) {
        return `df.loc[df["__row_id"] == "${step.rowId}", "${col}"] = ${val}`;
      }
      return `df.loc[df["__ri"] == ${step.ri}, "${col}"] = ${val}  # __ri-based: may misalign after sort`;
    }

    case "geocode": {
      const addrCol = step.addressCol ?? "address";
      const latCol  = step.latCol  ?? "lat";
      const lonCol  = step.lonCol  ?? "lon";
      return [
        `# Geocode: ${addrCol} → ${latCol} / ${lonCol}`,
        `# pip install geopy`,
        `from geopy.geocoders import Nominatim`,
        `from geopy.extra.rate_limiter import RateLimiter`,
        `_geolocator = Nominatim(user_agent="econsolver_replication")`,
        `_geocode    = RateLimiter(_geolocator.geocode, min_delay_seconds=1)`,
        `def _get_coords(address):`,
        `    loc = _geocode(str(address))`,
        `    return (loc.latitude, loc.longitude) if loc else (None, None)`,
        `df[["${latCol}", "${lonCol}"]] = df["${addrCol}"].apply(`,
        `    lambda a: pd.Series(_get_coords(a))`,
        `)`,
      ].join("\n");
    }

    case "inject_column": {
      const vals = (step.values ?? []).map(v => (v == null ? "np.nan" : Number(v).toFixed(8))).join(", ");
      return [
        `# inject_column: "${step.colName}" — extracted from model output`,
        `df["${step.colName}"] = np.array([${vals}])`,
      ].join("\n");
    }

    default:
      return `# [${type}] — not yet transpiled`;
  }
}

// ─── PYTHON FORMULA BUILDER ───────────────────────────────────────────────────
// Builds Patsy (statsmodels) RHS formula string. Uses xVarsRaw/wVarsRaw (pre-
// expansion) when available; factor vars wrapped in C(); interactions use * or :.
function buildPyFormulaStr(xVarsRaw, wVarsRaw, xVars, wVars, fvSet, interactionTerms) {
  const fmt  = v => fvSet.has(v) ? `C(${v})` : v;
  const rawX = xVarsRaw ?? xVars;
  const rawW = wVarsRaw ?? wVars;
  const parts = [...rawX, ...rawW].map(fmt);
  for (const { var1, var2, type } of (interactionTerms ?? [])) {
    if (!var1 || !var2) continue;
    const f1 = fmt(var1); const f2 = fmt(var2);
    if (type === "*") {
      const i1 = parts.indexOf(f1); if (i1 >= 0) parts.splice(i1, 1);
      const i2 = parts.indexOf(f2); if (i2 >= 0) parts.splice(i2, 1);
      parts.push(`${f1} * ${f2}`);
    } else {
      parts.push(`${f1} : ${f2}`);
    }
  }
  return parts.join(" + ") || "1";
}

// ─── MODEL TRANSPILER ─────────────────────────────────────────────────────────
function transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, distCol = null, treatmentCol = null, factorVars = [], feCols = null, offsetCol = null, treatedUnit, treatTime, weightCol = null, cohortCol = null, periodCol = null, controlMode = null, refPeriod = null, interactionTerms = [], xVarsRaw = null, wVarsRaw = null, seType = "classical", clusterVar = null, clusterVar2 = null, noIntercept = false }) {
  const lines = [];
  const fvSet    = new Set(factorVars);
  const fmtPy    = v => fvSet.has(v) ? `C(${v})` : v;
  const xFormula = allX.map(v => `"${v}"`).join(", ");
  const pyFormStr = buildPyFormulaStr(xVarsRaw, wVarsRaw, xVars, wVars, fvSet, interactionTerms);

  // statsmodels `.fit(...)` covariance argument matching the SE the user selected
  // in Litux (was hardcoded "HC3"). statsmodels supports HC1/HC2/HC3 natively.
  const smCov = () => {
    switch ((seType || "classical").toLowerCase()) {
      case "classical": return `cov_type="nonrobust"`;
      case "hc1":       return `cov_type="HC1"`;
      case "hc2":       return `cov_type="HC2"`;
      case "hc3":       return `cov_type="HC3"`;
      case "clustered": return clusterVar ? `cov_type="cluster", cov_kwds={"groups": df["${clusterVar}"]}` : `cov_type="HC1"`;
      // statsmodels has no CR2/CR3 — its "cluster" is CR1. Emitting CR1 silently
      // would misreport which estimator produced the SE, so the note below says so.
      case "cr2":
      case "cr3":       return clusterVar ? `cov_type="cluster", cov_kwds={"groups": df["${clusterVar}"]}` : `cov_type="HC1"`;
      case "twoway":    return (clusterVar && clusterVar2) ? `cov_type="cluster", cov_kwds={"groups": df[["${clusterVar}", "${clusterVar2}"]]}` : `cov_type="HC1"`;
      // Litux's Newey-West default bandwidth is L = floor(4*(n/100)^(2/9))
      // (see core/inference/robustSE.js). maxlags was hardcoded to 1, which is
      // that formula's answer only for tiny samples — reproduce it instead.
      case "hac":       return `cov_type="HAC", cov_kwds={"maxlags": int(np.floor(4 * (len(df) / 100) ** (2 / 9)))}`;
      default:          return `cov_type="nonrobust"`;
    }
  };
  // linearmodels IV2SLS `.fit(...)` covariance argument. Unlike statsmodels,
  // linearmodels has no HC2/HC3 — those fall back to its `robust` sandwich, so
  // the SE will differ slightly from Litux's. `ivCovNote()` says so out loud
  // rather than leaving the user to discover the mismatch numerically.
  const ivCov = () => {
    switch ((seType || "classical").toLowerCase()) {
      case "classical": return `cov_type="unadjusted"`;
      case "clustered": return clusterVar ? `cov_type="clustered", clusters=df["${clusterVar}"]` : `cov_type="robust"`;
      case "hac":       return `cov_type="kernel"`;
      default:          return `cov_type="robust"`;   // HC1/HC2/HC3 → robust sandwich
    }
  };
  // linearmodels PanelOLS / FirstDifferenceOLS `.fit(...)` covariance argument.
  // These call sites used to hardcode cov_type="clustered", cluster_entity=True
  // regardless of the user's selection, which disagreed with the platform: with
  // the default seType="classical", computeRobustSE returns classical SE — it
  // does not cluster by entity.
  const panelCov = () => {
    const s = (seType || "classical").toLowerCase();
    switch (s) {
      case "classical": return `cov_type="unadjusted"`;
      case "hc1": case "hc2": case "hc3": return `cov_type="robust"`;
      case "clustered":
        return (clusterVar && clusterVar !== entityCol)
          ? `cov_type="clustered", clusters=df_panel["${clusterVar}"]`
          : `cov_type="clustered", cluster_entity=True`;
      case "twoway": return `cov_type="clustered", cluster_entity=True, cluster_time=True`;
      case "hac":    return `cov_type="kernel"`;   // Driscoll-Kraay
      default:       return `cov_type="unadjusted"`;
    }
  };
  const panelCovNote = () => {
    const s = (seType || "classical").toLowerCase();
    if (s === "hc2" || s === "hc3") {
      return [`# NOTE: Litux used ${s.toUpperCase()} SE. linearmodels' panel estimators have no`,
              `# HC2/HC3 option; this uses cov_type="robust" — expect a small SE difference.`];
    }
    return [];
  };
  // pyfixest `vcov=` argument (fepois / feols). Same vocabulary as R's fixest:
  // "iid" / "hetero" / {"CRV1": col}. Was hardcoded to CRV1 on the first FE column.
  const pfVcov = () => {
    const s = (seType || "classical").toLowerCase();
    switch (s) {
      case "classical": return `"iid"`;
      case "hc1": case "hc2": case "hc3": return `"hetero"`;
      case "clustered":
      case "twoway":    return clusterVar ? `{"CRV1": "${clusterVar}"}` : `"hetero"`;
      default:          return `"iid"`;
    }
  };
  const ivCovNote = () => {
    const s = (seType || "classical").toLowerCase();
    if (s === "hc2" || s === "hc3") {
      return [`# NOTE: Litux used ${s.toUpperCase()} SE. linearmodels has no HC2/HC3 option;`,
              `# this uses its 'robust' sandwich (HC0-family) — expect a small SE difference.`];
    }
    if (s === "hac") {
      return [`# NOTE: cov_type="kernel" defaults to Bartlett with linearmodels' own`,
              `# automatic bandwidth, which may differ from Litux's L = floor(4*(n/100)^(2/9)).`];
    }
    return [];
  };

  switch (type) {
    case "OLS": {
      if (["cr2", "cr3"].includes((seType || "").toLowerCase())) {
        lines.push(`# NOTE: Litux reported ${(seType || "").toUpperCase()} (bias-reduced cluster-robust) SE.`);
        lines.push(`# statsmodels has no CR2/CR3; the line below gives CR1, which will differ.`);
        lines.push(`# For the exact SE use R: clubSandwich::coef_test(fit, vcov = "${(seType || "").toUpperCase()}", cluster = ...)`);
      }
      // patsy spells "no intercept" as a trailing `- 1`.
      const formula = `"${yVar} ~ ${pyFormStr}${noIntercept ? " - 1" : ""}"`;
      if (noIntercept) lines.push(`# Regression through the origin — no intercept estimated.`);
      lines.push(`model = smf.ols(${formula}, data=df).fit(${smCov()})`);
      lines.push(`print(model.summary())`);
      break;
    }

    case "WLS": {
      const formula = `"${yVar} ~ ${pyFormStr}"`;
      if (!weightCol) {
        lines.push(`# WARNING: no weight column supplied; falling back to OLS`);
        lines.push(`model = smf.ols(${formula}, data=df).fit(${smCov()})`);
      } else {
        lines.push(`# Weighted Least Squares (weights: ${weightCol})`);
        lines.push(`model = smf.wls(${formula}, data=df, weights=df["${weightCol}"]).fit(${smCov()})`);
      }
      lines.push(`print(model.summary())`);
      break;
    }

    case "FE": {
      // N-way FE: spec.feCols (Task 3-5) generalizes absorption beyond entity-only.
      // Fallback preserves the pre-existing entity-only default byte-for-byte.
      const feColsFE = feCols?.length ? feCols : [entityCol].filter(Boolean);
      if (feColsFE.length <= 2) {
        lines.push(`# Fixed Effects (within estimator)`);
        lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
        lines.push(`exog = sm.add_constant(df_panel[[${xFormula}]])`);
        lines.push(...panelCovNote());
      lines.push(`model = PanelOLS(df_panel["${yVar}"], exog, entity_effects=True).fit(${panelCov()})`);
        lines.push(`print(model.summary)`);
      } else {
        lines.push(`# linearmodels.PanelOLS only supports entity + time effects natively.`);
        lines.push(`# For a 3rd+ FE dimension, absorb via one-hot dummies through statsmodels instead:`);
        lines.push(`import statsmodels.formula.api as smf`);
        const dummyTerms = feColsFE.map(c => `C(${c})`).join(" + ");
        lines.push(`# drop the global intercept: multiple C(col) absorptions already span the`);
        lines.push(`# level space between them, so keeping a separate intercept would double-count`);
        lines.push(`model = smf.ols("${yVar} ~ ${pyFormStr} + ${dummyTerms} - 1", data=df).fit(${smCov()})`);
        lines.push(`print(model.summary())`);
      }
      break;
    }

    case "FD": {
      lines.push(`# First Differences estimator`);
      lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
      lines.push(`exog = sm.add_constant(df_panel[[${xFormula}]])`);
      lines.push(...panelCovNote());
      lines.push(`model = FirstDifferenceOLS(df_panel["${yVar}"], exog).fit(${panelCov()})`);
      lines.push(`print(model.summary)`);
      break;
    }

    case "2SLS": {
      const endog = xVars.map(v => `"${v}"`).join(", ");
      const instr = zVars.map(v => `"${v}"`).join(", ");
      const exogX = wVars.map(v => `"${v}"`).join(", ");
      lines.push(`# Two-Stage Least Squares (IV)`);
      if (entityCol && timeCol) {
        // Panel IV
        lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
        lines.push(`dependent  = df_panel["${yVar}"]`);
        lines.push(exogX ? `exog_vars  = sm.add_constant(df_panel[[${exogX}]])` : `exog_vars  = None`);
        lines.push(`endog_vars = df_panel[[${endog}]]`);
        lines.push(`instr_vars = df_panel[[${instr}]]`);
      } else {
        // Cross-sectional IV
        lines.push(`dependent  = df["${yVar}"]`);
        lines.push(exogX ? `exog_vars  = sm.add_constant(df[[${exogX}]])` : `exog_vars  = None`);
        lines.push(`endog_vars = df[[${endog}]]`);
        lines.push(`instr_vars = df[[${instr}]]`);
      }
      lines.push(...ivCovNote());
      lines.push(`model = IV2SLS(dependent, exog_vars, endog_vars, instr_vars).fit(${ivCov()})`);
      lines.push(`print(model.summary)`);
      break;
    }

    case "DiD": {
      const xExtra = wVars.length ? ` + ${wVars.join(" + ")}` : "";
      lines.push(`# Difference-in-Differences (2×2)`);
      lines.push(`df["did"] = df["${postVar}"] * df["${treatVar}"]`);
      lines.push(`model = smf.ols("${yVar} ~ ${postVar} + ${treatVar} + did${xExtra}", data=df).fit(${smCov()})`);
      lines.push(`print(model.summary())`);
      lines.push(`print(f"ATT = {model.params['did']:.4f}  SE = {model.bse['did']:.4f}  p = {model.pvalues['did']:.4f}")`);
      break;
    }

    case "TWFE": {
      // N-way FE: spec.feCols (Task 3-5) generalizes absorption beyond entity+time.
      // Fallback preserves the pre-existing entity+time default byte-for-byte.
      const feColsTWFE = feCols?.length ? feCols : [entityCol, timeCol].filter(Boolean);
      const extraX = wVars.length ? `, ${wVars.map(v=>`"${v}"`).join(", ")}` : "";
      if (feColsTWFE.length <= 2) {
        lines.push(`# Two-Way Fixed Effects DiD`);
        lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
        lines.push(`exog = sm.add_constant(df_panel[["${treatVar}"${extraX}]])`);
        lines.push(...panelCovNote());
      lines.push(`model = PanelOLS(df_panel["${yVar}"], exog, entity_effects=True, time_effects=True).fit(${panelCov()})`);
        lines.push(`print(model.summary)`);
      } else {
        lines.push(`# linearmodels.PanelOLS only supports entity + time effects natively.`);
        lines.push(`# For a 3rd+ FE dimension, absorb via one-hot dummies through statsmodels instead:`);
        lines.push(`import statsmodels.formula.api as smf`);
        const dummyTerms = feColsTWFE.map(c => `C(${c})`).join(" + ");
        const extraTerms = wVars.length ? ` + ${wVars.join(" + ")}` : "";
        lines.push(`model = smf.ols("${yVar} ~ ${treatVar}${extraTerms} + ${dummyTerms} - 1", data=df).fit(${smCov()})`);
        lines.push(`print(model.summary())`);
      }
      break;
    }

    case "RDD": {
      const kernelStr = kernel === "epanechnikov" ? "epanechnikov" : kernel === "uniform" ? "uniform" : "triangular";
      const extraCols = wVars.length ? ` + ${wVars.join(" + ")}` : "";
      const h_py = bandwidth ? Number(bandwidth).toFixed(6) : "None  # replace with numeric bandwidth";
      lines.push(`# Sharp Regression Discontinuity Design`);
      lines.push(`cutoff = ${cutoff ?? 0}`);
      lines.push(`bw     = ${h_py}`);
      lines.push(`# ── Preferred: rdrobust package ──────────────────────────────────────`);
      lines.push(`# pip install rdrobust`);
      lines.push(`try:`);
      lines.push(`    from rdrobust import rdrobust`);
      lines.push(`    rdd = rdrobust(y=df["${yVar}"].values, x=df["${runningVar}"].values, c=cutoff${bandwidth ? `, h=bw` : ""}${kernelStr !== "triangular" ? `, kernel="${kernelStr}"` : ""}${wVars.length ? `, covs=df[${JSON.stringify(wVars)}].values` : ""})`);
      lines.push(`    print(rdd.summary())`);
      lines.push(`    print(f"LATE = {rdd.coef[0]:.4f}  SE = {rdd.se[3]:.4f}  p = {rdd.pv[3]:.4f}")`);
      lines.push(`except ImportError:`);
      lines.push(`    # ── Fallback: manual local-linear WLS ────────────────────────────`);
      lines.push(`    df_rdd = df[(df["${runningVar}"] >= cutoff - bw) & (df["${runningVar}"] <= cutoff + bw)].copy()`);
      lines.push(`    df_rdd["above"] = (df_rdd["${runningVar}"] >= cutoff).astype(int)`);
      lines.push(`    df_rdd["run_c"] = df_rdd["${runningVar}"] - cutoff`);
      if (kernelStr === "triangular") {
        lines.push(`    df_rdd["_w"] = np.maximum(0, 1 - np.abs(df_rdd["run_c"]) / bw)`);
      } else if (kernelStr === "epanechnikov") {
        lines.push(`    df_rdd["_w"] = np.where(np.abs(df_rdd["run_c"] / bw) <= 1, 0.75 * (1 - (df_rdd["run_c"]/bw)**2), 0)`);
      } else {
        lines.push(`    df_rdd["_w"] = 1.0`);
      }
      lines.push(`    model = smf.wls("${yVar} ~ above + run_c + above:run_c${extraCols}", data=df_rdd, weights=df_rdd["_w"]).fit(${smCov()})`);
      lines.push(`    print(model.summary())`);
      lines.push(`    print(f"LATE = {model.params['above']:.4f}  SE = {model.bse['above']:.4f}  p = {model.pvalues['above']:.4f}")`);
      break;
    }

    case "Logit":
    case "Probit": {
      const formula = `"${yVar} ~ ${pyFormStr}"`;
      const fn = type === "Logit" ? "logit" : "probit";
      lines.push(`# ${type} regression`);
      lines.push(`model = smf.${fn}(${formula}, data=df).fit()`);
      lines.push(`print(model.summary())`);
      lines.push(`# Marginal effects at the mean`);
      lines.push(`print(model.get_margeff().summary())`);
      break;
    }

    case "LSDV": {
      // N-way FE: spec.feCols (Task 3-5) generalizes absorption beyond entity(+time).
      // Fallback preserves the pre-existing entity(+time) default byte-for-byte.
      const feColsLSDV = feCols?.length ? feCols : [entityCol, timeCol].filter(Boolean);
      if (feColsLSDV.length <= 2) {
        lines.push(`# Panel LSDV (numerically equivalent to within/FE)`);
        lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
        lines.push(`exog = sm.add_constant(df_panel[[${xFormula}]])`);
        lines.push(...panelCovNote());
      lines.push(`model = PanelOLS(df_panel["${yVar}"], exog, entity_effects=True${timeCol ? ", time_effects=True" : ""}).fit(${panelCov()})`);
        lines.push(`print(model.summary)`);
        lines.push(``);
        lines.push(`# Recover entity fixed effects (LSDV alpha_i)`);
        lines.push(`entity_fe = model.estimated_effects`);
        lines.push(`print("Entity fixed effects (first 20):")`);
        lines.push(`print(entity_fe.groupby(level="${entityCol}").first().head(20))`);
      } else {
        lines.push(`# linearmodels.PanelOLS only supports entity + time effects natively.`);
        lines.push(`# For a 3rd+ FE dimension, absorb via one-hot dummies through statsmodels instead:`);
        lines.push(`import statsmodels.formula.api as smf`);
        const dummyTerms = feColsLSDV.map(c => `C(${c})`).join(" + ");
        lines.push(`# drop the global intercept: multiple C(col) absorptions already span the`);
        lines.push(`# level space between them, so keeping a separate intercept would double-count`);
        lines.push(`model = smf.ols("${yVar} ~ ${pyFormStr} + ${dummyTerms} - 1", data=df).fit(${smCov()})`);
        lines.push(`print(model.summary())`);
        lines.push(``);
        lines.push(`# Recover entity fixed effects (LSDV alpha_i) — explicit dummy coefficients for "${entityCol}"`);
        lines.push(`entity_fe = model.params.filter(like="C(${entityCol})")`);
        lines.push(`print("Entity fixed effects (first 20):")`);
        lines.push(`print(entity_fe.head(20))`);
      }
      break;
    }

    case "FuzzyRDD": {
      const kernelStr = kernel === "epanechnikov" ? "epanechnikov"
                      : kernel === "uniform"      ? "uniform"
                      : "triangular";
      const dVar   = treatVar ?? "D";
      const extraCols = wVars.length ? ` + ${wVars.join(" + ")}` : "";
      const h_fpy = bandwidth ? Number(bandwidth).toFixed(6) : "None  # set bandwidth";
      lines.push(`# Fuzzy RDD — LATE for compliers`);
      lines.push(`cutoff = ${cutoff ?? 0}`);
      lines.push(`bw     = ${h_fpy}`);
      lines.push(`# ── Preferred: rdrobust package ──────────────────────────────────────`);
      lines.push(`# pip install rdrobust`);
      lines.push(`try:`);
      lines.push(`    from rdrobust import rdrobust`);
      lines.push(`    rdd = rdrobust(y=df["${yVar}"].values, x=df["${runningVar}"].values,`);
      lines.push(`                   fuzzy=df["${dVar}"].values, c=cutoff${bandwidth ? `, h=bw` : ""}${kernelStr !== "triangular" ? `, kernel="${kernelStr}"` : ""}${wVars.length ? `, covs=df[${JSON.stringify(wVars)}].values` : ""})`);
      lines.push(`    print(rdd.summary())`);
      lines.push(`    print(f"LATE (Fuzzy) = {rdd.coef[0]:.4f}  SE = {rdd.se[3]:.4f}  p = {rdd.pv[3]:.4f}")`);
      lines.push(`except ImportError:`);
      lines.push(`    # ── Fallback: manual kernel-weighted 2SLS ────────────────────────`);
      lines.push(`    df_bw = df[(df["${runningVar}"] >= cutoff - bw) & (df["${runningVar}"] <= cutoff + bw)].copy()`);
      lines.push(`    df_bw["_Z"]     = (df_bw["${runningVar}"] >= cutoff).astype(int)`);
      lines.push(`    df_bw["_run_c"] = df_bw["${runningVar}"] - cutoff`);
      if (kernelStr === "triangular") {
        lines.push(`    df_bw["_w"] = np.maximum(0, 1 - np.abs(df_bw["_run_c"]) / bw)`);
      } else if (kernelStr === "epanechnikov") {
        lines.push(`    df_bw["_w"] = np.where(np.abs(df_bw["_run_c"] / bw) <= 1, 0.75 * (1 - (df_bw["_run_c"]/bw)**2), 0)`);
      } else {
        lines.push(`    df_bw["_w"] = 1.0`);
      }
      lines.push(`    # First stage: Z -> D`);
      lines.push(`    fs = smf.wls("${dVar} ~ _Z + _run_c + _Z:_run_c${extraCols}", data=df_bw, weights=df_bw["_w"]).fit(${smCov()})`);
      lines.push(`    print(f"First-stage F-stat: {fs.fvalue:.2f}  (p={fs.f_pvalue:.4f})")`);
      lines.push(`    # Second stage: use D_hat as instrument`);
      lines.push(`    df_bw["_D_hat"] = fs.fittedvalues`);
      lines.push(`    ss = smf.wls("${yVar} ~ _D_hat + _run_c + _D_hat:_run_c${extraCols}", data=df_bw, weights=df_bw["_w"]).fit(${smCov()})`);
      lines.push(`    print(ss.summary())`);
      lines.push(`    print(f"LATE = {ss.params['_D_hat']:.4f}  SE = {ss.bse['_D_hat']:.4f}  p = {ss.pvalues['_D_hat']:.4f}")`);
      break;
    }

    case "SpatialRDD": {
      const kernelStr = kernel === "epanechnikov" ? "epanechnikov"
                      : kernel === "uniform"      ? "uniform"
                      : "triangular";
      const distV  = distCol      ?? runningVar ?? "dist";
      const trtV   = treatmentCol ?? treatVar   ?? "treatment";
      const h      = bandwidth ? Number(bandwidth).toFixed(6) : null;
      const extraCols = wVars.length ? ` + ${wVars.join(" + ")}` : "";
      lines.push(`# Spatial RD (Keele & Titiunik 2015)`);
      lines.push(`# Build signed running variable: positive = treated side, cutoff = 0`);
      lines.push(`df["_signed_dist"] = (2 * df["${trtV}"] - 1) * df["${distV}"].abs()`);
      lines.push(`bw = ${h ?? "None  # replace with numeric bandwidth"}`);
      lines.push(`df_rdd = df[(df["_signed_dist"] >= -bw) & (df["_signed_dist"] <= bw)].copy()`);
      if (kernelStr === "triangular") {
        lines.push(`df_rdd["_w"] = np.maximum(0, 1 - np.abs(df_rdd["_signed_dist"]) / bw)`);
      } else if (kernelStr === "epanechnikov") {
        lines.push(`df_rdd["_w"] = np.where(np.abs(df_rdd["_signed_dist"] / bw) <= 1, 0.75 * (1 - (df_rdd["_signed_dist"] / bw)**2), 0)`);
      } else {
        lines.push(`df_rdd["_w"] = 1.0`);
      }
      lines.push(`df_rdd["_above"] = (df_rdd["_signed_dist"] >= 0).astype(int)`);
      lines.push(`model = smf.wls("${yVar} ~ _above + _signed_dist + _above:_signed_dist${extraCols}", data=df_rdd, weights=df_rdd["_w"]).fit(${smCov()})`);
      lines.push(`print(model.summary())`);
      lines.push(`print(f"LATE at boundary = {model.params['_above']:.4f}  SE = {model.bse['_above']:.4f}  p = {model.pvalues['_above']:.4f}")`);
      break;
    }

    case "EventStudy": {
      const extraCols = wVars.map(v => `"${v}"`).join(", ");
      // N-way FE: spec.feCols (Task 3-5) generalizes absorption beyond entity+time.
      // Fallback preserves the pre-existing entity+time default byte-for-byte.
      const feColsES = feCols?.length ? feCols : [entityCol, timeCol].filter(Boolean);
      lines.push(`# Event Study — relative-time dummies`);
      lines.push(`# Replace 'treat_time' with the column holding each unit's treatment period`);
      lines.push(`df["rel_time"] = df["${timeCol}"] - df["treat_time"]`);
      lines.push(`df["rel_time"] = df["rel_time"].clip(-5, 5)  # truncate distant periods`);
      if (feColsES.length <= 2) {
        lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
        lines.push(`rel_dummies = pd.get_dummies(df_panel["rel_time"], prefix="rt", drop_first=False)`);
        lines.push(`rel_dummies = rel_dummies.drop(columns=["rt_-1"], errors="ignore")  # ref = -1`);
        if (wVars.length) {
          lines.push(`exog = sm.add_constant(pd.concat([rel_dummies, df_panel[[${extraCols}]]], axis=1))`);
        } else {
          lines.push(`exog = sm.add_constant(rel_dummies)`);
        }
        lines.push(`from linearmodels.panel import PanelOLS`);
        lines.push(...panelCovNote());
      lines.push(`model = PanelOLS(df_panel["${yVar}"], exog, entity_effects=True, time_effects=True).fit(${panelCov()})`);
        lines.push(`print(model.summary)`);
      } else {
        lines.push(`# linearmodels.PanelOLS only supports entity + time effects natively.`);
        lines.push(`# For a 3rd+ FE dimension, absorb via one-hot dummies through statsmodels instead:`);
        lines.push(`import statsmodels.formula.api as smf`);
        lines.push(`rel_dummies = pd.get_dummies(df["rel_time"], prefix="rt", drop_first=False)`);
        lines.push(`rel_dummies = rel_dummies.drop(columns=["rt_-1"], errors="ignore")  # ref = -1`);
        lines.push(`df = pd.concat([df, rel_dummies], axis=1)`);
        lines.push(`rt_terms = " + ".join(rel_dummies.columns)`);
        const dummyTerms = feColsES.map(c => `C(${c})`).join(" + ");
        const extraTerms = wVars.length ? ` + ${wVars.join(" + ")}` : "";
        lines.push(`# drop the global intercept: multiple C(col) absorptions already span the`);
        lines.push(`# level space between them, so keeping a separate intercept would double-count`);
        lines.push(`model = smf.ols(f"${yVar} ~ {rt_terms}${extraTerms} + ${dummyTerms} - 1", data=df).fit(${smCov()})`);
        lines.push(`print(model.summary())`);
      }
      break;
    }

    case "SunAbraham": {
      const coh = cohortCol ?? "cohort";
      const per = periodCol ?? timeCol ?? "period";
      const fes = (feCols && feCols.length ? feCols : [entityCol ?? "unit", per]);
      const feStr = fes.join(" + ");
      const cl = fes[0];
      const ctrls = (xVars ?? []).length ? " + " + xVars.join(" + ") : "";
      const ref = refPeriod != null ? Number(refPeriod) : -1;
      lines.push(`# ── Sun & Abraham (2021) interaction-weighted event study over Poisson PPML ──`);
      lines.push(`# Control convention: ${controlMode === "never" ? "never-treated only" : "never- + not-yet-treated (auto)"}`);
      lines.push(`# Reference relative period: ${ref}  (omitted from the event-study path)`);
      lines.push(`# pip install pyfixest`);
      lines.push(`import pyfixest as pf`);
      lines.push(`# sunab(cohort, period) builds the saturated cohort x relative-period interactions`);
      lines.push(`# and auto-aggregates to interaction-weighted per-relative-period ATTs.`);
      lines.push(`fit = pf.fepois("${yVar} ~ sunab(${coh}, ${per})${ctrls} | ${feStr}", data=df, vcov=${pfVcov()})`);
      lines.push(`pf.etable([fit])`);
      lines.push(`import numpy as np`);
      lines.push(`print("IRR (exp of event-study coefficients):", np.exp(fit.coef().values))`);
      lines.push(`# Event-study path plot`);
      lines.push(`pf.iplot([fit])`);
      break;
    }

    case "SyntheticControl": {
      const ec = entityCol ?? "unit";
      const tc = timeCol   ?? "time";
      const tu = treatedUnit ?? "TreatedUnit";
      const tt = treatTime != null ? Number(treatTime) : "TREAT_TIME";
      const predsStr = (xVars ?? []).length
        ? `[${(xVars ?? []).map(v => `"${v}"`).join(", ")}]`
        : "[]  # no explicit predictors — outcome mean used";
      lines.push(`# ── Synthetic Control (pysynth / scipy fallback) ─────────────────────`);
      lines.push(`# Install: pip install pysynth  (or use scipy.optimize directly)`);
      lines.push(`# pysynth wraps the Frank-Wolfe algorithm used by the Synth R package`);
      lines.push(`try:`);
      lines.push(`    from pysynth import Synth`);
      lines.push(`    sc = Synth()`);
      lines.push(`    sc.fit(`);
      lines.push(`        df,`);
      lines.push(`        outcome_var="${yVar}",`);
      lines.push(`        id_var="${ec}",`);
      lines.push(`        time_var="${tc}",`);
      lines.push(`        treatment_identifier="${tu}",`);
      lines.push(`        treatment_time=${tt},`);
      lines.push(`        predictors=${predsStr},`);
      lines.push(`    )`);
      lines.push(`    sc.plot()          # path plot`);
      lines.push(`    sc.gaps_plot()     # gap plot`);
      lines.push(`    print(sc.weights)  # donor weights`);
      lines.push(`except ImportError:`);
      lines.push(`    # ── Manual Frank-Wolfe via scipy ─────────────────────────────────`);
      lines.push(`    import numpy as np`);
      lines.push(`    from scipy.optimize import minimize`);
      lines.push(`    pre = df[df["${tc}"] < ${tt}]`);
      lines.push(`    donors = df["${ec}"].unique().tolist()`);
      lines.push(`    donors = [d for d in donors if d != "${tu}"]`);
      lines.push(`    Y_treated = pre[pre["${ec}"] == "${tu}"]["${yVar}"].values`);
      lines.push(`    Y_donors  = np.column_stack([pre[pre["${ec}"] == d]["${yVar}"].values for d in donors])`);
      lines.push(`    def loss(w): return np.sum((Y_treated - Y_donors @ w) ** 2)`);
      lines.push(`    w0     = np.ones(len(donors)) / len(donors)`);
      lines.push(`    cons   = {"type": "eq", "fun": lambda w: np.sum(w) - 1}`);
      lines.push(`    bounds = [(0, 1)] * len(donors)`);
      lines.push(`    res    = minimize(loss, w0, method="SLSQP", bounds=bounds, constraints=cons)`);
      lines.push(`    weights = dict(zip(donors, res.x))`);
      lines.push(`    print("Donor weights:", {k: round(v, 4) for k, v in weights.items() if v > 0.001})`);
      break;
    }

    case "GMM": {
      const xList = xVars.map(v => `"${v}"`).join(", ");
      const wList = wVars.map(v => `"${v}"`).join(", ");
      const zList = [...xVars, ...zVars].map(v => `"${v}"`).join(", ");
      lines.push(`# Two-Step Efficient GMM`);
      lines.push(`from linearmodels.iv import IVGMM`);
      lines.push(`dependent  = df["${yVar}"]`);
      lines.push(`exog_vars  = sm.add_constant(df[[${xList || `"# add exog columns"`}]])` );
      lines.push(`endog_vars = df[[${wList || `"# add endogenous columns"`}]]`);
      lines.push(`instr_vars = df[[${zList || `"# add instrument columns"`}]]`);
      lines.push(`model = IVGMM(dependent, exog_vars, endog_vars, instr_vars).fit(${ivCov()})`);
      lines.push(`print(model.summary)`);
      lines.push(`# J-statistic (over-identification test)`);
      lines.push(`print(f"J-stat: {model.j_stat.stat:.4f}  p={model.j_stat.pval:.4f}")`);
      break;
    }

    case "LIML": {
      const xList = xVars.map(v => `"${v}"`).join(", ");
      const wList = wVars.map(v => `"${v}"`).join(", ");
      const zList = [...xVars, ...zVars].map(v => `"${v}"`).join(", ");
      lines.push(`# Limited Information Maximum Likelihood (LIML)`);
      lines.push(`from linearmodels.iv import IVLIML`);
      lines.push(`dependent  = df["${yVar}"]`);
      lines.push(`exog_vars  = sm.add_constant(df[[${xList || `"# add exog columns"`}]])`);
      lines.push(`endog_vars = df[[${wList || `"# add endogenous columns"`}]]`);
      lines.push(`instr_vars = df[[${zList || `"# add instrument columns"`}]]`);
      lines.push(`model = IVLIML(dependent, exog_vars, endog_vars, instr_vars).fit(${ivCov()})`);
      lines.push(`print(model.summary)`);
      lines.push(`# kappa: 1 = just-identified (= 2SLS); > 1 = over-identified`);
      lines.push(`print(f"kappa = {model.kappa:.6f}")`);
      break;
    }

    case "Poisson": {
      const formula = `"${yVar} ~ ${pyFormStr}"`;
      lines.push(`# Poisson regression (count GLM, log link)`);
      lines.push(`model = smf.glm(${formula},`);
      lines.push(`    data=df, family=sm.families.Poisson()).fit(${smCov()})`);
      lines.push(`print(model.summary())`);
      lines.push(`# Incidence Rate Ratios (exp(beta))`);
      lines.push(`print("IRR:")`);
      lines.push(`print(np.exp(model.params))`);
      lines.push(`# Overdispersion check: Pearson chi-sq / df (>> 1 -> consider NB/QMLE)`);
      lines.push(`print(f"Pearson chi2/df = {model.pearson_chi2 / model.df_resid:.4f}")`);
      break;
    }

    case "PoissonFE": {
      const fes = (feCols && feCols.length ? feCols : [entityCol ?? "entity"]);
      const feStr = fes.join(" + ");
      lines.push(`# Poisson FE (PPML with ${fes.length}-way fixed effects)`);
      lines.push(`# Option 1 — pyfixest (mirrors R's fixest)`);
      lines.push(`# pip install pyfixest`);
      lines.push(`try:`);
      lines.push(`    import pyfixest as pf`);
      lines.push(`    fit = pf.fepois("${yVar} ~ ${xVars.join(" + ") || "1"} | ${feStr}", data=df, vcov=${pfVcov()})`);
      lines.push(`    pf.etable([fit])`);
      lines.push(`    import numpy as np`);
      lines.push(`    print("IRR:", np.exp(fit.coef().values))`);
      lines.push(`except ImportError:`);
      lines.push(`    # Option 2 — statsmodels GLM with FE dummies (slow for large N)`);
      lines.push(`    import statsmodels.formula.api as smf`);
      lines.push(`    model = smf.glm("${yVar} ~ ${[...xVars, ...fes.map(f => `C(${f})`)].join(" + ") || "1"}",`);
      lines.push(`        data=df, family=sm.families.Poisson()).fit(${smCov()})`);
      lines.push(`    print(model.summary())`);
      lines.push(`    import numpy as np`);
      lines.push(`    print("IRR:", np.exp(model.params))`);
      break;
    }

    case "NegBinFE": {
      const fes = (feCols && feCols.length ? feCols : [entityCol ?? "entity"]);
      const rhs = [...xVars, ...fes.map(f => `C(${f})`)].join(" + ") || "1";
      const formula = `"${yVar} ~ ${rhs}"`;
      lines.push(`# Negative Binomial FE (NB2 with fixed-effect dummies)`);
      if (offsetCol) {
        lines.push(`model = smf.negativebinomial(${formula}, data=df, offset=np.log(df["${offsetCol}"])).fit()`);
      } else {
        lines.push(`model = smf.negativebinomial(${formula}, data=df).fit()`);
      }
      lines.push(`print(model.summary())`);
      lines.push(`print("IRR:")`);
      lines.push(`print(np.exp(model.params))`);
      break;
    }

    case "McCrary": {
      const rv = runningVar ?? "running";
      const c0 = cutoff ?? 0;
      lines.push(`# McCrary / Cattaneo-Jansson-Ma density test`);
      lines.push(`# pip install rddensity`);
      lines.push(`from rddensity import rddensity`);
      lines.push(`fit = rddensity(X=df["${rv}"], c=${c0})`);
      lines.push(`print(fit.summary())`);
      lines.push(`# Density plot`);
      lines.push(`from rddensity import rdplotdensity`);
      lines.push(`rdplotdensity(fit, df["${rv}"], xlabel="${rv}")`);
      break;
    }

    case "CallawayCS": {
      // Callaway-Sant'Anna (2021) staggered DiD via csdid package
      const csY = yVar;
      const { xVars: csXVars = [], csCompGroup = "nevertreated",
              csEstMethod = "dr", csAnticipation = 0 } = model;

      // Build xformla: if xVars empty or ["~1"], use ~1; else ~ X1 + X2 + ...
      const xformlaRhs = (csXVars && csXVars.length && !csXVars.includes("~1"))
        ? csXVars.join(" + ")
        : "1";
      const xformla = `~${xformlaRhs}`;

      lines.push(`# Callaway-Sant'Anna (2021) Staggered DiD`);
      lines.push(`# pip install csdid`);
      lines.push(`from csdid import att_gt, aggte`);
      lines.push(``);
      lines.push(`result = att_gt(`);
      lines.push(`    yname      = "${csY}",`);
      lines.push(`    gname      = "${treatVar}",`);
      lines.push(`    idname     = "${entityCol}",`);
      lines.push(`    tname      = "${timeCol}",`);
      lines.push(`    xformla    = "${xformla}",`);
      lines.push(`    data       = df,`);
      lines.push(`    control_group = "${csCompGroup}",`);
      lines.push(`    base_period   = "varying",`);
      lines.push(`    anticipation  = ${csAnticipation},`);
      lines.push(`    est_method    = "${csEstMethod}"`);
      lines.push(`)`);
      lines.push(``);
      lines.push(`print(result.summary())`);
      lines.push(``);
      lines.push(`# Aggregations by cohort (group)`);
      lines.push(`aggte(result, type="group")`);
      lines.push(``);
      lines.push(`# Aggregations by event (relative period)`);
      lines.push(`aggte(result, type="dynamic")`);
      lines.push(``);
      lines.push(`# Calendar time aggregation`);
      lines.push(`aggte(result, type="calendar")`);
      lines.push(``);
      lines.push(`# Simple overall ATT`);
      lines.push(`aggte(result, type="simple")`);
      break;
    }

    default:
      lines.push(`# Model type "${type}" — add estimation code here`);
  }

  return lines;
}

// ─── MULTI-MODEL HELPERS ─────────────────────────────────────────────��────────

function detectMapPatternPy(configs) {
  if (configs.length < 2) return "separate";
  const allHaveMeta = configs.every(c => Array.isArray(c.subsetFilters));
  if (!allHaveMeta) return "separate";
  const first = configs[0].model;
  const xKey  = arr => JSON.stringify([...(arr ?? [])].sort());
  return configs.every(c =>
    c.model.type === first.type &&
    c.model.yVar === first.yVar &&
    xKey(c.model.xVars) === xKey(first.xVars)
  ) ? "map" : "separate";
}

function subsetFiltersToPython(filters, dfName = "df") {
  if (!filters?.length) return null;
  const parts = filters.map(f => {
    const val = isNaN(Number(f.val)) ? `"${f.val}"` : f.val;
    return `(${dfName}["${f.col}"] ${f.op} ${val})`;
  });
  return `${dfName}[${parts.join(" & ")}]`;
}

// ─── MULTI-MODEL EXPORT ────────────────────────────────────────────────────────
// configs: Array of { model: ModelConfig, label: string, subsetName?, subsetFilters? }
// opts:    { filename?: string, pipeline?: Step[] }
export function generateMultiModelPythonScript(configs = [], dataDictionary = null, opts = {}) {
  if (!configs.length) return "# No models provided.";

  const filename     = opts.filename ?? "dataset.csv";
  const pipeline     = opts.pipeline ?? [];
  const dataLoadOpts = opts.dataLoadOpts ?? null;
  const pyFile       = filename.replace(/\\/g, "/");
  const ts = new Date().toISOString().slice(0, 10);
  const lines = [];

  lines.push(`# ${"─".repeat(72)}`);
  lines.push(`# Multi-model replication script — generated by Litux`);
  lines.push(`# Models: ${configs.map((c, i) => `(${i+1}) ${c.label ?? c.model?.type}`).join(", ")}`);
  lines.push(`# Generated: ${ts}`);
  lines.push(`# ${"─".repeat(72)}`);
  lines.push("");

  const needsLinear = configs.some(c => ["FE","FD","2SLS","TWFE"].includes(c.model?.type));
  const needs2SLS   = configs.some(c => c.model?.type === "2SLS");
  const installPkgs = ["statsmodels", ...(needsLinear ? ["linearmodels"] : [])];
  lines.push(`# Install required packages if needed:`);
  lines.push(`#   pip install ${installPkgs.join(" ")}`);
  lines.push("");

  lines.push("import pandas as pd");
  lines.push("import numpy as np");
  lines.push("import statsmodels.formula.api as smf");
  lines.push("import statsmodels.api as sm");
  if (needsLinear) lines.push("from linearmodels.panel import PanelOLS, FirstDifferenceOLS");
  if (needs2SLS)   lines.push("from linearmodels.iv import IV2SLS");
  lines.push("");

  lines.push(`# ── Load data ─────────────────────────────────────────────────────────────`);
  lines.push(buildPyLoadLine(pyFile, dataLoadOpts));
  lines.push("");

  if (pipeline.length) {
    lines.push(`# ── Data pipeline ─────────────────────────────────────────────────────────`);
    pipeline.forEach(step => {
      const out = isGridEditStep(step) ? transpileStep(step, opts.allDatasets ?? {}) : toPython(step, "df");
      if (Array.isArray(out)) out.forEach(l => lines.push(l));
      else if (out) lines.push(out);
    });
    lines.push("");
  }

  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push(`# ── Variable definitions ─────────────────────────────────────────────────`);
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => lines.push(`# ${k}: ${String(v).replace(/\n/g, " ")}`));
    lines.push("");
  }

  const pattern = detectMapPatternPy(configs);

  if (pattern === "map") {
    // ── Same spec, different subsets → dict + for loop ───────────────────────
    lines.push(`# ── Subsets ─────────────────────────────────────────────────────────────────`);
    lines.push(`subsets = {`);
    configs.forEach((c, i) => {
      const expr = subsetFiltersToPython(c.subsetFilters, "df");
      const rhs  = expr ?? "df";
      const comma = i < configs.length - 1 ? "," : "";
      lines.push(`    "${c.subsetName ?? c.label}": ${rhs}${comma}`);
    });
    lines.push(`}`);
    lines.push(``);

    // Build the model call from first config, replacing "df" with "s"
    const { type = "OLS", yVar = "y", xVars = [], wVars = [], zVars = [],
            entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel,
            treatedUnit, treatTime, feCols, cohortCol, periodCol, controlMode, refPeriod,
            interactionTerms: ix0 = [], xVarsRaw: xr0 = null, wVarsRaw: wr0 = null,
            seType: se0 = "classical", clusterVar: cl0 = null, clusterVar2: cl20 = null, noIntercept: ni0 = false } = configs[0].model ?? {};
    const allX0 = [...xVars, ...wVars];
    const singleLines = transpileModel({ type, yVar, allX: allX0, xVars, wVars, zVars,
      entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, treatedUnit, treatTime,
      feCols: feCols ?? null, cohortCol: cohortCol ?? null, periodCol: periodCol ?? null, controlMode: controlMode ?? null, refPeriod: refPeriod ?? null,
      interactionTerms: ix0, xVarsRaw: xr0, wVarsRaw: wr0, seType: se0, clusterVar: cl0, clusterVar2: cl20, noIntercept: ni0 });
    // Strip assignment prefix, swap df → s
    const fitCall = singleLines
      .map(l => l.replace(/\bmodel\b\s*=\s*/, "").replace(/\bdf\b/g, "s"))
      .join("; ");

    lines.push(`# ── Estimation ─────────────────────────────────────────────────────────────`);
    lines.push(`results = {}`);
    lines.push(`for name, s in subsets.items():`);
    lines.push(`    results[name] = ${fitCall}`);
    lines.push(``);

    lines.push(`# ── Results ─────────────────────────────────────────────────────────────────`);
    lines.push(`from statsmodels.iolib.summary2 import summary_col`);
    lines.push(`table = summary_col(list(results.values()), model_names=list(results.keys()), stars=True, float_format="%.4f")`);
    lines.push(`print(table)`);
    lines.push(``);
  } else {
    // ── Different specs → one model object per config ────────────────────────
    lines.push(`# ── Estimation ─────────────────────────────────────────────────────────────`);
    const fitNames = [];
    configs.forEach((c, i) => {
      const { type = "OLS", yVar = "y", xVars = [], wVars = [], zVars = [],
              entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel,
              treatedUnit, treatTime, feCols, cohortCol, periodCol, controlMode, refPeriod,
              interactionTerms: ixc = [], xVarsRaw: xrc = null, wVarsRaw: wrc = null,
              seType: seC = "classical", clusterVar: clC = null, clusterVar2: cl2C = null, noIntercept: niC = false } = c.model ?? {};
      const allX = [...xVars, ...wVars];
      const fitName = `model_${i + 1}`;
      fitNames.push(fitName);
      lines.push(`# Model ${i+1}: ${c.label ?? type}`);
      const modelLines = transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, treatedUnit, treatTime, feCols: feCols ?? null, cohortCol: cohortCol ?? null, periodCol: periodCol ?? null, controlMode: controlMode ?? null, refPeriod: refPeriod ?? null, interactionTerms: ixc, xVarsRaw: xrc, wVarsRaw: wrc, seType: seC, clusterVar: clC, clusterVar2: cl2C, noIntercept: niC });
      modelLines.forEach(l => lines.push(l.replace(/\bmodel\b/g, fitName)));
      lines.push("");
    });

    const ivTypes = new Set(["2SLS", "FE", "FD", "TWFE", "LSDV", "EventStudy"]);
    const smFits  = [];
    const lmFits  = [];
    configs.forEach((c, i) => {
      if (ivTypes.has(c.model?.type)) lmFits.push({ name: fitNames[i], label: c.label ?? `Model ${i+1}` });
      else                             smFits.push({ name: fitNames[i], label: c.label ?? `Model ${i+1}` });
    });

    lines.push(`# ── Results ─────────────────────────────────────────────────────────────────`);
    if (smFits.length && lmFits.length) {
      lines.push(`# statsmodels models`);
      lines.push(`from statsmodels.iolib.summary2 import summary_col`);
      const smList   = smFits.map(f => f.name).join(", ");
      const smLabels = smFits.map(f => `"${f.label}"`).join(", ");
      lines.push(`print(summary_col([${smList}], model_names=[${smLabels}], stars=True, float_format="%.4f"))`);
      lines.push(`# linearmodels models`);
      lines.push(`from linearmodels.iv.model import compare as lm_compare`);
      const lmDict = lmFits.map(f => `"${f.label}": ${f.name}`).join(", ");
      lines.push(`print(lm_compare({${lmDict}}))`);
    } else if (smFits.length) {
      lines.push(`from statsmodels.iolib.summary2 import summary_col`);
      const fitList   = smFits.map(f => f.name).join(", ");
      const labelList = smFits.map(f => `"${f.label}"`).join(", ");
      lines.push(`table = summary_col([${fitList}], model_names=[${labelList}], stars=True, float_format="%.4f")`);
      lines.push(`print(table)`);
    } else {
      lines.push(`from linearmodels.iv.model import compare as lm_compare`);
      const lmDict = lmFits.map(f => `"${f.label}": ${f.name}`).join(", ");
      lines.push(`print(lm_compare({${lmDict}}))`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

// ─── SUBSET REPLICATION SCRIPT (H6/H10) ───────────────────────────────────────
// config: { filename, pipeline, perSubsetSteps, subsets, model, dataDictionary }
export function generateSubsetPythonScript({ filename = "dataset.csv", pipeline = [], perSubsetSteps = [], subsets = [], model = {}, dataDictionary = null, dataLoadOpts = null } = {}) {
  const ts   = new Date().toISOString().slice(0, 10);
  const stem = filename.replace(/\.[^.]+$/, "");
  const lines = [];

  function filterExpr(f) {
    const isNum = f.val !== "" && !isNaN(Number(f.val));
    const val   = isNum ? f.val : JSON.stringify(f.val);
    return `(d[${JSON.stringify(f.col)}] ${f.op} ${val})`;
  }

  // Strip output lines from model code so it can sit inside a function
  function modelBody(modelLines) {
    return modelLines.filter(l => !l.match(/^(print\(|summary\(|table =|from statsmodels)/));
  }

  lines.push(`# ${"─".repeat(72)}`);
  lines.push(`# Multi-subset replication script — generated by Litux`);
  lines.push(`# Dataset: ${filename}  |  Model: ${model.type ?? "OLS"}  |  ${ts}`);
  lines.push(`# ${"─".repeat(72)}`);
  lines.push("");

  lines.push("import pandas as pd");
  lines.push("import numpy as np");
  lines.push("import statsmodels.formula.api as smf");
  lines.push("import statsmodels.api as sm");
  if (["FE","FD","2SLS","TWFE"].includes(model.type)) {
    lines.push("from linearmodels.panel import PanelOLS, FirstDifferenceOLS");
    lines.push("from linearmodels.iv import IV2SLS");
  }
  lines.push("from statsmodels.iolib.summary2 import summary_col");
  lines.push("");

  lines.push(`# ── Load data ─────────────────────────────────────────────────────────────`);
  lines.push(buildPyLoadLine(filename, dataLoadOpts));
  lines.push("");

  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push(`# ── Variable definitions ─────────────────────────────────────────────────`);
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => lines.push(`# ${k}: ${String(v).replace(/\n/g, " ")}`));
    lines.push("");
  }

  if (pipeline.length) {
    lines.push(`# ── Shared pipeline ──────────────────────────────────────────────────────`);
    pipeline.forEach(step => { const c = transpileStep(step); if (c) lines.push(c); });
    lines.push("");
  }

  lines.push(`# ── Define subsets ───────────────────────────────────────────────────────`);
  lines.push(`subsets = {`);
  lines.push(`    "Full sample": lambda d: d,`);
  subsets.forEach((s, i) => {
    const cond = s.filters?.length ? s.filters.map(filterExpr).join(" & ") : null;
    const fn   = cond ? `lambda d: d[${cond}]` : `lambda d: d`;
    lines.push(`    ${JSON.stringify(s.name)}: ${fn}${i < subsets.length - 1 ? "," : ""}`);
  });
  lines.push(`}`);
  lines.push("");

  if (perSubsetSteps.length) {
    lines.push(`# ── Per-subset prep ──────────────────────────────────────────────────────`);
    lines.push(`def prep(d):`);
    perSubsetSteps.forEach(step => {
      const c = transpileStep(step);
      if (c) lines.push(`    ${c.replace(/\bdf\b/g, "d").replace(/\n/g, "\n    ")}`);
    });
    lines.push(`    return d`);
    lines.push("");
  }

  const { type = "OLS", yVar = "y", xVars = [], wVars = [], zVars = [],
          entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel,
          treatedUnit, treatTime, feCols, cohortCol, periodCol, controlMode, refPeriod,
          interactionTerms: ixs = [], xVarsRaw: xrs = null, wVarsRaw: wrs = null,
          seType: seS = "classical", clusterVar: clS = null, clusterVar2: cl2S = null, noIntercept: niS = false } = model;
  const allX = [...(xVars ?? []), ...(wVars ?? [])];
  const rawModelLines = transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, treatedUnit, treatTime, feCols: feCols ?? null, cohortCol: cohortCol ?? null, periodCol: periodCol ?? null, controlMode: controlMode ?? null, refPeriod: refPeriod ?? null, interactionTerms: ixs, xVarsRaw: xrs, wVarsRaw: wrs, seType: seS, clusterVar: clS, clusterVar2: cl2S, noIntercept: niS });

  lines.push(`# ── Model function ───────────────────────────────────────────────────────`);
  lines.push(`def run_model(d):`);
  if (perSubsetSteps.length) lines.push(`    d = prep(d)`);
  modelBody(rawModelLines).forEach(l => lines.push(`    ${l.replace(/\bdf\b/g, "d")}`));
  lines.push(`    return model`);
  lines.push("");

  lines.push(`# ── Run on all subsets ───────────────────────────────────────────────────`);
  lines.push(`results = {name: run_model(fn(df)) for name, fn in subsets.items()}`);
  lines.push("");

  lines.push(`# ── Comparison table ─────────────────────────────────────────────────────`);
  lines.push(`table = summary_col(list(results.values()), model_names=list(results.keys()), stars=True, float_format="%.4f")`);
  lines.push(`print(table)`);
  lines.push("");

  return lines.join("\n");
}
