// ─── LITUX · services/export/pythonScript.js ───────────────────────────
// Generates a self-contained Python replication script using pandas,
// statsmodels, and linearmodels.
//
// Config shape (same as rScript.js):
//   { filename, pipeline, model, auditTrail, dataDictionary }
//
// model shape:
//   { type, yVar, xVars, wVars, zVars, entityCol, timeCol,
//     postVar, treatVar, runningVar, cutoff, bandwidth, kernel }

import { toPython, jsExprToPython } from "../../pipeline/stepTranslators.js";

export function generatePythonScript(config = {}) {
  const {
    filename     = "dataset.csv",
    pipeline     = [],
    model        = {},
    dataDictionary = null,
  } = config;

  const {
    type        = "OLS",
    yVar        = "y",
    xVars       = [],
    wVars       = [],
    zVars       = [],
    entityCol   = null,
    timeCol     = null,
    postVar     = null,
    treatVar    = null,
    runningVar    = null,
    cutoff        = null,
    bandwidth     = null,
    kernel        = "triangular",
    distCol       = null,
    treatmentCol  = null,
  } = model;

  const stem    = filename.replace(/\.[^.]+$/, "");
  const pyFile  = filename.replace(/\\/g, "/");   // forward slashes — safe in Python strings
  const allX = [...(xVars ?? []), ...(wVars ?? [])];
  const pkgs = buildPackageList(type, pipeline);

  const lines = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`# ${"─".repeat(72)}`);
  lines.push(`# Replication script — ${stem}`);
  lines.push(`# Generated by Litux · ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`# Estimator: ${type}`);
  lines.push(`# ${"─".repeat(72)}`);
  lines.push("");

  // ── Install hint ─────────────────────────────────────────────────────────────
  const installPkgs = [];
  if (pkgs.has("statsmodels"))  installPkgs.push("statsmodels");
  if (pkgs.has("linearmodels")) installPkgs.push("linearmodels");
  if (pkgs.has("scipy"))        installPkgs.push("scipy");
  if (installPkgs.length) {
    lines.push(`# Install required packages if needed:`);
    lines.push(`#   pip install ${installPkgs.join(" ")}`);
    lines.push("");
  }

  // ── Imports ─────────────────────────────────────────────────────────────────
  lines.push("import pandas as pd");
  lines.push("import numpy as np");
  if (pkgs.has("statsmodels")) {
    lines.push("import statsmodels.formula.api as smf");
    lines.push("import statsmodels.api as sm");
  }
  if (pkgs.has("linearmodels")) {
    lines.push("from linearmodels.panel import PanelOLS, FirstDifferenceOLS, BetweenOLS");
    lines.push("from linearmodels.iv import IV2SLS");
  }
  if (pkgs.has("scipy")) {
    lines.push("from scipy import stats");
  }
  lines.push("");

  // ── Load data ───────────────────────────────────────────────────────────────
  lines.push("# ── Load data ─────────────────────────────────────────────────────────────");
  lines.push(`df = pd.read_csv("${pyFile}")`);
  lines.push("");

  // ── Data dictionary ─────────────────────────────────────────────────────────
  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push("# ── Variable definitions ──────────────────────────────────────────────────");
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => {
      lines.push(`# ${k}: ${String(v).replace(/\n/g, " ")}`);
    });
    lines.push("");
  }

  // ── Pipeline steps ──────────────────────────────────────────────────────────
  if (pipeline.length) {
    lines.push("# ── Data pipeline ─────────────────────────────────────────────────────────");
    pipeline.forEach(step => {
      const code = transpileStep(step);
      if (code) lines.push(code);
    });
    lines.push("");
  }

  // ── Model ───────────────────────────────────────────────────────────────────
  lines.push("# ── Estimation ─────────────────────────────────────────────────────────────");
  lines.push(...transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, factorVars: model.factorVars ?? [] }));
  lines.push("");

  return lines.join("\n");
}

// ─── PACKAGE LIST ─────────────────────────────────────────────────────────────
function buildPackageList(modelType, pipeline = []) {
  const pkgs = new Set(["statsmodels"]);
  if (["FE","FD","2SLS","TWFE","GMM","LIML"].includes(modelType)) pkgs.add("linearmodels");
  if (modelType === "RDD" || modelType === "SpatialRDD") pkgs.add("scipy");
  return pkgs;
}

// ─── STEP TRANSPILER ─────────────────────────────────────────────────────────
function transpileStep(step) {
  const { type, params = {} } = step;
  switch (type) {
    case "rename":
      return `df = df.rename(columns={"${params.from}": "${params.to}"})`;
    case "drop":
      return `df = df.drop(columns=${JSON.stringify(params.cols ?? [])}, errors="ignore")`;
    case "filter": {
      const { col, op, val } = params;
      const ops = { ">": ">", "<": "<", ">=": ">=", "<=": "<=", "==": "==", "!=": "!=" };
      const pyOp = ops[op] ?? "==";
      const v = typeof val === "string" ? `"${val}"` : val;
      return `df = df[df["${col}"] ${pyOp} ${v}]`;
    }
    case "drop_na":
      if (params.cols?.length) return `df = df.dropna(subset=${JSON.stringify(params.cols)})`;
      return `df = df.dropna()`;
    case "fill_na": {
      const col = params.col, mode = params.mode, val = params.value;
      if (mode === "mean")   return `df["${col}"] = df["${col}"].fillna(df["${col}"].mean())`;
      if (mode === "median") return `df["${col}"] = df["${col}"].fillna(df["${col}"].median())`;
      if (mode === "mode")   return `df["${col}"] = df["${col}"].fillna(df["${col}"].mode()[0])`;
      if (mode === "ffill")  return `df["${col}"] = df["${col}"].ffill()`;
      if (mode === "bfill")  return `df["${col}"] = df["${col}"].bfill()`;
      const v = typeof val === "string" ? `"${val}"` : val ?? 0;
      return `df["${col}"] = df["${col}"].fillna(${v})`;
    }
    case "fill_na_grouped": {
      const { col, groupCol, mode } = params;
      if (mode === "mean")   return `df["${col}"] = df.groupby("${groupCol}")["${col}"].transform(lambda x: x.fillna(x.mean()))`;
      if (mode === "median") return `df["${col}"] = df.groupby("${groupCol}")["${col}"].transform(lambda x: x.fillna(x.median()))`;
      return `df["${col}"] = df.groupby("${groupCol}")["${col}"].transform(lambda x: x.fillna(x.mode()[0] if len(x.mode()) > 0 else np.nan))`;
    }
    case "type_cast": {
      const t = params.targetType;
      if (t === "numeric") return `df["${params.col}"] = pd.to_numeric(df["${params.col}"], errors="coerce")`;
      if (t === "string")  return `df["${params.col}"] = df["${params.col}"].astype(str)`;
      if (t === "boolean") return `df["${params.col}"] = df["${params.col}"].astype(bool)`;
      return `df["${params.col}"] = df["${params.col}"].astype("${t}")`;
    }
    case "log":
      return `df["log_${params.col}"] = np.log(df["${params.col}"].clip(lower=1e-10))`;
    case "sq":
      return `df["${params.col}_sq"] = df["${params.col}"] ** 2`;
    case "std":
      return `df["${params.col}_z"] = (df["${params.col}"] - df["${params.col}"].mean()) / df["${params.col}"].std()`;
    case "winz": {
      const { col, p1, p99 } = params;
      return `df["${col}"] = df["${col}"].clip(lower=${p1 ?? "df[\"" + col + "\"].quantile(0.01)"}, upper=${p99 ?? "df[\"" + col + "\"].quantile(0.99)"})`;
    }
    case "dummy":
      return `df = pd.get_dummies(df, columns=["${params.col}"], prefix="${params.col}", drop_first=True, dtype=int)`;
    case "lag":
      if (params.entityCol) {
        return `df["${params.col}_lag${params.n ?? 1}"] = df.groupby("${params.entityCol}")["${params.col}"].shift(${params.n ?? 1})`;
      }
      return `df["${params.col}_lag${params.n ?? 1}"] = df["${params.col}"].shift(${params.n ?? 1})`;
    case "lead":
      if (params.entityCol) {
        return `df["${params.col}_lead${params.n ?? 1}"] = df.groupby("${params.entityCol}")["${params.col}"].shift(-${params.n ?? 1})`;
      }
      return `df["${params.col}_lead${params.n ?? 1}"] = df["${params.col}"].shift(-${params.n ?? 1})`;
    case "diff":
      if (params.entityCol) {
        return `df["${params.col}_d"] = df.groupby("${params.entityCol}")["${params.col}"].diff()`;
      }
      return `df["${params.col}_d"] = df["${params.col}"].diff()`;
    case "ix":
      return `df["${params.col1}_x_${params.col2}"] = df["${params.col1}"] * df["${params.col2}"]`;
    case "did":
      return `df["did"] = df["${params.postVar}"] * df["${params.treatVar}"]`;
    case "mutate": {
      const nn     = step.nn ?? params.newCol ?? "newcol";
      const pyExpr = jsExprToPython(step.expr ?? params.expr, "df");
      if (pyExpr) return `df["${nn}"] = ${pyExpr}`;
      return [
        `# mutate: ${nn} = ${step.expr ?? params.expr}`,
        `# NOTE: expression uses JS syntax — translate to Python manually`,
        `# df["${nn}"] = <pandas expression>`,
      ].join("\n");
    }
    case "arrange":
      return `df = df.sort_values("${params.col}", ascending=${params.asc !== false ? "True" : "False"})`;
    case "group_summarize": {
      const { groupCol, agg } = params;
      const aggMap = JSON.stringify(agg ?? {}).replace(/"/g, "'");
      return `df = df.groupby("${groupCol}").agg(${aggMap}).reset_index()`;
    }
    case "pivot_longer": {
      const { idCols, valueName, variableName } = params;
      const valueCols = params.valueCols ?? [];
      return `df = df.melt(id_vars=${JSON.stringify(idCols ?? [])}, value_vars=${JSON.stringify(valueCols)}, var_name="${variableName ?? "variable"}", value_name="${valueName ?? "value"}")`;
    }
    case "date_parse":
      return `df["${params.col}"] = pd.to_datetime(df["${params.col}"], errors="coerce")`;
    case "date_extract":
      return `df["${params.newCol}"] = df["${params.col}"].dt.${params.part ?? "year"}`;
    case "recode": {
      const mapStr = JSON.stringify(params.map ?? {});
      return `df["${params.col}"] = df["${params.col}"].map(${mapStr}).fillna(df["${params.col}"])`;
    }
    case "trim_outliers":
    case "flag_outliers": {
      const { col } = params;
      const out = type === "flag_outliers" ? `df["${col}_outlier"] = ((df["${col}"] < q1 - 1.5 * iqr) | (df["${col}"] > q3 + 1.5 * iqr)).astype(int)` : `df = df[(df["${col}"] >= q1 - 1.5 * iqr) & (df["${col}"] <= q3 + 1.5 * iqr)]`;
      return [
        `_q1, _q3 = df["${col}"].quantile([0.25, 0.75])`,
        `_iqr = _q3 - _q1`,
        out,
      ].join("\n");
    }
    case "quickclean":
      return `df = df.dropna(how="all").drop_duplicates()`;
    case "normalize_cats":
      if (params.col) return `df["${params.col}"] = df["${params.col}"].str.strip().str.lower()`;
      return `# normalize_cats: manual step`;
    case "extract_regex":
      return `df["${params.newCol}"] = df["${params.col}"].str.extract(r"${params.regex}")`;
    case "join": {
      const how     = step.how === "inner" ? "inner" : "left";
      const lk      = step.leftKey  ?? "id";
      const rk      = step.rightKey ?? lk;
      const sfx     = step.suffix   ?? "_r";
      const rightId = step.rightId  ?? "right_dataset";
      const byExpr  = lk === rk
        ? `on="${lk}"`
        : `left_on="${lk}", right_on="${rk}"`;
      return [
        `# Join: load right dataset and merge on ${lk}`,
        `df_right = pd.read_csv("<path_to_${rightId}.csv>")`,
        `df = df.merge(df_right, ${byExpr}, how="${how}", suffixes=("", "${sfx}"))`,
      ].join("\n");
    }
    case "append": {
      const rightId = step.rightId ?? "right_dataset";
      return [
        `# Append: stack right dataset below current`,
        `df_right = pd.read_csv("<path_to_${rightId}.csv>")`,
        `df = pd.concat([df, df_right], ignore_index=True)`,
      ].join("\n");
    }
    case "ai_tr": {
      const col    = step.col ?? "col";
      const jsCode = step.js  ?? "";
      const arrowMatch = jsCode.match(/^\s*\(?\s*(\w+)\s*\)?\s*=>\s*([\s\S]+)$/);
      if (arrowMatch) {
        const [, param, body] = arrowMatch;
        const colRef = `df["${col}"]`;
        const substituted = body.trim().replace(new RegExp(`\\b${param}\\b`, "g"), colRef);
        const pyExpr = jsExprToPython(substituted, "df");
        if (pyExpr) return `df["${col}"] = ${pyExpr}`;
      }
      return [
        `# AI transform on "${col}"`,
        `# JS: ${jsCode}`,
        `# df["${col}"] = <Python expression>`,
      ].join("\n");
    }
    case "factor_interactions": {
      const { cols } = params;
      if (cols?.length >= 2) return `df["${cols.join("_x_")}"] = df["${cols[0]}"] * df["${cols[1]}"]`;
      return `# factor_interactions`;
    }
    case "patch": {
      const col = step.col ?? "column";
      const val = typeof step.value === "string" ? `"${step.value}"` : (step.value ?? "None");
      if (step.rowId) {
        return `df.loc[df["__row_id"] == "${step.rowId}", "${col}"] = ${val}`;
      }
      return `df.loc[df["__ri"] == ${step.ri}, "${col}"] = ${val}  # __ri-based: may misalign after sort`;
    }

    case "geocode": {
      const addrCol = step.addressCol ?? "address";
      const latCol  = step.latCol  ?? "lat";
      const lonCol  = step.lonCol  ?? "lon";
      return [
        `# Geocode: ${addrCol} → ${latCol} / ${lonCol}`,
        `# pip install geopy`,
        `from geopy.geocoders import Nominatim`,
        `from geopy.extra.rate_limiter import RateLimiter`,
        `_geolocator = Nominatim(user_agent="econsolver_replication")`,
        `_geocode    = RateLimiter(_geolocator.geocode, min_delay_seconds=1)`,
        `def _get_coords(address):`,
        `    loc = _geocode(str(address))`,
        `    return (loc.latitude, loc.longitude) if loc else (None, None)`,
        `df[["${latCol}", "${lonCol}"]] = df["${addrCol}"].apply(`,
        `    lambda a: pd.Series(_get_coords(a))`,
        `)`,
      ].join("\n");
    }

    default:
      return `# [${type}] — not yet transpiled`;
  }
}

// ─── MODEL TRANSPILER ─────────────────────────────────────────────────────────
function transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, factorVars = [], treatedUnit, treatTime }) {
  const lines = [];
  const fvSet    = new Set(factorVars);
  const fmtPy    = v => fvSet.has(v) ? `C(${v})` : v;
  const xFormula = allX.map(v => `"${v}"`).join(", ");

  switch (type) {
    case "OLS": {
      const formula = `"${yVar} ~ ${allX.map(fmtPy).join(" + ")}"`;
      lines.push(`model = smf.ols(${formula}, data=df).fit(cov_type="HC3")`);
      lines.push(`print(model.summary())`);
      break;
    }

    case "FE": {
      lines.push(`# Fixed Effects (within estimator)`);
      lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
      lines.push(`exog = sm.add_constant(df_panel[[${xFormula}]])`);
      lines.push(`model = PanelOLS(df_panel["${yVar}"], exog, entity_effects=True).fit(cov_type="clustered", cluster_entity=True)`);
      lines.push(`print(model.summary)`);
      break;
    }

    case "FD": {
      lines.push(`# First Differences estimator`);
      lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
      lines.push(`exog = sm.add_constant(df_panel[[${xFormula}]])`);
      lines.push(`model = FirstDifferenceOLS(df_panel["${yVar}"], exog).fit(cov_type="clustered", cluster_entity=True)`);
      lines.push(`print(model.summary)`);
      break;
    }

    case "2SLS": {
      const endog = xVars.map(v => `"${v}"`).join(", ");
      const instr = zVars.map(v => `"${v}"`).join(", ");
      const exogX = wVars.map(v => `"${v}"`).join(", ");
      lines.push(`# Two-Stage Least Squares (IV)`);
      if (entityCol && timeCol) {
        // Panel IV
        lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
        lines.push(`dependent  = df_panel["${yVar}"]`);
        lines.push(exogX ? `exog_vars  = sm.add_constant(df_panel[[${exogX}]])` : `exog_vars  = None`);
        lines.push(`endog_vars = df_panel[[${endog}]]`);
        lines.push(`instr_vars = df_panel[[${instr}]]`);
      } else {
        // Cross-sectional IV
        lines.push(`dependent  = df["${yVar}"]`);
        lines.push(exogX ? `exog_vars  = sm.add_constant(df[[${exogX}]])` : `exog_vars  = None`);
        lines.push(`endog_vars = df[[${endog}]]`);
        lines.push(`instr_vars = df[[${instr}]]`);
      }
      lines.push(`model = IV2SLS(dependent, exog_vars, endog_vars, instr_vars).fit(cov_type="robust")`);
      lines.push(`print(model.summary)`);
      break;
    }

    case "DiD": {
      const xExtra = wVars.length ? ` + ${wVars.join(" + ")}` : "";
      lines.push(`# Difference-in-Differences (2×2)`);
      lines.push(`df["did"] = df["${postVar}"] * df["${treatVar}"]`);
      lines.push(`model = smf.ols("${yVar} ~ ${postVar} + ${treatVar} + did${xExtra}", data=df).fit(cov_type="HC3")`);
      lines.push(`print(model.summary())`);
      lines.push(`print(f"ATT = {model.params['did']:.4f}  SE = {model.bse['did']:.4f}  p = {model.pvalues['did']:.4f}")`);
      break;
    }

    case "TWFE": {
      lines.push(`# Two-Way Fixed Effects DiD`);
      lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
      const extraX = wVars.length ? `, ${wVars.map(v=>`"${v}"`).join(", ")}` : "";
      lines.push(`exog = sm.add_constant(df_panel[["${treatVar}"${extraX}]])`);
      lines.push(`model = PanelOLS(df_panel["${yVar}"], exog, entity_effects=True, time_effects=True).fit(cov_type="clustered", cluster_entity=True)`);
      lines.push(`print(model.summary)`);
      break;
    }

    case "RDD": {
      const kernelStr = kernel === "epanechnikov" ? "epanechnikov" : kernel === "uniform" ? "uniform" : "triangular";
      const extraCols = wVars.length ? ` + ${wVars.join(" + ")}` : "";
      const h_py = bandwidth ? Number(bandwidth).toFixed(6) : "None  # replace with numeric bandwidth";
      lines.push(`# Sharp Regression Discontinuity Design`);
      lines.push(`cutoff = ${cutoff ?? 0}`);
      lines.push(`bw     = ${h_py}`);
      lines.push(`# ── Preferred: rdrobust package ──────────────────────────────────────`);
      lines.push(`# pip install rdrobust`);
      lines.push(`try:`);
      lines.push(`    from rdrobust import rdrobust`);
      lines.push(`    rdd = rdrobust(y=df["${yVar}"].values, x=df["${runningVar}"].values, c=cutoff${bandwidth ? `, h=bw` : ""}${kernelStr !== "triangular" ? `, kernel="${kernelStr}"` : ""}${wVars.length ? `, covs=df[${JSON.stringify(wVars)}].values` : ""})`);
      lines.push(`    print(rdd.summary())`);
      lines.push(`    print(f"LATE = {rdd.coef[0]:.4f}  SE = {rdd.se[3]:.4f}  p = {rdd.pv[3]:.4f}")`);
      lines.push(`except ImportError:`);
      lines.push(`    # ── Fallback: manual local-linear WLS ────────────────────────────`);
      lines.push(`    df_rdd = df[(df["${runningVar}"] >= cutoff - bw) & (df["${runningVar}"] <= cutoff + bw)].copy()`);
      lines.push(`    df_rdd["above"] = (df_rdd["${runningVar}"] >= cutoff).astype(int)`);
      lines.push(`    df_rdd["run_c"] = df_rdd["${runningVar}"] - cutoff`);
      if (kernelStr === "triangular") {
        lines.push(`    df_rdd["_w"] = np.maximum(0, 1 - np.abs(df_rdd["run_c"]) / bw)`);
      } else if (kernelStr === "epanechnikov") {
        lines.push(`    df_rdd["_w"] = np.where(np.abs(df_rdd["run_c"] / bw) <= 1, 0.75 * (1 - (df_rdd["run_c"]/bw)**2), 0)`);
      } else {
        lines.push(`    df_rdd["_w"] = 1.0`);
      }
      lines.push(`    model = smf.wls("${yVar} ~ above + run_c + above:run_c${extraCols}", data=df_rdd, weights=df_rdd["_w"]).fit(cov_type="HC3")`);
      lines.push(`    print(model.summary())`);
      lines.push(`    print(f"LATE = {model.params['above']:.4f}  SE = {model.bse['above']:.4f}  p = {model.pvalues['above']:.4f}")`);
      break;
    }

    case "Logit":
    case "Probit": {
      const formula = `"${yVar} ~ ${allX.map(fmtPy).join(" + ")}"`;
      const fn = type === "Logit" ? "logit" : "probit";
      lines.push(`# ${type} regression`);
      lines.push(`model = smf.${fn}(${formula}, data=df).fit()`);
      lines.push(`print(model.summary())`);
      lines.push(`# Marginal effects at the mean`);
      lines.push(`print(model.get_margeff().summary())`);
      break;
    }

    case "LSDV": {
      lines.push(`# Panel LSDV (numerically equivalent to within/FE)`);
      lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
      lines.push(`exog = sm.add_constant(df_panel[[${xFormula}]])`);
      lines.push(`model = PanelOLS(df_panel["${yVar}"], exog, entity_effects=True${timeCol ? ", time_effects=True" : ""}).fit(cov_type="clustered", cluster_entity=True)`);
      lines.push(`print(model.summary)`);
      lines.push(``);
      lines.push(`# Recover entity fixed effects (LSDV alpha_i)`);
      lines.push(`entity_fe = model.estimated_effects`);
      lines.push(`print("Entity fixed effects (first 20):")`);
      lines.push(`print(entity_fe.groupby(level="${entityCol}").first().head(20))`);
      break;
    }

    case "FuzzyRDD": {
      const kernelStr = kernel === "epanechnikov" ? "epanechnikov"
                      : kernel === "uniform"      ? "uniform"
                      : "triangular";
      const dVar   = treatVar ?? "D";
      const extraCols = wVars.length ? ` + ${wVars.join(" + ")}` : "";
      const h_fpy = bandwidth ? Number(bandwidth).toFixed(6) : "None  # set bandwidth";
      lines.push(`# Fuzzy RDD — LATE for compliers`);
      lines.push(`cutoff = ${cutoff ?? 0}`);
      lines.push(`bw     = ${h_fpy}`);
      lines.push(`# ── Preferred: rdrobust package ──────────────────────────────────────`);
      lines.push(`# pip install rdrobust`);
      lines.push(`try:`);
      lines.push(`    from rdrobust import rdrobust`);
      lines.push(`    rdd = rdrobust(y=df["${yVar}"].values, x=df["${runningVar}"].values,`);
      lines.push(`                   fuzzy=df["${dVar}"].values, c=cutoff${bandwidth ? `, h=bw` : ""}${kernelStr !== "triangular" ? `, kernel="${kernelStr}"` : ""}${wVars.length ? `, covs=df[${JSON.stringify(wVars)}].values` : ""})`);
      lines.push(`    print(rdd.summary())`);
      lines.push(`    print(f"LATE (Fuzzy) = {rdd.coef[0]:.4f}  SE = {rdd.se[3]:.4f}  p = {rdd.pv[3]:.4f}")`);
      lines.push(`except ImportError:`);
      lines.push(`    # ── Fallback: manual kernel-weighted 2SLS ────────────────────────`);
      lines.push(`    df_bw = df[(df["${runningVar}"] >= cutoff - bw) & (df["${runningVar}"] <= cutoff + bw)].copy()`);
      lines.push(`    df_bw["_Z"]     = (df_bw["${runningVar}"] >= cutoff).astype(int)`);
      lines.push(`    df_bw["_run_c"] = df_bw["${runningVar}"] - cutoff`);
      if (kernelStr === "triangular") {
        lines.push(`    df_bw["_w"] = np.maximum(0, 1 - np.abs(df_bw["_run_c"]) / bw)`);
      } else if (kernelStr === "epanechnikov") {
        lines.push(`    df_bw["_w"] = np.where(np.abs(df_bw["_run_c"] / bw) <= 1, 0.75 * (1 - (df_bw["_run_c"]/bw)**2), 0)`);
      } else {
        lines.push(`    df_bw["_w"] = 1.0`);
      }
      lines.push(`    # First stage: Z -> D`);
      lines.push(`    fs = smf.wls("${dVar} ~ _Z + _run_c + _Z:_run_c${extraCols}", data=df_bw, weights=df_bw["_w"]).fit(cov_type="HC3")`);
      lines.push(`    print(f"First-stage F-stat: {fs.fvalue:.2f}  (p={fs.f_pvalue:.4f})")`);
      lines.push(`    # Second stage: use D_hat as instrument`);
      lines.push(`    df_bw["_D_hat"] = fs.fittedvalues`);
      lines.push(`    ss = smf.wls("${yVar} ~ _D_hat + _run_c + _D_hat:_run_c${extraCols}", data=df_bw, weights=df_bw["_w"]).fit(cov_type="HC3")`);
      lines.push(`    print(ss.summary())`);
      lines.push(`    print(f"LATE = {ss.params['_D_hat']:.4f}  SE = {ss.bse['_D_hat']:.4f}  p = {ss.pvalues['_D_hat']:.4f}")`);
      break;
    }

    case "SpatialRDD": {
      const kernelStr = kernel === "epanechnikov" ? "epanechnikov"
                      : kernel === "uniform"      ? "uniform"
                      : "triangular";
      const distV  = distCol      ?? runningVar ?? "dist";
      const trtV   = treatmentCol ?? treatVar   ?? "treatment";
      const h      = bandwidth ? Number(bandwidth).toFixed(6) : null;
      const extraCols = wVars.length ? ` + ${wVars.join(" + ")}` : "";
      lines.push(`# Spatial RD (Keele & Titiunik 2015)`);
      lines.push(`# Build signed running variable: positive = treated side, cutoff = 0`);
      lines.push(`df["_signed_dist"] = (2 * df["${trtV}"] - 1) * df["${distV}"].abs()`);
      lines.push(`bw = ${h ?? "None  # replace with numeric bandwidth"}`);
      lines.push(`df_rdd = df[(df["_signed_dist"] >= -bw) & (df["_signed_dist"] <= bw)].copy()`);
      if (kernelStr === "triangular") {
        lines.push(`df_rdd["_w"] = np.maximum(0, 1 - np.abs(df_rdd["_signed_dist"]) / bw)`);
      } else if (kernelStr === "epanechnikov") {
        lines.push(`df_rdd["_w"] = np.where(np.abs(df_rdd["_signed_dist"] / bw) <= 1, 0.75 * (1 - (df_rdd["_signed_dist"] / bw)**2), 0)`);
      } else {
        lines.push(`df_rdd["_w"] = 1.0`);
      }
      lines.push(`df_rdd["_above"] = (df_rdd["_signed_dist"] >= 0).astype(int)`);
      lines.push(`model = smf.wls("${yVar} ~ _above + _signed_dist + _above:_signed_dist${extraCols}", data=df_rdd, weights=df_rdd["_w"]).fit(cov_type="HC3")`);
      lines.push(`print(model.summary())`);
      lines.push(`print(f"LATE at boundary = {model.params['_above']:.4f}  SE = {model.bse['_above']:.4f}  p = {model.pvalues['_above']:.4f}")`);
      break;
    }

    case "EventStudy": {
      const extraCols = wVars.map(v => `"${v}"`).join(", ");
      lines.push(`# Event Study — relative-time dummies`);
      lines.push(`# Replace 'treat_time' with the column holding each unit's treatment period`);
      lines.push(`df["rel_time"] = df["${timeCol}"] - df["treat_time"]`);
      lines.push(`df["rel_time"] = df["rel_time"].clip(-5, 5)  # truncate distant periods`);
      lines.push(`df_panel = df.set_index(["${entityCol}", "${timeCol}"])`);
      lines.push(`rel_dummies = pd.get_dummies(df_panel["rel_time"], prefix="rt", drop_first=False)`);
      lines.push(`rel_dummies = rel_dummies.drop(columns=["rt_-1"], errors="ignore")  # ref = -1`);
      if (wVars.length) {
        lines.push(`exog = sm.add_constant(pd.concat([rel_dummies, df_panel[[${extraCols}]]], axis=1))`);
      } else {
        lines.push(`exog = sm.add_constant(rel_dummies)`);
      }
      lines.push(`from linearmodels.panel import PanelOLS`);
      lines.push(`model = PanelOLS(df_panel["${yVar}"], exog, entity_effects=True, time_effects=True).fit(cov_type="clustered", cluster_entity=True)`);
      lines.push(`print(model.summary)`);
      break;
    }

    case "SyntheticControl": {
      const ec = entityCol ?? "unit";
      const tc = timeCol   ?? "time";
      const tu = treatedUnit ?? "TreatedUnit";
      const tt = treatTime != null ? Number(treatTime) : "TREAT_TIME";
      const predsStr = (xVars ?? []).length
        ? `[${(xVars ?? []).map(v => `"${v}"`).join(", ")}]`
        : "[]  # no explicit predictors — outcome mean used";
      lines.push(`# ── Synthetic Control (pysynth / scipy fallback) ─────────────────────`);
      lines.push(`# Install: pip install pysynth  (or use scipy.optimize directly)`);
      lines.push(`# pysynth wraps the Frank-Wolfe algorithm used by the Synth R package`);
      lines.push(`try:`);
      lines.push(`    from pysynth import Synth`);
      lines.push(`    sc = Synth()`);
      lines.push(`    sc.fit(`);
      lines.push(`        df,`);
      lines.push(`        outcome_var="${yVar}",`);
      lines.push(`        id_var="${ec}",`);
      lines.push(`        time_var="${tc}",`);
      lines.push(`        treatment_identifier="${tu}",`);
      lines.push(`        treatment_time=${tt},`);
      lines.push(`        predictors=${predsStr},`);
      lines.push(`    )`);
      lines.push(`    sc.plot()          # path plot`);
      lines.push(`    sc.gaps_plot()     # gap plot`);
      lines.push(`    print(sc.weights)  # donor weights`);
      lines.push(`except ImportError:`);
      lines.push(`    # ── Manual Frank-Wolfe via scipy ─────────────────────────────────`);
      lines.push(`    import numpy as np`);
      lines.push(`    from scipy.optimize import minimize`);
      lines.push(`    pre = df[df["${tc}"] < ${tt}]`);
      lines.push(`    donors = df["${ec}"].unique().tolist()`);
      lines.push(`    donors = [d for d in donors if d != "${tu}"]`);
      lines.push(`    Y_treated = pre[pre["${ec}"] == "${tu}"]["${yVar}"].values`);
      lines.push(`    Y_donors  = np.column_stack([pre[pre["${ec}"] == d]["${yVar}"].values for d in donors])`);
      lines.push(`    def loss(w): return np.sum((Y_treated - Y_donors @ w) ** 2)`);
      lines.push(`    w0     = np.ones(len(donors)) / len(donors)`);
      lines.push(`    cons   = {"type": "eq", "fun": lambda w: np.sum(w) - 1}`);
      lines.push(`    bounds = [(0, 1)] * len(donors)`);
      lines.push(`    res    = minimize(loss, w0, method="SLSQP", bounds=bounds, constraints=cons)`);
      lines.push(`    weights = dict(zip(donors, res.x))`);
      lines.push(`    print("Donor weights:", {k: round(v, 4) for k, v in weights.items() if v > 0.001})`);
      break;
    }

    case "GMM": {
      const xList = xVars.map(v => `"${v}"`).join(", ");
      const wList = wVars.map(v => `"${v}"`).join(", ");
      const zList = [...xVars, ...zVars].map(v => `"${v}"`).join(", ");
      lines.push(`# Two-Step Efficient GMM`);
      lines.push(`from linearmodels.iv import IVGMM`);
      lines.push(`dependent  = df["${yVar}"]`);
      lines.push(`exog_vars  = sm.add_constant(df[[${xList || `"# add exog columns"`}]])` );
      lines.push(`endog_vars = df[[${wList || `"# add endogenous columns"`}]]`);
      lines.push(`instr_vars = df[[${zList || `"# add instrument columns"`}]]`);
      lines.push(`model = IVGMM(dependent, exog_vars, endog_vars, instr_vars).fit(cov_type="robust")`);
      lines.push(`print(model.summary)`);
      lines.push(`# J-statistic (over-identification test)`);
      lines.push(`print(f"J-stat: {model.j_stat.stat:.4f}  p={model.j_stat.pval:.4f}")`);
      break;
    }

    case "LIML": {
      const xList = xVars.map(v => `"${v}"`).join(", ");
      const wList = wVars.map(v => `"${v}"`).join(", ");
      const zList = [...xVars, ...zVars].map(v => `"${v}"`).join(", ");
      lines.push(`# Limited Information Maximum Likelihood (LIML)`);
      lines.push(`from linearmodels.iv import IVLIML`);
      lines.push(`dependent  = df["${yVar}"]`);
      lines.push(`exog_vars  = sm.add_constant(df[[${xList || `"# add exog columns"`}]])`);
      lines.push(`endog_vars = df[[${wList || `"# add endogenous columns"`}]]`);
      lines.push(`instr_vars = df[[${zList || `"# add instrument columns"`}]]`);
      lines.push(`model = IVLIML(dependent, exog_vars, endog_vars, instr_vars).fit(cov_type="robust")`);
      lines.push(`print(model.summary)`);
      lines.push(`# kappa: 1 = just-identified (= 2SLS); > 1 = over-identified`);
      lines.push(`print(f"kappa = {model.kappa:.6f}")`);
      break;
    }

    case "PoissonFE": {
      const ec  = entityCol ?? "entity";
      const cov = xVars.map(v => `"${v}"`).join(", ");
      lines.push(`# Poisson FE (PPML with entity fixed effects)`);
      lines.push(`# Option 1 — pyfixest (mirrors R's fixest)`);
      lines.push(`# pip install pyfixest`);
      lines.push(`try:`);
      lines.push(`    import pyfixest as pf`);
      lines.push(`    fit = pf.fepois("${yVar} ~ ${xVars.join(" + ") || "1"} | ${ec}", data=df, vcov={"CRV1": "${ec}"})`);
      lines.push(`    pf.etable([fit])`);
      lines.push(`    import numpy as np`);
      lines.push(`    print("IRR:", np.exp(fit.coef().values))`);
      lines.push(`except ImportError:`);
      lines.push(`    # Option 2 — statsmodels GLM with entity dummies (slow for large N)`);
      lines.push(`    import statsmodels.formula.api as smf`);
      lines.push(`    model = smf.glm("${yVar} ~ ${[...xVars, `C(${ec})`].join(" + ") || "1"}",`);
      lines.push(`        data=df, family=sm.families.Poisson()).fit(cov_type="HC3")`);
      lines.push(`    print(model.summary())`);
      lines.push(`    import numpy as np`);
      lines.push(`    print("IRR:", np.exp(model.params))`);
      break;
    }

    case "McCrary": {
      const rv = runningVar ?? "running";
      const c0 = cutoff ?? 0;
      lines.push(`# McCrary / Cattaneo-Jansson-Ma density test`);
      lines.push(`# pip install rddensity`);
      lines.push(`from rddensity import rddensity`);
      lines.push(`fit = rddensity(X=df["${rv}"], c=${c0})`);
      lines.push(`print(fit.summary())`);
      lines.push(`# Density plot`);
      lines.push(`from rddensity import rdplotdensity`);
      lines.push(`rdplotdensity(fit, df["${rv}"], xlabel="${rv}")`);
      break;
    }

    default:
      lines.push(`# Model type "${type}" — add estimation code here`);
  }

  return lines;
}

// ─── MULTI-MODEL EXPORT ────────────────────────────────────────────────────────
// configs: Array of { model: ModelConfig, label: string }
// opts:    { filename?: string, pipeline?: Step[] }
export function generateMultiModelPythonScript(configs = [], dataDictionary = null, opts = {}) {
  if (!configs.length) return "# No models provided.";

  const filename = opts.filename ?? "dataset.csv";
  const pipeline = opts.pipeline ?? [];
  const pyFile   = filename.replace(/\\/g, "/");
  const ts = new Date().toISOString().slice(0, 10);
  const lines = [];

  lines.push(`# ${"─".repeat(72)}`);
  lines.push(`# Multi-model replication script — generated by Litux`);
  lines.push(`# Models: ${configs.map((c, i) => `(${i+1}) ${c.label ?? c.model?.type}`).join(", ")}`);
  lines.push(`# Generated: ${ts}`);
  lines.push(`# ${"─".repeat(72)}`);
  lines.push("");

  const needsLinear = configs.some(c => ["FE","FD","2SLS","TWFE"].includes(c.model?.type));
  const needs2SLS   = configs.some(c => c.model?.type === "2SLS");
  const installPkgs = ["statsmodels", ...(needsLinear ? ["linearmodels"] : [])];
  lines.push(`# Install required packages if needed:`);
  lines.push(`#   pip install ${installPkgs.join(" ")}`);
  lines.push("");

  lines.push("import pandas as pd");
  lines.push("import numpy as np");
  lines.push("import statsmodels.formula.api as smf");
  lines.push("import statsmodels.api as sm");
  if (needsLinear) lines.push("from linearmodels.panel import PanelOLS, FirstDifferenceOLS");
  if (needs2SLS)   lines.push("from linearmodels.iv import IV2SLS");
  lines.push("");

  lines.push(`# ── Load data ─────────────────────────────────────────────────────────────`);
  const ext = filename.split(".").pop()?.toLowerCase();
  if (ext === "dta") lines.push(`df = pd.read_stata("${pyFile}")`);
  else if (["xlsx","xls"].includes(ext)) lines.push(`df = pd.read_excel("${pyFile}")`);
  else lines.push(`df = pd.read_csv("${pyFile}")`);
  lines.push("");

  if (pipeline.length) {
    lines.push(`# ── Data pipeline ─────────────────────────────────────────────────────────`);
    pipeline.forEach(step => {
      const out = toPython(step, "df");
      if (Array.isArray(out)) out.forEach(l => lines.push(l));
      else if (out) lines.push(out);
    });
    lines.push("");
  }

  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push(`# ── Variable definitions ─────────────────────────────────────────────────`);
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => lines.push(`# ${k}: ${String(v).replace(/\n/g, " ")}`));
    lines.push("");
  }

  lines.push(`# ── Estimation ─────────────────────────────────────────────────────────────`);
  const fitNames = [];
  configs.forEach((c, i) => {
    const { type = "OLS", yVar = "y", xVars = [], wVars = [], zVars = [],
            entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel,
            treatedUnit, treatTime } = c.model ?? {};
    const allX = [...xVars, ...wVars];
    const fitName = `model_${i + 1}`;
    fitNames.push(fitName);
    lines.push(`# Model ${i+1}: ${c.label ?? type}`);
    const modelLines = transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, treatedUnit, treatTime });
    modelLines.forEach(l => lines.push(l.replace(/\bmodel\b/g, fitName)));
    lines.push("");
  });

  // Split fit names by library: statsmodels models support summary_col;
  // linearmodels (IV2SLS, PanelOLS, etc.) use their own .summary attribute.
  const ivTypes = new Set(["2SLS", "FE", "FD", "TWFE", "LSDV", "EventStudy"]);
  const smFits  = [];   // statsmodels fit objects
  const lmFits  = [];   // linearmodels fit objects
  configs.forEach((c, i) => {
    if (ivTypes.has(c.model?.type)) lmFits.push({ name: fitNames[i], label: c.label ?? `Model ${i+1}` });
    else                             smFits.push({ name: fitNames[i], label: c.label ?? `Model ${i+1}` });
  });

  lines.push(`# ── Results ─────────────────────────────────────────────────────────────────`);
  if (smFits.length && lmFits.length) {
    // Mixed: print each group separately
    lines.push(`# statsmodels models`);
    lines.push(`from statsmodels.iolib.summary2 import summary_col`);
    const smList   = smFits.map(f => f.name).join(", ");
    const smLabels = smFits.map(f => `"${f.label}"`).join(", ");
    lines.push(`print(summary_col([${smList}], model_names=[${smLabels}], stars=True, float_format="%.4f"))`);
    lines.push(`# linearmodels models`);
    lines.push(`from linearmodels.iv.model import compare as lm_compare`);
    const lmDict = lmFits.map(f => `"${f.label}": ${f.name}`).join(", ");
    lines.push(`print(lm_compare({${lmDict}}))`);
  } else if (smFits.length) {
    lines.push(`from statsmodels.iolib.summary2 import summary_col`);
    const fitList   = smFits.map(f => f.name).join(", ");
    const labelList = smFits.map(f => `"${f.label}"`).join(", ");
    lines.push(`table = summary_col([${fitList}], model_names=[${labelList}], stars=True, float_format="%.4f")`);
    lines.push(`print(table)`);
  } else {
    lines.push(`from linearmodels.iv.model import compare as lm_compare`);
    const lmDict = lmFits.map(f => `"${f.label}": ${f.name}`).join(", ");
    lines.push(`print(lm_compare({${lmDict}}))`);
  }
  lines.push("");

  return lines.join("\n");
}

// ─── SUBSET REPLICATION SCRIPT (H6/H10) ───────────────────────────────────────
// config: { filename, pipeline, perSubsetSteps, subsets, model, dataDictionary }
export function generateSubsetPythonScript({ filename = "dataset.csv", pipeline = [], perSubsetSteps = [], subsets = [], model = {}, dataDictionary = null } = {}) {
  const ts   = new Date().toISOString().slice(0, 10);
  const stem = filename.replace(/\.[^.]+$/, "");
  const lines = [];

  function filterExpr(f) {
    const isNum = f.val !== "" && !isNaN(Number(f.val));
    const val   = isNum ? f.val : JSON.stringify(f.val);
    return `(d[${JSON.stringify(f.col)}] ${f.op} ${val})`;
  }

  // Strip output lines from model code so it can sit inside a function
  function modelBody(modelLines) {
    return modelLines.filter(l => !l.match(/^(print\(|summary\(|table =|from statsmodels)/));
  }

  lines.push(`# ${"─".repeat(72)}`);
  lines.push(`# Multi-subset replication script — generated by Litux`);
  lines.push(`# Dataset: ${filename}  |  Model: ${model.type ?? "OLS"}  |  ${ts}`);
  lines.push(`# ${"─".repeat(72)}`);
  lines.push("");

  lines.push("import pandas as pd");
  lines.push("import numpy as np");
  lines.push("import statsmodels.formula.api as smf");
  lines.push("import statsmodels.api as sm");
  if (["FE","FD","2SLS","TWFE"].includes(model.type)) {
    lines.push("from linearmodels.panel import PanelOLS, FirstDifferenceOLS");
    lines.push("from linearmodels.iv import IV2SLS");
  }
  lines.push("from statsmodels.iolib.summary2 import summary_col");
  lines.push("");

  lines.push(`# ── Load data ─────────────────────────────────────────────────────────────`);
  lines.push(`df = pd.read_csv(${JSON.stringify(filename)})`);
  lines.push("");

  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push(`# ── Variable definitions ─────────────────────────────────────────────────`);
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => lines.push(`# ${k}: ${String(v).replace(/\n/g, " ")}`));
    lines.push("");
  }

  if (pipeline.length) {
    lines.push(`# ── Shared pipeline ──────────────────────────────────────────────────────`);
    pipeline.forEach(step => { const c = transpileStep(step); if (c) lines.push(c); });
    lines.push("");
  }

  lines.push(`# ── Define subsets ───────────────────────────────────────────────────────`);
  lines.push(`subsets = {`);
  lines.push(`    "Full sample": lambda d: d,`);
  subsets.forEach((s, i) => {
    const cond = s.filters?.length ? s.filters.map(filterExpr).join(" & ") : null;
    const fn   = cond ? `lambda d: d[${cond}]` : `lambda d: d`;
    lines.push(`    ${JSON.stringify(s.name)}: ${fn}${i < subsets.length - 1 ? "," : ""}`);
  });
  lines.push(`}`);
  lines.push("");

  if (perSubsetSteps.length) {
    lines.push(`# ── Per-subset prep ──────────────────────────────────────────────────────`);
    lines.push(`def prep(d):`);
    perSubsetSteps.forEach(step => {
      const c = transpileStep(step);
      if (c) lines.push(`    ${c.replace(/\bdf\b/g, "d").replace(/\n/g, "\n    ")}`);
    });
    lines.push(`    return d`);
    lines.push("");
  }

  const { type = "OLS", yVar = "y", xVars = [], wVars = [], zVars = [],
          entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel,
          treatedUnit, treatTime } = model;
  const allX = [...(xVars ?? []), ...(wVars ?? [])];
  const rawModelLines = transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, treatedUnit, treatTime });

  lines.push(`# ── Model function ───────────────────────────────────────────────────────`);
  lines.push(`def run_model(d):`);
  if (perSubsetSteps.length) lines.push(`    d = prep(d)`);
  modelBody(rawModelLines).forEach(l => lines.push(`    ${l.replace(/\bdf\b/g, "d")}`));
  lines.push(`    return model`);
  lines.push("");

  lines.push(`# ── Run on all subsets ───────────────────────────────────────────────────`);
  lines.push(`results = {name: run_model(fn(df)) for name, fn in subsets.items()}`);
  lines.push("");

  lines.push(`# ── Comparison table ─────────────────────────────────────────────────────`);
  lines.push(`table = summary_col(list(results.values()), model_names=list(results.keys()), stars=True, float_format="%.4f")`);
  lines.push(`print(table)`);
  lines.push("");

  return lines.join("\n");
}
