// ─── ECON STUDIO · services/export/stataScript.js ────────────────────────────
// Generates a self-contained Stata .do replication file.
//
// Config shape (same as rScript.js / pythonScript.js):
//   { filename, pipeline, model, auditTrail, dataDictionary }
//
// model shape:
//   { type, yVar, xVars, wVars, zVars, entityCol, timeCol,
//     postVar, treatVar, runningVar, cutoff, bandwidth, kernel }

export function generateStataScript(config = {}) {
  const {
    filename       = "dataset.csv",
    pipeline       = [],
    model          = {},
    dataDictionary = null,
  } = config;

  const {
    type       = "OLS",
    yVar       = "y",
    xVars      = [],
    wVars      = [],
    zVars      = [],
    entityCol  = null,
    timeCol    = null,
    postVar    = null,
    treatVar   = null,
    runningVar = null,
    cutoff     = null,
    bandwidth  = null,
    kernel     = "triangular",
  } = model;

  const stem = filename.replace(/\.[^.]+$/, "");
  const allX = [...(xVars ?? []), ...(wVars ?? [])];

  const lines = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`* ${"─".repeat(71)}`);
  lines.push(`* Replication do-file — ${stem}`);
  lines.push(`* Generated by Econ Studio · ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`* Estimator: ${type}`);
  lines.push(`* ${"─".repeat(71)}`);
  lines.push("");
  lines.push("clear all");
  lines.push("set more off");
  lines.push(`version 17`);
  lines.push("");

  // ── Load data ───────────────────────────────────────────────────────────────
  lines.push(`* ── Load data ────────────────────────────────────────────────────────────`);
  lines.push(`import delimited "${filename}", clear`);
  lines.push("");

  // ── Data dictionary ─────────────────────────────────────────────────────────
  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push(`* ── Variable definitions ─────────────────────────────────────────────────`);
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => {
      const clean = String(v).replace(/`/g, "'").replace(/\n/g, " ").slice(0, 120);
      lines.push(`* ${k}: ${clean}`);
    });
    lines.push("");
  }

  // ── Pipeline steps ──────────────────────────────────────────────────────────
  if (pipeline.length) {
    lines.push(`* ── Data pipeline ────────────────────────────────────────────────────────`);
    pipeline.forEach(step => {
      const code = transpileStep(step);
      if (code) lines.push(code);
    });
    lines.push("");
  }

  // ── Model ───────────────────────────────────────────────────────────────────
  lines.push(`* ── Estimation ───────────────────────────────────────────────────────────`);
  lines.push(...transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel }));
  lines.push("");

  return lines.join("\n");
}

// ─── STEP TRANSPILER ─────────────────────────────────────────────────────────
function transpileStep(step) {
  const { type, params = {} } = step;
  switch (type) {
    case "rename":
      return `rename ${params.from} ${params.to}`;
    case "drop":
      return `drop ${(params.cols ?? []).join(" ")}`;
    case "filter": {
      const { col, op, val } = params;
      const v = typeof val === "string" ? `"${val}"` : val;
      return `keep if ${col} ${op ?? "=="} ${v}`;
    }
    case "drop_na":
      if (params.cols?.length) return `drop if missing(${params.cols.join(", ")})`;
      return `drop if missing(*)`;
    case "fill_na": {
      const { col, mode, value } = params;
      if (mode === "mean")   return `egen _tmp = mean(${col})\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
      if (mode === "median") return `egen _tmp = median(${col})\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
      if (mode === "mode") {
        return [
          `egen _tmp_grp = group(${col})`,
          `* Note: mode fill — manually select most frequent value`,
          `replace ${col} = .  // replace with computed mode`,
          `drop _tmp_grp`,
        ].join("\n");
      }
      if (mode === "ffill") return `* forward fill
local obs = _N
forval i = 2/\`obs' {
  if missing(${col}[\`i']) replace ${col} = ${col}[\`i'-1] in \`i'
}
`;
      const v = typeof value === "string" ? `"${value}"` : value ?? 0;
      return `replace ${col} = ${v} if missing(${col})`;
    }
    case "fill_na_grouped": {
      const { col, groupCol, mode } = params;
      if (mode === "mean")   return `bysort ${groupCol}: egen _tmp = mean(${col})\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
      if (mode === "median") return `bysort ${groupCol}: egen _tmp = median(${col})\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
      return `* fill_na_grouped (${mode}) by ${groupCol}: add custom logic`;
    }
    case "type_cast": {
      const { col, targetType } = params;
      if (targetType === "numeric") return `destring ${col}, replace force`;
      if (targetType === "string")  return `tostring ${col}, replace`;
      return `* type_cast ${col} to ${targetType}`;
    }
    case "log":
      return `gen log_${params.col} = log(${params.col})`;
    case "sq":
      return `gen ${params.col}_sq = ${params.col}^2`;
    case "std":
      return `egen _mn = mean(${params.col})\negen _sd = sd(${params.col})\ngen ${params.col}_z = (${params.col} - _mn) / _sd\ndrop _mn _sd`;
    case "winz": {
      const { col, p1, p99 } = params;
      if (p1 != null && p99 != null) {
        return `replace ${col} = max(${p1}, min(${p99}, ${col}))`;
      }
      return `winsor2 ${col}, cuts(1 99) replace`;
    }
    case "dummy":
      return `tabulate ${params.col}, generate(${params.col}_)`;
    case "lag":
      if (params.entityCol) {
        return `xtset ${params.entityCol} ${params.timeCol ?? "_t"}\ngen ${params.col}_lag${params.n ?? 1} = L${params.n ?? 1}.${params.col}`;
      }
      return `gen ${params.col}_lag${params.n ?? 1} = L${params.n ?? 1}.${params.col}`;
    case "lead":
      if (params.entityCol) {
        return `xtset ${params.entityCol} ${params.timeCol ?? "_t"}\ngen ${params.col}_lead${params.n ?? 1} = F${params.n ?? 1}.${params.col}`;
      }
      return `gen ${params.col}_lead${params.n ?? 1} = F${params.n ?? 1}.${params.col}`;
    case "diff":
      if (params.entityCol) {
        return `xtset ${params.entityCol} ${params.timeCol ?? "_t"}\ngen ${params.col}_d = D.${params.col}`;
      }
      return `gen ${params.col}_d = D.${params.col}`;
    case "ix":
      return `gen ${params.col1}_x_${params.col2} = ${params.col1} * ${params.col2}`;
    case "did":
      return `gen did = ${params.postVar} * ${params.treatVar}`;
    case "mutate":
      return `gen ${params.newCol} = ${params.expr}`;
    case "arrange":
      return `sort ${params.col}`;
    case "group_summarize": {
      const { groupCol, agg = {} } = params;
      const cmds = Object.entries(agg).map(([col, fn]) => `  egen ${col}_${fn} = ${fn}(${col}), by(${groupCol})`);
      return [`collapse (${Object.values(agg)[0] ?? "mean"}) ${Object.keys(agg).join(" ")}, by(${groupCol})`, ...cmds].join("\n");
    }
    case "pivot_longer": {
      const { idCols = [], valueName = "value", variableName = "variable", valueCols = [] } = params;
      return `reshape long ${valueCols.join(" ")}, i(${idCols.join(" ")}) j(${variableName}) string`;
    }
    case "date_parse":
      return `gen ${params.col}_dt = date(${params.col}, "YMD")`;
    case "date_extract":
      return `gen ${params.newCol} = ${params.part ?? "year"}(${params.col}_dt)`;
    case "recode": {
      const entries = Object.entries(params.map ?? {});
      return entries.map(([from, to]) => {
        const f = isNaN(Number(from)) ? `"${from}"` : from;
        const t = isNaN(Number(to))   ? `"${to}"`   : to;
        return `replace ${params.col} = ${t} if ${params.col} == ${f}`;
      }).join("\n");
    }
    case "trim_outliers": {
      const { col } = params;
      return [`_pctile ${col}, percentiles(25 75)`, `local q1 = r(r1)`, `local q3 = r(r2)`, `local iqr = \`q3' - \`q1'`, `drop if ${col} < \`q1' - 1.5*\`iqr' | ${col} > \`q3' + 1.5*\`iqr'`].join("\n");
    }
    case "flag_outliers": {
      const { col } = params;
      return [`_pctile ${col}, percentiles(25 75)`, `local q1 = r(r1)`, `local q3 = r(r2)`, `local iqr = \`q3' - \`q1'`, `gen ${col}_outlier = (${col} < \`q1' - 1.5*\`iqr') | (${col} > \`q3' + 1.5*\`iqr')`].join("\n");
    }
    case "quickclean":
      return `duplicates drop\ndrop if missing(*)`;
    case "normalize_cats":
      if (params.col) return `replace ${params.col} = strtrim(lower(${params.col}))`;
      return `* normalize_cats: manual step`;
    case "extract_regex":
      return `* regex extract: gen ${params.newCol} from ${params.col} using pattern "${params.regex}"\n* Use -regexm()- / -regexs()-:\n* gen ${params.newCol} = regexs(1) if regexm(${params.col}, "${params.regex}")`;
    case "join":
      return `* merge: load second dataset as df_right.dta first\n* merge ${params.how ?? "1:1"} ${params.key} using "df_right.dta"`;
    case "append":
      return `* append: load second dataset\n* append using "df_right.dta"`;
    case "ai_tr":
      return `* AI transform: ${params.description ?? "(manual step)"}`;
    case "factor_interactions": {
      const { cols } = params;
      if (cols?.length >= 2) return `gen ${cols.join("_x_")} = ${cols[0]} * ${cols[1]}`;
      return `* factor_interactions`;
    }
    default:
      return `* [${type}] — not yet transpiled`;
  }
}

// ─── MODEL TRANSPILER ─────────────────────────────────────────────────────────
function transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel }) {
  const lines = [];
  const xList = allX.join(" ");

  switch (type) {
    case "OLS":
      lines.push(`reg ${yVar} ${xList}, robust`);
      lines.push(`estimates store m_ols`);
      break;

    case "FE":
      lines.push(`* Fixed Effects (within)`);
      lines.push(`xtset ${entityCol} ${timeCol}`);
      lines.push(`xtreg ${yVar} ${xList}, fe vce(cluster ${entityCol})`);
      lines.push(`estimates store m_fe`);
      break;

    case "FD":
      lines.push(`* First Differences`);
      lines.push(`xtset ${entityCol} ${timeCol}`);
      lines.push(`xtreg ${yVar} ${xList}, fd vce(cluster ${entityCol})`);
      lines.push(`estimates store m_fd`);
      break;

    case "2SLS": {
      const endog = xVars.join(" ");
      const instr = zVars.join(" ");
      const exog  = wVars.join(" ");
      lines.push(`* Two-Stage Least Squares / IV`);
      lines.push(`ivregress 2sls ${yVar} ${exog ? `(${endog} = ${instr}) ${exog}` : `(${endog} = ${instr})`}, robust`);
      lines.push(`estimates store m_2sls`);
      lines.push(`* First-stage F-statistic`);
      lines.push(`estat firststage`);
      break;
    }

    case "DiD": {
      const extra = wVars.length ? ` ${wVars.join(" ")}` : "";
      lines.push(`* Difference-in-Differences (2×2)`);
      lines.push(`gen did = ${postVar} * ${treatVar}`);
      lines.push(`reg ${yVar} ${postVar} ${treatVar} did${extra}, robust`);
      lines.push(`estimates store m_did`);
      break;
    }

    case "TWFE": {
      const extra = wVars.length ? ` ${wVars.join(" ")}` : "";
      lines.push(`* Two-Way Fixed Effects DiD`);
      lines.push(`xtset ${entityCol} ${timeCol}`);
      lines.push(`reghdfe ${yVar} ${treatVar}${extra}, absorb(${entityCol} ${timeCol}) vce(cluster ${entityCol})`);
      lines.push(`* If reghdfe not installed: ssc install reghdfe`);
      lines.push(`estimates store m_twfe`);
      break;
    }

    case "RDD": {
      const kernelOpt = kernel === "uniform" ? "nw(1)" : kernel === "epanechnikov" ? "kernel(epanechnikov)" : "kernel(triangular)";
      const extra = wVars.length ? ` ${wVars.join(" ")}` : "";
      lines.push(`* Sharp RDD — local linear regression`);
      lines.push(`* If rdrobust not installed: ssc install rdrobust`);
      lines.push(`rdrobust ${yVar} ${runningVar}, c(${cutoff ?? 0}) h(${bandwidth ?? "# set bandwidth"}) ${kernelOpt}${extra ? ` covs(${wVars.join(" ")})` : ""}`);
      lines.push(`* Manual approach (WLS local linear):`);
      lines.push(`gen _above = (${runningVar} >= ${cutoff ?? 0})`);
      lines.push(`gen _run_c = ${runningVar} - ${cutoff ?? 0}`);
      lines.push(`gen _above_run = _above * _run_c`);
      lines.push(`* Triangular kernel weights:`);
      lines.push(`gen _w = max(0, 1 - abs(_run_c) / ${bandwidth ?? 1}) if abs(_run_c) <= ${bandwidth ?? 1}`);
      lines.push(`reg ${yVar} _above _run_c _above_run${extra} [aw=_w], robust`);
      lines.push(`drop _above _run_c _above_run _w`);
      break;
    }

    case "Logit":
      lines.push(`logit ${yVar} ${xList}`);
      lines.push(`estimates store m_logit`);
      lines.push(`* Marginal effects at the mean`);
      lines.push(`margins, dydx(*) atmeans`);
      break;

    case "Probit":
      lines.push(`probit ${yVar} ${xList}`);
      lines.push(`estimates store m_probit`);
      lines.push(`* Marginal effects at the mean`);
      lines.push(`margins, dydx(*) atmeans`);
      break;

    default:
      lines.push(`* Model type "${type}" — add estimation command here`);
  }

  return lines;
}
