// ─── LITUX · services/export/stataScript.js ────────────────────────────
// Generates a self-contained Stata .do replication file.
//
// Config shape (same as rScript.js / pythonScript.js):
//   { filename, pipeline, model, auditTrail, dataDictionary }
//
// model shape:
//   { type, yVar, xVars, wVars, zVars, entityCol, timeCol,
//     postVar, treatVar, runningVar, cutoff, bandwidth, kernel }

import { toStata, jsExprToStata, stataRightLoad } from "../../pipeline/stepTranslators.js";
import { buildStataLoadLine } from "./loadLine.js";

export function generateStataScript(config = {}) {
  const {
    filename       = "dataset.csv",
    pipeline       = [],
    model          = {},
    dataDictionary = null,
    dataLoadOpts   = null,
    allDatasets    = {},
  } = config;

  const {
    type       = "OLS",
    yVar       = "y",
    xVars      = [],
    wVars      = [],
    zVars      = [],
    entityCol  = null,
    timeCol    = null,
    postVar    = null,
    treatVar   = null,
    runningVar    = null,
    cutoff        = null,
    bandwidth     = null,
    kernel        = "triangular",
    distCol       = null,
    treatmentCol  = null,
    offsetCol     = null,
    seType        = "classical",
    clusterVar    = null,
    clusterVar2   = null,
  } = model;

  const stem     = filename.replace(/\.[^.]+$/, "");
  const stataFile = filename.replace(/\\/g, "/");  // forward slashes — safe in Stata
  const allX = [...(xVars ?? []), ...(wVars ?? [])];

  const lines = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`* ${"─".repeat(71)}`);
  lines.push(`* Replication do-file — ${stem}`);
  lines.push(`* Generated by Litux · ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`* Estimator: ${type}`);
  lines.push(`* ${"─".repeat(71)}`);
  lines.push("");
  lines.push("clear all");
  lines.push("set more off");
  lines.push(`version 17`);
  lines.push("");

  // ── Load data ───────────────────────────────────────────────────────────────
  lines.push(`* ── Load data ────────────────────────────────────────────────────────────`);
  lines.push(buildStataLoadLine(stataFile, dataLoadOpts));
  lines.push("");

  // ── Data dictionary ─────────────────────────────────────────────────────────
  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push(`* ── Variable definitions ─────────────────────────────────────────────────`);
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => {
      const clean = String(v).replace(/`/g, "'").replace(/\n/g, " ").slice(0, 120);
      lines.push(`* ${k}: ${clean}`);
    });
    lines.push("");
  }

  // ── Pipeline steps ──────────────────────────────────────────────────────────
  if (pipeline.length) {
    lines.push(`* ── Data pipeline ────────────────────────────────────────────────────────`);
    pipeline.forEach(step => {
      const code = transpileStep(step, allDatasets);
      if (code) lines.push(code);
    });
    lines.push("");
  }

  // ── Model ───────────────────────────────────────────────────────────────────
  lines.push(`* ── Estimation ───────────────────────────────────────────────────────────`);
  lines.push(...transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, distCol, treatmentCol, factorVars: model.factorVars ?? [], feCols: model.feCols ?? null, offsetCol, cohortCol: model.cohortCol ?? null, periodCol: model.periodCol ?? null, controlMode: model.controlMode ?? null, refPeriod: model.refPeriod ?? null, interactionTerms: model.interactionTerms ?? [], xVarsRaw: model.xVarsRaw ?? null, wVarsRaw: model.wVarsRaw ?? null, seType, clusterVar, clusterVar2, noIntercept: model.noIntercept ?? false }));
  lines.push("");

  return lines.join("\n");
}

// ─── STEP TRANSPILER ─────────────────────────────────────────────────────────
function stVar(s) {
  return String(s ?? "").replace(/[^a-zA-Z0-9_]/g, "_").replace(/^([0-9])/, "_$1").slice(0, 32);
}

function stStr(s) {
  return `"${String(s ?? "").replace(/"/g, `""`)}"`;
}

function stValue(v, dtype = null) {
  if (v === null || v === undefined) return ".";
  if (dtype === "number" || typeof v === "number") {
    const n = Number(v);
    return isFinite(n) ? String(n) : ".";
  }
  return stStr(v);
}

function stWhere(where) {
  if (!where?.col || !where?.op) return "1";
  const c = stVar(where.col);
  const v = where.value;
  switch (where.op) {
    case "equals": return `${c} == ${stValue(v)}`;
    case "not_equals": return `${c} != ${stValue(v)}`;
    case "contains": return `strpos(${c}, ${stStr(v ?? "")}) > 0`;
    case "starts": return `substr(${c}, 1, length(${stStr(v ?? "")})) == ${stStr(v ?? "")}`;
    case "ends": return `substr(${c}, -length(${stStr(v ?? "")}), .) == ${stStr(v ?? "")}`;
    case "gt": return `${c} > ${Number(v)}`;
    case "lt": return `${c} < ${Number(v)}`;
    case "between": {
      const lo = Number(Array.isArray(v) ? v[0] : v);
      const hi = Number(Array.isArray(v) ? v[1] : v);
      return `${c} >= ${lo} & ${c} <= ${hi}`;
    }
    case "empty": return `missing(${c}) | ${c} == ""`;
    case "notempty": return `!missing(${c}) & ${c} != ""`;
    default: return "1";
  }
}

function isGridEditStep(step) {
  return ["add_column", "add_row", "set_where", "replace", "str_splice"].includes(step.type);
}

function transpileStep(step, allDatasets = {}) {
  const { type, params = {} } = step;
  if (typeof type === "string" && type.startsWith("sp_")) return toStata(step, "df", allDatasets);
  switch (type) {
    case "add_column": {
      const out = stVar(step.nn);
      if (step.dtype === "number") return `gen double ${out} = ${stValue(step.fill, "number")}`;
      return `gen strL ${out} = ${stValue(step.fill)}`;
    }
    case "add_row": {
      const count = Math.max(1, Number(step.count) || 1);
      const assigns = Object.entries(step.values || {})
        .map(([k, v]) => `replace ${stVar(k)} = ${stValue(v)} in \`i'`);
      return [
        `* add_row: append ${count} synthetic row(s); unspecified columns remain missing`,
        `local __oldN = _N`,
        `set obs \`= _N + ${count}'`,
        `forvalues i = \`= \`__oldN' + 1'/\`=_N' {`,
        ...assigns.map(x => `  ${x}`),
        `}`,
      ].join("\n");
    }
    case "set_where": {
      const target = stVar(step.col);
      if (step.action === "clear") {
        return [
          `capture confirm string variable ${target}`,
          `if !_rc replace ${target} = "" if ${stWhere(step.where)}`,
          `else replace ${target} = . if ${stWhere(step.where)}`,
        ].join("\n");
      }
      return `replace ${target} = ${stValue(step.value, step.dtype)} if ${stWhere(step.where)}`;
    }
    case "replace": {
      const src = stVar(step.col);
      const out = stVar(step.nn || step.col);
      const mode = step.match?.mode || "exact";
      const find = step.match?.find ?? "";
      const repl = step.replaceWith ?? "";
      const init = step.nn ? `capture confirm string variable ${src}\nif !_rc gen strL ${out} = ${src}\nelse gen double ${out} = ${src}\n` : "";
      if (mode === "exact") return `${init}replace ${out} = ${stValue(repl)} if ${out} == ${stValue(find)}`;
      if (mode === "contains") return `${init}replace ${out} = subinstr(${out}, ${stStr(find)}, ${stStr(repl)}, .)`;
      return `${init}replace ${out} = regexr(${out}, ${stStr(find)}, ${stStr(repl)})`;
    }
    case "str_splice": {
      const src = stVar(step.col);
      const out = stVar(step.nn || step.col);
      const pos = Number(step.position) || 1;
      const n = Math.max(0, Number(step.count) || 0);
      const text = stStr(step.text ?? "");
      const init = step.nn
        ? `gen strL ${out} = string(${src})\n`
        : `capture confirm string variable ${out}\nif _rc tostring ${out}, replace force\n`;
      const p = `cond(${pos} < 0, max(1, length(${out}) + ${pos} + 1), ${pos})`;
      if (step.mode === "delete") return `${init}replace ${out} = substr(${out}, 1, ${p} - 1) + substr(${out}, ${p} + ${n}, .)`;
      if (step.mode === "overwrite") return `${init}replace ${out} = substr(${out}, 1, ${p} - 1) + ${text} + substr(${out}, ${p} + ${n}, .)`;
      return `${init}replace ${out} = substr(${out}, 1, ${p} - 1) + ${text} + substr(${out}, ${p}, .)`;
    }
    case "rename":
      return `rename ${stVar(step.col)} ${stVar(step.newName)}`;
    case "drop":
      return `drop ${stVar(step.col)}`;
    case "filter": {
      const col = stVar(step.col), v = step.value;
      switch (step.op) {
        case "notna": return `keep if !missing(${col})`;
        case "eq":    return `keep if ${col} == ${stValue(v)}`;
        case "neq":   return `keep if ${col} != ${stValue(v)}`;
        case "gt":    return `keep if ${col} > ${Number(v)}`;
        case "lt":    return `keep if ${col} < ${Number(v)}`;
        case "gte":   return `keep if ${col} >= ${Number(v)}`;
        case "lte":   return `keep if ${col} <= ${Number(v)}`;
        default:      return `* filter: unsupported op "${step.op}"`;
      }
    }
    case "drop_na": {
      const cols = (step.cols ?? []).map(stVar);
      if (!cols.length) return `* drop_na: specify columns (Stata has no all-column missing drop)`;
      if (step.how === "all") return `drop if ${cols.map(c => `missing(${c})`).join(" & ")}`;
      return `drop if missing(${cols.join(", ")})`;
    }
    case "fill_na": {
      const col = stVar(step.col);
      if (step.strategy === "mean")   return `egen _tmp = mean(${col})\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
      if (step.strategy === "median") return `egen _tmp = median(${col})\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
      if (step.strategy === "mode")   return `egen _tmp = mode(${col}), maxmode\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
      if (step.strategy === "forward_fill")  return `sort _n\nby _n: replace ${col} = ${col}[_n-1] if missing(${col})  /* forward fill — ensure data are sorted as intended */`;
      if (step.strategy === "backward_fill") return `gsort -_n\nreplace ${col} = ${col}[_n-1] if missing(${col})\nsort _n  /* backward fill */`;
      return `replace ${col} = ${stValue(step.value)} if missing(${col})`;
    }
    case "fill_na_grouped": {
      const col = stVar(step.col), g = stVar(step.groupCol);
      const fn = step.strategy === "median" ? "median" : "mean";
      return `bysort ${g}: egen _tmp = ${fn}(${col})\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
    }
    case "type_cast": {
      const col = stVar(step.col);
      if (step.to === "number" || step.to === "number_smart") return `destring ${col}, replace force`;
      if (step.to === "string")  return `tostring ${col}, replace force`;
      if (step.to === "boolean") return `gen byte _b = (${col} != 0 & !missing(${col}))\ndrop ${col}\nrename _b ${col}`;
      return `destring ${col}, replace force`;
    }
    case "log": {
      const col = stVar(step.col), out = stVar(step.nn || `log_${step.col}`);
      return `gen ${out} = log(${col})`;
    }
    case "sq": {
      const col = stVar(step.col), out = stVar(step.nn || `${step.col}_sq`);
      return `gen ${out} = ${col}^2`;
    }
    case "std": {
      const col = stVar(step.col), out = stVar(step.nn || `${step.col}_z`);
      // Fixed mu/sd captured at step-creation time (matches the app + R script).
      return `gen ${out} = (${col} - ${Number(step.mu)}) / ${Number(step.sd)}`;
    }
    case "winz": {
      const col = stVar(step.col);
      const out = step.nn && step.nn !== step.col ? stVar(step.nn) : col;
      const lo = Number(step.lo), hi = Number(step.hi);
      return out === col
        ? `replace ${col} = max(${lo}, min(${hi}, ${col}))`
        : `gen ${out} = max(${lo}, min(${hi}, ${col}))`;
    }
    case "dummy":
      return `tabulate ${stVar(step.col)}, generate(${(step.pfx || step.col)}_)`;
    case "lag": {
      const col = stVar(step.col), out = stVar(step.nn || `${step.col}_lag${step.n ?? 1}`), n = step.n ?? 1;
      if (step.ec && step.tc) return `xtset ${stVar(step.ec)} ${stVar(step.tc)}\ngen ${out} = L${n}.${col}`;
      return `gen ${out} = ${col}[_n-${n}]`;
    }
    case "lead": {
      const col = stVar(step.col), out = stVar(step.nn || `${step.col}_lead${step.n ?? 1}`), n = step.n ?? 1;
      if (step.ec && step.tc) return `xtset ${stVar(step.ec)} ${stVar(step.tc)}\ngen ${out} = F${n}.${col}`;
      return `gen ${out} = ${col}[_n+${n}]`;
    }
    case "diff": {
      const col = stVar(step.col), out = stVar(step.nn || `${step.col}_d`);
      if (step.ec && step.tc) return `xtset ${stVar(step.ec)} ${stVar(step.tc)}\ngen ${out} = D.${col}`;
      return `gen ${out} = ${col} - ${col}[_n-1]`;
    }
    case "ix": {
      const out = stVar(step.nn || `${step.c1}_x_${step.c2}`);
      return `gen ${out} = ${stVar(step.c1)} * ${stVar(step.c2)}`;
    }
    case "did": {
      const out = stVar(step.nn || "did");
      return `gen ${out} = ${stVar(step.tc)} * ${stVar(step.pc)}`;
    }
    case "mutate": {
      const nn     = step.nn ?? "newcol";
      const stExpr = jsExprToStata(step.expr);
      if (stExpr) return `gen ${stVar(nn)} = ${stExpr}`;
      return [
        `* mutate: ${nn} = ${step.expr}`,
        `* NOTE: expression uses JS syntax — translate to Stata manually`,
        `* gen ${stVar(nn)} = <Stata expression>`,
      ].join("\n");
    }
    case "arrange":
      return step.dir === "desc" ? `gsort -${stVar(step.col)}` : `sort ${stVar(step.col)}`;
    case "group_summarize": {
      const fnMap = { mean: "mean", sum: "sum", count: "count", min: "min", max: "max", sd: "sd", median: "median" };
      const collapse = (step.aggs ?? []).map(a =>
        `(${fnMap[a.fn] ?? "mean"}) ${stVar(a.nn)}=${stVar(a.col)}`).join(" ");
      const by = (step.by ?? []).map(stVar).join(" ");
      return `collapse ${collapse}, by(${by})`;
    }
    case "group_transform": {
      const by = step.by ?? [];
      const col = step.col ?? "";
      const out = stVar(step.nn ?? `${step.fn ?? "mean"}_${col}`);
      const fn = step.fn ?? "mean";
      const egenFn = fn === "count" ? "count" : fn === "sd" ? "sd" : fn === "rank" ? "rank" : fn === "median" ? "median" : fn;
      return `bysort ${by.map(stVar).join(" ")}: egen ${out} = ${egenFn}(${stVar(col)})`;
    }
    case "pivot_longer":
      return [
        `* pivot_longer: reshape to long — value columns must share a common stub for native reshape.`,
        `reshape long ${(step.cols ?? []).map(stVar).join(" ")}, i(${(step.idCols ?? []).map(stVar).join(" ")}) j(${stVar(step.namesTo || "name")}) string`,
      ].join("\n");
    case "pivot_wider": {
      const valsFrom = Array.isArray(step.valuesFrom) ? step.valuesFrom : [step.valuesFrom].filter(Boolean);
      return [
        `* pivot_wider: long -> wide`,
        `reshape wide ${valsFrom.map(stVar).join(" ")}, i(${(step.idCols ?? []).map(stVar).join(" ")}) j(${stVar(step.namesFrom)})`,
      ].join("\n");
    }
    case "date_parse": {
      const col = stVar(step.col);
      const out = (step.nn && step.nn !== step.col) ? stVar(step.nn) : col;
      return [
        `* date_parse: parse string ${col} into a Stata %td date → ${out}`,
        `gen _tmp_dp = date(${col}, "YMD")`,
        `gen ${out} = _tmp_dp`,
        `drop _tmp_dp`,
        `format ${out} %td`,
      ].join("\n");
    }
    case "date_extract": {
      const col = stVar(step.col);
      const lines = (step.parts ?? []).map(p => {
        const out = stVar(step.names?.[p] ?? `${step.col}_${p}`);
        if (p === "year")      return `gen ${out} = year(${col})`;
        if (p === "month")     return `gen ${out} = month(${col})`;
        if (p === "dow")       return `gen ${out} = dow(${col})`;
        if (p === "isweekend") return `gen ${out} = inlist(dow(${col}), 0, 6)`;
        return null;
      }).filter(Boolean);
      return lines.length
        ? [`* date_extract assumes ${col} is a Stata date; use date() to parse a string first`, ...lines].join("\n")
        : `* date_extract: no parts specified`;
    }
    case "recode":
      return Object.entries(step.map ?? {}).map(([from, to]) => {
        const f = isNaN(Number(from)) ? `"${from}"` : from;
        const t = isNaN(Number(to))   ? `"${to}"`   : to;
        return `replace ${stVar(step.col)} = ${t} if ${stVar(step.col)} == ${f}`;
      }).join("\n") || `* recode: no mapping specified`;
    case "trim_outliers": {
      const col = stVar(step.col);
      // Fixed bounds captured at step-creation time (matches the app + R script).
      return `drop if ${col} < ${Number(step.lo)} | ${col} > ${Number(step.hi)}`;
    }
    case "flag_outliers": {
      const col = stVar(step.col), out = stVar(step.nn || `${step.col}_outlier`);
      if (step.method === "zscore") {
        const thr = Number(step.threshold) || 3;
        return `egen _mn = mean(${col})\negen _sd = sd(${col})\ngen ${out} = abs((${col} - _mn) / _sd) > ${thr}\ndrop _mn _sd`;
      }
      return [
        `_pctile ${col}, percentiles(25 75)`,
        `local q1 = r(r1)`,
        `local q3 = r(r2)`,
        `local iqr = \`q3' - \`q1'`,
        `gen ${out} = (${col} < \`q1' - 1.5*\`iqr') | (${col} > \`q3' + 1.5*\`iqr')`,
      ].join("\n");
    }
    case "quickclean": {
      const col = stVar(step.col);
      if (step.mode === "upper") return `replace ${col} = upper(${col})`;
      if (step.mode === "title") return `replace ${col} = proper(${col})`;
      return `replace ${col} = lower(${col})`;
    }
    case "clean_strings": {
      const col = stVar(step.col);
      let inner = `itrim(strtrim(${col}))`;
      if (step.case === "lower") inner = `lower(${inner})`;
      else if (step.case === "upper") inner = `upper(${inner})`;
      else if (step.case === "title") inner = `proper(${inner})`;
      return `replace ${col} = ${inner}`;
    }
    case "normalize_cats":
      return Object.entries(step.map ?? {}).map(([from, to]) =>
        `replace ${stVar(step.col)} = "${to}" if ${stVar(step.col)} == "${from}"`).join("\n")
        || `* normalize_cats: no mapping specified`;
    case "extract_regex": {
      const col = stVar(step.col), out = stVar(step.nn || `${step.col}_num`);
      if (step.regex) {
        return [
          `gen ${out} = real(regexs(1)) if regexm(${col}, "${step.regex}")`,
        ].join("\n");
      }
      // locale-aware numeric parse: strip non-numeric, normalize decimal mark.
      if (step.locale === "comma") {
        return [
          `gen _s = subinstr(${col}, ".", "", .)`,
          `replace _s = subinstr(_s, ",", ".", .)`,
          `gen ${out} = real(_s)`,
          `drop _s`,
        ].join("\n");
      }
      return `gen ${out} = real(subinstr(${col}, ",", "", .))`;
    }
    case "factor_interactions": {
      const cont = stVar(step.contCol);
      const pfx = step.prefix || `${step.contCol}_x_`;
      const lines = (step.dummyCols ?? []).map(d => `gen ${stVar(pfx + d)} = ${cont} * ${stVar(d)}`);
      return lines.length ? lines.join("\n") : `* factor_interactions: no dummy columns specified`;
    }
    case "if_else": {
      const out = stVar(step.nn);
      const cond = jsExprToStata(step.cond);
      if (!cond) return `* if_else: ${step.nn} = cond(${step.cond}, ...) — translate condition to Stata manually`;
      return `gen ${out} = cond(${cond}, ${stValue(step.trueVal)}, ${stValue(step.falseVal)})`;
    }
    case "case_when": {
      const out = stVar(step.nn);
      const branches = (step.cases ?? [])
        .map(c => { const cc = jsExprToStata(c.cond); return cc ? `replace ${out} = ${stValue(c.val)} if ${cc}` : null; })
        .filter(Boolean);
      if (!branches.length) return `* case_when: no valid conditions — translate manually`;
      return [`gen ${out} = ${stValue(step.defaultVal)}`, ...branches].join("\n");
    }
    case "grouped_mutate": {
      const by = (step.by ?? []).map(stVar).join(" ");
      const out = stVar(step.newCol || "grouped");
      const fn = step.fn ?? "mean";
      if (!by || !step.newCol) return `* grouped_mutate: incomplete config`;
      const egenFn = fn === "sd" ? "sd" : fn === "count" ? "count" : fn === "expr" ? "mean" : fn;
      return [
        `* grouped_mutate: ${fn} over groups${step.condition?.length ? " (row conditions applied in-app — review)" : ""}`,
        `bysort ${by}: egen ${out} = ${egenFn}(${stVar(step.col || by.split(" ")[0])})`,
      ].join("\n");
    }
    case "balance_panel": {
      const ent = stVar(step.entityCol), tim = stVar(step.timeCol);
      const lines = [
        `* Balance panel: fill ${step.entityCol} × ${step.timeCol} grid (static cols may need manual carry-forward)`,
        `xtset ${ent} ${tim}`,
        `tsfill, full`,
      ];
      const fill = Number(step.fillValue) || 0;
      for (const oc of (step.outcomeCols ?? [])) lines.push(`replace ${stVar(oc)} = ${fill} if missing(${stVar(oc)})`);
      return lines.join("\n");
    }
    case "distinct": {
      const subset = step.subset ?? params.subset ?? [];
      return `duplicates drop ${subset.length ? subset.join(" ") : ""}, force`;
    }
    case "join": {
      const how      = step.how || "left";
      const lk       = step.leftKey  ?? "id";
      const rk       = step.rightKey ?? lk;
      const sfx      = step.suffix   ?? "_r";
      const sameKey  = lk === rk ? lk : `${lk} = ${rk}`;
      if (how === "semi" || how === "anti") {
        const keep = how === "semi" ? "keep(match)" : "keep(master)";
        return [
          `* ${how} join: row filter only, no right-side columns added`,
          `preserve`,
          `  ${stataRightLoad(step.rightId, allDatasets)}`,
          `  keep ${rk}`,
          `  duplicates drop`,
          lk === rk ? null : `  rename ${rk} ${lk}  /* align key names */`,
          `  save "__right_keys_tmp.dta", replace`,
          `restore`,
          `merge m:1 ${lk} using "__right_keys_tmp.dta", ${keep} nogen`,
          `erase "__right_keys_tmp.dta"`,
        ].filter(Boolean).join("\n");
      }
      const keep = {
        left: "keep(master match)",
        inner: "keep(match)",
        right: "keep(match using)",
        full: "keep(master match using)",
      }[how] ?? "keep(master match)";
      return [
        `* ${how} join: load right dataset, merge on ${sameKey}`,
        `preserve`,
        `  ${stataRightLoad(step.rightId, allDatasets)}`,
        lk === rk ? null : `  rename ${rk} ${lk}  /* align key names */`,
        `  save "__right_tmp.dta", replace`,
        `restore`,
        `merge 1:1 ${lk} using "__right_tmp.dta", ${keep} nogen suffixes("" "${sfx}")`,
        `erase "__right_tmp.dta"`,
      ].filter(Boolean).join("\n");
    }
    case "append": {
      return [
        `* Append: stack right dataset below current`,
        `preserve`,
        `  ${stataRightLoad(step.rightId, allDatasets)}`,
        `  save "__append_tmp.dta", replace`,
        `restore`,
        `append using "__append_tmp.dta"`,
        `erase "__append_tmp.dta"`,
      ].join("\n");
    }
    case "bind_cols": {
      return [
        `* bind_cols: align by row order`,
        `gen long __row_order = _n`,
        `preserve`,
        `  ${stataRightLoad(step.rightId, allDatasets)}`,
        `  gen long __row_order = _n`,
        `  save "__bind_cols_tmp.dta", replace`,
        `restore`,
        `merge 1:1 __row_order using "__bind_cols_tmp.dta", keep(match) nogen suffixes("" "${step.suffix ?? "_r"}")`,
        `drop __row_order`,
        `erase "__bind_cols_tmp.dta"`,
      ].join("\n");
    }
    case "union": {
      return [
        `* union: append right dataset, then drop full-row duplicates`,
        `preserve`,
        `  ${stataRightLoad(step.rightId, allDatasets)}`,
        `  save "__union_tmp.dta", replace`,
        `restore`,
        `append using "__union_tmp.dta"`,
        `duplicates drop, force`,
        `erase "__union_tmp.dta"`,
      ].join("\n");
    }
    case "intersect":
    case "setdiff": {
      const keep = type === "intersect" ? "keep(match)" : "keep(master)";
      return [
        `* ${type}: merge on shared columns; replace /* shared keys */ with the common key list if needed`,
        `preserve`,
        `  ${stataRightLoad(step.rightId, allDatasets)}`,
        `  save "__setop_tmp.dta", replace`,
        `restore`,
        `merge m:1 /* shared keys */ using "__setop_tmp.dta", ${keep} nogen`,
        `erase "__setop_tmp.dta"`,
      ].join("\n");
    }
    case "vector_assign": {
      const out = step.nn ?? "assigned";
      const values = step.values ?? [];
      const seed = Number.isFinite(Number(step.seed)) ? Number(step.seed) : 42;
      if (step.mode === "recycle") {
        return [
          `gen strL ${out} = ""`,
          `local vals "${values.join(" ")}"`,
          `forvalues i = 1/\`=_N' {`,
          `  local k = mod(\`i' - 1, ${values.length || 1}) + 1`,
          `  replace ${out} = word("\`vals'", \`k') in \`i'`,
          `}`,
        ].join("\n");
      }
      if (step.mode === "conditional") {
        const lines = [
          `gen strL ${out} = "${step.elseValue ?? ""}"`,
          ...(step.rules || []).map(r => `replace ${out} = "${r.value}" if ${r.expr}`),
        ];
        return lines.join("\n");
      }
      return [
        `* NOTE: EconSolver uses a seeded mulberry32 RNG; exported values differ but the distribution matches`,
        `set seed ${seed}`,
        `gen double __u = runiform()`,
        `gen strL ${out} = ""`,
        `* assign ${values.join("/")} by equal or weighted bins; adjust cutpoints for exact weights if needed`,
        `drop __u`,
      ].join("\n");
    }
    case "ai_tr": {
      const col    = step.col ?? "col";
      const jsCode = step.js  ?? "";
      const arrowMatch = jsCode.match(/^\s*\(?\s*(\w+)\s*\)?\s*=>\s*([\s\S]+)$/);
      if (arrowMatch) {
        const [, param, body] = arrowMatch;
        const substituted = body.trim().replace(new RegExp(`\\b${param}\\b`, "g"), col);
        const stExpr = jsExprToStata(substituted);
        if (stExpr) return `replace ${col} = ${stExpr}`;
      }
      return [
        `* AI transform on "${col}"`,
        `* JS: ${jsCode}`,
        `* replace ${col} = <Stata expression>`,
      ].join("\n");
    }
    case "patch": {
      const col = step.col ?? "column";
      const row = step.ri ?? step.rowId ?? "?";
      return `* manual cell edit (${col} @ row ${row}) — not replayable on the raw file; load the exported *_cleaned.csv instead (see Data Loading note)`;
    }

    case "geocode": {
      const addrCol = step.addressCol ?? "address";
      const latCol  = step.latCol  ?? "lat";
      const lonCol  = step.lonCol  ?? "lon";
      return [
        `* Geocode: ${addrCol} -> ${latCol} / ${lonCol}`,
        `* Stata has no native geocoding — export addresses, geocode externally, merge back.`,
        `* Step 1: export addresses`,
        `preserve`,
        `keep ${addrCol}`,
        `duplicates drop`,
        `export delimited using "addresses_to_geocode.csv", replace`,
        `restore`,
        `* Step 2: geocode the CSV externally (Python/R with geopy/tidygeocoder)`,
        `* Step 3: merge geocoded coordinates back`,
        `* merge m:1 ${addrCol} using "geocoded_coords.dta", keep(master match) nogenerate`,
        `* rename _lat ${latCol}`,
        `* rename _lon ${lonCol}`,
      ].join("\n");
    }

    case "inject_column": {
      const vals = (step.values ?? []).map(v => (v == null ? "." : Number(v).toFixed(8)));
      // svmat needs an n×1 column vector (backslash separators), not a row vector.
      // Note: Stata matrices are bounded by matsize — for very large n, export the
      // column to a .dta and merge instead.
      const matName = String(step.colName ?? "").replace(/[^a-zA-Z0-9_]/g, "_").slice(0, 32);
      return [
        `* inject_column: "${step.colName}" — extracted from model output`,
        `matrix ${matName} = (${vals.join(" \\ ")})`,
        `svmat ${matName}, name(${step.colName})`,
        `rename ${step.colName}1 ${step.colName}`,
      ].join("\n");
    }

    default:
      return `* [${type}] — not yet transpiled`;
  }
}

// ─── STATA VARLIST BUILDER ────────────────────────────────────────────────────
// Builds Stata varlist RHS. Factor vars use i. prefix; interactions use ## (*) or # (:).
// Continuous vars inside interactions get the c. prefix (required by Stata).
function buildStataVarlist(xVarsRaw, wVarsRaw, xVars, wVars, fvSet, interactionTerms) {
  const fmtBase  = v => fvSet.has(v) ? `i.${v}` : v;
  const fmtInInt = v => fvSet.has(v) ? `i.${v}` : `c.${v}`;
  const rawX = xVarsRaw ?? xVars ?? [];
  const rawW = wVarsRaw ?? wVars ?? [];
  const parts = [...rawX, ...rawW].map(fmtBase);
  for (const { var1, var2, type } of (interactionTerms ?? [])) {
    if (!var1 || !var2) continue;
    const f1 = fmtInInt(var1); const f2 = fmtInInt(var2);
    if (type === "*") {
      const i1 = parts.indexOf(fmtBase(var1)); if (i1 >= 0) parts.splice(i1, 1);
      const i2 = parts.indexOf(fmtBase(var2)); if (i2 >= 0) parts.splice(i2, 1);
      parts.push(`${f1}##${f2}`);
    } else {
      parts.push(`${f1}#${f2}`);
    }
  }
  return parts.join(" ") || "1";
}

// ─── MODEL TRANSPILER ─────────────────────────────────────────────────────────
// Estimators whose Stata command is a panel command (xtreg / reghdfe / areg /
// ppmlhdfe) — these accept vce(cluster) but not vce(hc2)/vce(hc3) or a HAC option.
const PANEL_TYPES = new Set(["FE", "FD", "TWFE", "LSDV", "EventStudy", "PoissonFE"]);

function transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, distCol = null, treatmentCol = null, factorVars = [], feCols = null, offsetCol = null, treatedUnit, treatTime, weightCol = null, cohortCol = null, periodCol = null, controlMode = null, refPeriod = null, interactionTerms = [], xVarsRaw = null, wVarsRaw = null, seType = "classical", clusterVar = null, clusterVar2 = null, noIntercept = false }) {
  const lines = [];
  const fvSet = new Set(factorVars);
  const fmtS  = v => fvSet.has(v) ? `i.${v}` : v;
  const xList = buildStataVarlist(xVarsRaw, wVarsRaw, xVars, wVars, fvSet, interactionTerms);

  // Stata SE option matching the user's selection (was hardcoded ", robust").
  // Returns the trailing option string ("" = classical default, no comma).
  //
  // `regress` supports hc2/hc3 natively via vce(hc2)/vce(hc3) — these used to be
  // collapsed onto plain `robust` (= HC1), so the do-file silently reported
  // different SE than the platform. NOTE: vce(hc2)/vce(hc3) are a `regress`-only
  // feature; commands like xtreg/reghdfe/ivregress do not accept them, which is
  // what `vceNoHC23` is for.
  const seLower = (seType || "classical").toLowerCase();
  const vce = (() => {
    switch (seLower) {
      case "classical": return "";
      case "hc1":       return "robust";
      case "hc2":       return "vce(hc2)";
      case "hc3":       return "vce(hc3)";
      case "clustered": return clusterVar ? `vce(cluster ${clusterVar})` : "robust";
      // Stata's vce(cluster) takes a single variable; true two-way clustering
      // needs a user command (e.g. vcemway / cgmreg) — see the note emitted below.
      case "twoway":    return clusterVar ? `vce(cluster ${clusterVar})` : "robust";
      case "hac":       return "robust";   // reg has no native HAC; use newey for true HAC
      default:          return "";
    }
  })();
  const opt = vce ? `, ${vce}` : "";   // append only when non-empty

  // Same mapping for commands that do NOT accept vce(hc2)/vce(hc3).
  const vceNoHC23 = (seLower === "hc2" || seLower === "hc3") ? "robust" : vce;
  const optNoHC23 = vceNoHC23 ? `, ${vceNoHC23}` : "";

  // Panel commands (xtreg / reghdfe / areg / ppmlhdfe). These used to hardcode
  // vce(cluster entityCol) regardless of the user's selection, which disagreed
  // with the platform — with the default seType="classical", computeRobustSE
  // returns classical SE, it does not cluster by entity. Emitted WITHOUT a
  // leading comma, since these commands already have options (fe / absorb()).
  const pVce = (() => {
    switch (seLower) {
      case "classical": return "";
      case "hc1": case "hc2": case "hc3": return "robust";   // no hc2/hc3 here
      case "clustered": return `vce(cluster ${clusterVar || entityCol})`;
      // NOTE: single cluster variable only. xtreg and areg reject a second one —
      // `xtreg y x, fe vce(cluster a b)` is a syntax error. Two-way clustering is
      // available on reghdfe, which uses pVceHdfe below.
      case "twoway":    return `vce(cluster ${clusterVar || entityCol})`;
      case "hac":       return "robust";   // true panel HAC needs xtscc
      default:          return "";
    }
  })();
  const pOpt = pVce ? ` ${pVce}` : "";

  // reghdfe accepts multi-way clustering, so it can honour two-way exactly.
  const pVceHdfe = (seLower === "twoway" && clusterVar && clusterVar2)
    ? `vce(cluster ${clusterVar} ${clusterVar2})`
    : pVce;
  const pOptHdfe = pVceHdfe ? ` ${pVceHdfe}` : "";

  if (seLower === "twoway" && clusterVar && clusterVar2 && PANEL_TYPES.has(type)) {
    lines.push(`* NOTE: two-way clustering (${clusterVar}, ${clusterVar2}) is emitted on reghdfe.`);
    lines.push(`* xtreg/areg accept one cluster variable only and fall back to ${clusterVar}.`);
    lines.push(``);
  }

  if ((seLower === "hc2" || seLower === "hc3") && PANEL_TYPES.has(type)) {
    lines.push(`* NOTE: Litux used ${seLower.toUpperCase()} SE. xtreg/reghdfe/areg have no hc2/hc3`);
    lines.push(`* option; this reports robust (HC1) SE — expect a small SE difference.`);
    lines.push(``);
  }
  if (seLower === "hac" && PANEL_TYPES.has(type)) {
    lines.push(`* NOTE: Litux used Driscoll-Kraay HAC SE. xtreg/reghdfe have no HAC option;`);
    lines.push(`* this reports robust SE. For Driscoll-Kraay: ssc install xtscc, then`);
    lines.push(`* xtscc ${yVar} ${xList}, fe`);
    lines.push(``);
  }

  // Caveats that belong in the do-file rather than in a code comment nobody sees.
  if (seLower === "twoway" && clusterVar && clusterVar2) {
    lines.push(`* NOTE: Litux used two-way clustered SE (${clusterVar}, ${clusterVar2}).`);
    lines.push(`* Official Stata vce(cluster) accepts one variable only; this do-file clusters`);
    lines.push(`* on ${clusterVar}. For the two-way SE install vcemway: ssc install vcemway`);
    lines.push(``);
  }
  if (seLower === "hac") {
    lines.push(`* NOTE: Litux used Newey-West HAC SE. regress has no HAC option; the line`);
    lines.push(`* below reports robust (HC1) SE. For true HAC: tsset the data, then`);
    lines.push(`* newey ${yVar} ${xList}, lag(#)`);
    lines.push(``);
  }

  switch (type) {
    case "OLS": {
      // `noconstant` is an option, so it needs the option comma. `opt` is either
      // "" or ", vce(...)" — reuse its comma when present rather than emitting a
      // second one, which is a syntax error.
      const olsOpt = noIntercept ? (opt ? `${opt} noconstant` : `, noconstant`) : opt;
      if (noIntercept) lines.push(`* Regression through the origin — no intercept estimated.`);
      lines.push(`reg ${yVar} ${xList}${olsOpt}`);
      lines.push(`estimates store m_ols`);
      break;
    }

    case "WLS":
      if (!weightCol) {
        lines.push(`* WARNING: no weight column supplied; falling back to OLS`);
        lines.push(`reg ${yVar} ${xList}${opt}`);
      } else {
        lines.push(`* Weighted Least Squares (analytic weights: ${weightCol})`);
        lines.push(`reg ${yVar} ${xList} [aw=${weightCol}]${opt}`);
      }
      lines.push(`estimates store m_wls`);
      break;

    case "FE": {
      // N-way FE: spec.feCols (Task 3-5) generalizes absorption beyond entity-only.
      // Fallback preserves the pre-existing entity-only default byte-for-byte.
      const feColsFE = feCols?.length ? feCols : [entityCol].filter(Boolean);
      if (feColsFE.length <= 2) {
        lines.push(`* Fixed Effects (within)`);
        lines.push(`xtset ${entityCol} ${timeCol}`);
        lines.push(`xtreg ${yVar} ${xList}, fe${pOpt}`);
        lines.push(`estimates store m_fe`);
      } else {
        lines.push(`* Fixed Effects (within) — N-way absorption via reghdfe`);
        lines.push(`* ssc install reghdfe  // if not installed — required for 3+-way FE absorption`);
        lines.push(`* NOTE: clusters on the first FE column (entityCol) by convention, matching the`);
        lines.push(`* existing TWFE reghdfe export — does not yet thread the model's actual seType/`);
        lines.push(`* clusterVar selection through this fallback path.`);
        lines.push(`reghdfe ${yVar} ${xList}, absorb(${feColsFE.join(" ")})${pOptHdfe}`);
        lines.push(`estimates store m_fe`);
      }
      break;
    }

    case "FD":
      lines.push(`* First Differences`);
      lines.push(`xtset ${entityCol} ${timeCol}`);
      lines.push(`xtreg ${yVar} ${xList}, fd${pOpt}`);
      lines.push(`estimates store m_fd`);
      break;

    case "2SLS": {
      const endog = xVars.join(" ");
      const instr = zVars.join(" ");
      const exog  = wVars.join(" ");
      lines.push(`* Two-Stage Least Squares / IV`);
      // ivregress does not accept vce(hc2)/vce(hc3) — fall back to robust (HC1)
      // and say so, rather than emitting a line that errors out in Stata.
      if (seLower === "hc2" || seLower === "hc3") {
        lines.push(`* NOTE: Litux used ${seLower.toUpperCase()} SE. ivregress has no hc2/hc3 option;`);
        lines.push(`* this reports robust (HC1) SE instead — expect a small SE difference.`);
      }
      lines.push(`ivregress 2sls ${yVar} ${exog ? `(${endog} = ${instr}) ${exog}` : `(${endog} = ${instr})`}${optNoHC23}`);
      lines.push(`estimates store m_2sls`);
      lines.push(`* First-stage F-statistic`);
      lines.push(`estat firststage`);
      break;
    }

    case "DiD": {
      const extra = wVars.length ? ` ${wVars.join(" ")}` : "";
      lines.push(`* Difference-in-Differences (2×2)`);
      lines.push(`gen did = ${postVar} * ${treatVar}`);
      lines.push(`reg ${yVar} ${postVar} ${treatVar} did${extra}${opt}`);
      lines.push(`estimates store m_did`);
      break;
    }

    case "TWFE": {
      const extra = wVars.length ? ` ${wVars.join(" ")}` : "";
      // N-way FE: spec.feCols (Task 3-5) generalizes absorption beyond entity+time.
      // Fallback preserves the pre-existing entity+time default byte-for-byte.
      const feColsTWFE = feCols?.length ? feCols : [entityCol, timeCol].filter(Boolean);
      lines.push(`* Two-Way Fixed Effects DiD`);
      lines.push(`xtset ${entityCol} ${timeCol}`);
      lines.push(`reghdfe ${yVar} ${treatVar}${extra}, absorb(${feColsTWFE.join(" ")})${pOptHdfe}`);
      lines.push(`* If reghdfe not installed: ssc install reghdfe`);
      lines.push(`estimates store m_twfe`);
      break;
    }

    case "RDD": {
      const kernelOpt = kernel === "uniform" ? "nw(1)" : kernel === "epanechnikov" ? "kernel(epanechnikov)" : "kernel(triangular)";
      const extra = wVars.length ? ` ${wVars.join(" ")}` : "";
      lines.push(`* Sharp RDD — local linear regression`);
      lines.push(`* If rdrobust not installed: ssc install rdrobust`);
      lines.push(`rdrobust ${yVar} ${runningVar}, c(${cutoff ?? 0}) h(${bandwidth ?? "# set bandwidth"}) ${kernelOpt}${extra ? ` covs(${wVars.join(" ")})` : ""}`);
      lines.push(`* Manual approach (WLS local linear):`);
      lines.push(`gen _above = (${runningVar} >= ${cutoff ?? 0})`);
      lines.push(`gen _run_c = ${runningVar} - ${cutoff ?? 0}`);
      lines.push(`gen _above_run = _above * _run_c`);
      lines.push(`* Triangular kernel weights:`);
      lines.push(`gen _w = max(0, 1 - abs(_run_c) / ${bandwidth ?? 1}) if abs(_run_c) <= ${bandwidth ?? 1}`);
      lines.push(`reg ${yVar} _above _run_c _above_run${extra} [aw=_w]${opt}`);
      lines.push(`drop _above _run_c _above_run _w`);
      break;
    }

    case "Logit":
      lines.push(`logit ${yVar} ${xList}`);
      lines.push(`estimates store m_logit`);
      lines.push(`* Marginal effects at the mean`);
      lines.push(`margins, dydx(*) atmeans`);
      break;

    case "Probit":
      lines.push(`probit ${yVar} ${xList}`);
      lines.push(`estimates store m_probit`);
      lines.push(`* Marginal effects at the mean`);
      lines.push(`margins, dydx(*) atmeans`);
      break;

    case "LSDV": {
      // N-way FE: spec.feCols (Task 3-5) generalizes absorption beyond entity(+time).
      // Fallback preserves the pre-existing entity(+time) default byte-for-byte.
      const feColsLSDV = feCols?.length ? feCols : [entityCol, timeCol].filter(Boolean);
      if (feColsLSDV.length <= 2) {
        lines.push(`* Panel LSDV — recover entity fixed effects explicitly`);
        lines.push(`xtset ${entityCol} ${timeCol}`);
        lines.push(`* Within (FE) — numerically equivalent to LSDV`);
        lines.push(`xtreg ${yVar} ${xList}, fe${pOpt}`);
        lines.push(`estimates store m_lsdv`);
        lines.push(``);
        lines.push(`* Recover alpha_i (entity fixed effects) via areg`);
        lines.push(`areg ${yVar} ${xList}, absorb(${entityCol})${pOpt}`);
        lines.push(`predict _alpha_i, dresiduals`);
        lines.push(`label var _alpha_i "Entity fixed effect (LSDV alpha_i)"`);
        lines.push(`* List unique entity FEs`);
        lines.push(`bysort ${entityCol}: keep if _n == 1`);
        lines.push(`list ${entityCol} _alpha_i, sep(0)`);
      } else {
        lines.push(`* Panel LSDV — N-way absorption via reghdfe`);
        lines.push(`* ssc install reghdfe  // if not installed — required for 3+-way FE absorption`);
        lines.push(`* Single call: savefe (var=newname) syntax both stores estimates and materializes`);
        lines.push(`* alpha_i per FE dimension — no need to run reghdfe twice`);
        lines.push(`reghdfe ${yVar} ${xList}, absorb(${feColsLSDV.map(c => `${c}=fe_${c}`).join(" ")})${pOptHdfe}`);
        lines.push(`estimates store m_lsdv`);
        lines.push(``);
        lines.push(`* Recover alpha_i per FE dimension`);
        feColsLSDV.forEach((c) => {
          lines.push(`label var fe_${c} "${c} fixed effect (LSDV alpha)"`);
        });
        lines.push(`* List unique entity FEs`);
        lines.push(`bysort ${entityCol}: keep if _n == 1`);
        lines.push(`list ${entityCol} ${feColsLSDV.map(c => `fe_${c}`).join(" ")}, sep(0)`);
      }
      break;
    }

    case "FuzzyRDD": {
      const kernelOpt = kernel === "uniform" ? "nw(1)"
                      : kernel === "epanechnikov" ? "kernel(epanechnikov)"
                      : "kernel(triangular)";
      const dVar  = treatVar ?? "D";
      const extra = wVars.length ? ` covs(${wVars.join(" ")})` : "";
      lines.push(`* Fuzzy RDD via rdrobust`);
      lines.push(`* If not installed: ssc install rdrobust`);
      lines.push(`rdrobust ${yVar} ${runningVar}, fuzzy(${dVar}) c(${cutoff ?? 0}) h(${bandwidth ?? "# set bandwidth"}) ${kernelOpt}${extra}`);
      lines.push(`* First-stage jump in take-up probability`);
      lines.push(`gen _Z = (${runningVar} >= ${cutoff ?? 0})`);
      lines.push(`gen _run_c = ${runningVar} - ${cutoff ?? 0}`);
      lines.push(`ivregress 2sls ${yVar} _run_c (${dVar} = _Z)${optNoHC23}`);
      lines.push(`drop _Z _run_c`);
      break;
    }

    case "SpatialRDD": {
      const kernelOpt = kernel === "uniform"      ? "nw(1)"
                      : kernel === "epanechnikov" ? "kernel(epanechnikov)"
                      : "kernel(triangular)";
      const distV  = distCol      ?? runningVar ?? "dist";
      const trtV   = treatmentCol ?? treatVar   ?? "treatment";
      const h      = bandwidth ? Number(bandwidth).toFixed(6) : null;
      const extra  = wVars.length ? ` covs(${wVars.join(" ")})` : "";
      lines.push(`* Spatial RD (Keele & Titiunik 2015)`);
      lines.push(`* Build signed running variable: positive on treated side, cutoff = 0`);
      lines.push(`gen _signed_dist = (2 * ${trtV} - 1) * abs(${distV})`);
      lines.push(`* If rdrobust not installed: ssc install rdrobust`);
      if (h) {
        lines.push(`rdrobust ${yVar} _signed_dist, c(0) h(${h}) ${kernelOpt}${extra}`);
      } else {
        lines.push(`rdrobust ${yVar} _signed_dist, c(0) ${kernelOpt}${extra}`);
      }
      lines.push(`* Manual WLS approach (triangular kernel):`);
      lines.push(`gen _above = (_signed_dist >= 0)`);
      lines.push(`gen _above_run = _above * _signed_dist`);
      const bwStata = h ?? "# replace with bandwidth";
      lines.push(`gen _w = max(0, 1 - abs(_signed_dist) / ${bwStata}) if abs(_signed_dist) <= ${bwStata}`);
      lines.push(`reg ${yVar} _above _signed_dist _above_run${wVars.length ? " " + wVars.join(" ") : ""} [aw=_w]${opt}`);
      lines.push(`drop _signed_dist _above _above_run _w`);
      break;
    }

    case "EventStudy": {
      const extra = wVars.length ? ` ${wVars.join(" ")}` : "";
      // N-way FE: spec.feCols (Task 3-5) generalizes absorption beyond entity+time.
      // reghdfe natively absorbs any number of dimensions, so no <=2-dim branching is
      // needed here (unlike PanelOLS/xtreg in the Python/Stata FE and LSDV cases).
      // Fallback preserves the pre-existing entity+time default byte-for-byte.
      const feColsES = feCols?.length ? feCols : [entityCol, timeCol].filter(Boolean);
      lines.push(`* Event Study — relative-time dummies`);
      lines.push(`* Replace treat_time with the variable holding each unit's treatment period`);
      lines.push(`xtset ${entityCol} ${timeCol}`);
      lines.push(`gen rel_time = ${timeCol} - treat_time`);
      lines.push(`* Estimate with unit + time FE, ref = -1`);
      lines.push(`* If reghdfe not installed: ssc install reghdfe`);
      lines.push(`reghdfe ${yVar} ib(-1).rel_time${extra}, absorb(${feColsES.join(" ")})${pOptHdfe}`);
      lines.push(`estimates store m_eventstudy`);
      lines.push(`* Plot coefficients`);
      lines.push(`coefplot m_eventstudy, keep(*rel_time*) vertical yline(0) xline(# replace with ref period index)`);
      break;
    }

    case "SunAbraham": {
      const fes = (feCols && feCols.length ? feCols : [entityCol ?? "unit", periodCol ?? timeCol ?? "period"]);
      const coh = cohortCol ?? "cohort";
      const per = periodCol ?? timeCol ?? "period";
      const cov = (xVars ?? []).length ? ` ${xVars.join(" ")}` : "";
      const ref = refPeriod != null ? Number(refPeriod) : -1;
      lines.push(`* ── Sun & Abraham (2021) interaction-weighted event study over Poisson PPML ──`);
      lines.push(`* Control convention: ${controlMode === "never" ? "never-treated only" : "never- + not-yet-treated (auto)"}`);
      lines.push(`* Reference relative period: ${ref}`);
      lines.push(`* eventstudyinteract (Sun & Abraham's own Stata package) over a Poisson link:`);
      lines.push(`* If not installed: ssc install eventstudyinteract`);
      lines.push(`* It also requires: ssc install avar`);
      lines.push(`xtset ${fes[0]} ${per}`);
      lines.push(`* Build relative-period dummies (rel = period - cohort); ref = ${ref} omitted`);
      lines.push(`gen rel_period = ${per} - ${coh}`);
      lines.push(`* never-treated units (missing cohort) act as the control group`);
      lines.push(`gen never_treated = missing(${coh})`);
      lines.push(`* Generate relative-time indicators g_* for each value of rel_period (excl. ${ref})`);
      lines.push(`* then run:`);
      lines.push(`* eventstudyinteract ${yVar}${cov} g_*, cohort(${coh}) control_cohort(never_treated) absorb(${fes.join(" ")}) vce(cluster ${fes[0]})`);
      lines.push(`*`);
      lines.push(`* NOTE: eventstudyinteract is built for linear (reghdfe) FE. For a Poisson/PPML`);
      lines.push(`* version (as estimated here), prefer R fixest::fepois(y ~ sunab(cohort, period) | fe)`);
      lines.push(`* or Python pyfixest. Stata has no native PPML Sun-Abraham aggregator.`);
      break;
    }

    case "SyntheticControl": {
      const ec = entityCol ?? "unit";
      const tc = timeCol   ?? "time";
      const tu = treatedUnit ?? "TreatedUnit";
      const tt = treatTime != null ? Number(treatTime) : "TREAT_TIME";
      const predsStr = (xVars ?? []).length
        ? (xVars ?? []).join(" ")
        : `${yVar}  /* no explicit predictors — outcome mean used */`;
      lines.push(`* ── Synthetic Control (synth package) ──────────────────────────────`);
      lines.push(`* Install: ssc install synth, replace`);
      lines.push(`tsset ${ec} ${tc}`);
      lines.push(``);
      lines.push(`* synth requires balanced panel — verify before running`);
      lines.push(`synth ${yVar} ${predsStr}, ///`);
      lines.push(`    trunit("${tu}") trperiod(${tt}) ///`);
      lines.push(`    xperiod(#pre_start(#)${tt - 1}) ///`);
      lines.push(`    nested allopt figure`);
      lines.push(``);
      lines.push(`* Donor weights are stored in e(W_weights)`);
      lines.push(`mat weights = e(W_weights)`);
      lines.push(`mat list weights`);
      lines.push(``);
      lines.push(`* MSPE ratio (post/pre) for inference`);
      lines.push(`* Use synth_runner for automated placebo inference:`);
      lines.push(`* ssc install synth_runner, replace`);
      lines.push(`* synth_runner ${yVar} ${predsStr}, trunit("${tu}") trperiod(${tt}) gen_vars`);
      break;
    }

    case "GMM": {
      const endog  = wVars.join(" ");
      const exog   = xVars.join(" ");
      const instrs = [...xVars, ...zVars].join(" ");
      lines.push(`* Two-Step Efficient GMM`);
      lines.push(`* Structural: ${yVar} ~ ${exog || "(no exog)"} + (${endog || "endog"}) endogenous`);
      lines.push(`* Instruments: ${instrs || "(instruments)"}`);
      if (wVars.length) {
        lines.push(`ivregress gmm ${yVar}${exog ? ` ${exog}` : ""} (${endog} = ${zVars.join(" ")}), wmatrix(${seLower === "classical" ? "unadjusted" : "robust"})`);
      } else {
        lines.push(`* No endogenous variables specified — using 2SLS form`);
        lines.push(`ivregress gmm ${yVar} ${exog}${optNoHC23}`);
      }
      lines.push(`estat overid  /* Sargan-Hansen J-test — available after gmm */`);
      break;
    }

    case "LIML": {
      const endog  = wVars.join(" ");
      const exog   = xVars.join(" ");
      lines.push(`* Limited Information Maximum Likelihood (LIML)`);
      if (wVars.length) {
        lines.push(`ivregress liml ${yVar}${exog ? ` ${exog}` : ""} (${endog} = ${zVars.join(" ")})${optNoHC23}`);
      } else {
        lines.push(`* No endogenous variables specified — defaulting to OLS`);
        lines.push(`reg ${yVar} ${exog}${opt}`);
      }
      lines.push(`estat firststage  /* first-stage F-statistics */`);
      break;
    }

    case "Poisson": {
      lines.push(`* Poisson regression (count GLM, log link)`);
      lines.push(`poisson ${yVar} ${xList}${opt ? opt : ", vce(robust)"} irr`);
      lines.push(`* irr option reports Incidence Rate Ratios (exp(beta))`);
      lines.push(`estimates store m_poisson`);
      lines.push(`* Overdispersion check: deviance / df and Pearson / df`);
      lines.push(`estat gof`);
      break;
    }

    case "PoissonFE": {
      const fes  = (feCols && feCols.length ? feCols : [entityCol ?? "entity"]);
      const cov  = xVars.join(" ");
      lines.push(`* Poisson FE (PPML with ${fes.length}-way fixed effects)`);
      lines.push(`* ppmlhdfe recommended — if not installed: ssc install ppmlhdfe`);
      lines.push(`ppmlhdfe ${yVar}${cov ? ` ${cov}` : ""}, absorb(${fes.join(" ")})${pOpt || " vce(cluster " + fes[0] + ")"}`);
      lines.push(`* Incidence Rate Ratios (manual — Stata PPML reports log-IRR by default):`);
      lines.push(`* nlcom (exp(_b[${xVars[0] ?? "x"}]))`);
      break;
    }

    case "NegBinFE": {
      const fes = (feCols && feCols.length ? feCols : [entityCol ?? "entity"]);
      const cov = xVars.join(" ");
      const feTerms = fes.map(f => `i.${f}`).join(" ");
      const offsetOpt = offsetCol ? " offset(__nb_offset)" : "";
      lines.push(`* Negative Binomial FE (NB2 with fixed-effect indicators)`);
      if (offsetCol) {
        lines.push(`gen double __nb_offset = log(${offsetCol})`);
      }
      lines.push(`nbreg ${yVar}${cov ? ` ${cov}` : ""}${feTerms ? ` ${feTerms}` : ""}, vce(cluster ${fes[0]})${offsetOpt} irr`);
      lines.push(`estimates store m_negbin_fe`);
      break;
    }

    case "McCrary": {
      const rv = runningVar ?? "running";
      const c0 = cutoff ?? 0;
      lines.push(`* McCrary / Cattaneo-Jansson-Ma density test`);
      lines.push(`* If rddensity not installed: ssc install rddensity`);
      lines.push(`rddensity ${rv}, c(${c0})`);
      lines.push(`rddensity ${rv}, c(${c0}) plot`);
      break;
    }

    case "CallawayCS": {
      // Callaway-Sant'Anna (2021) staggered DiD via csdid package
      const csY = yVar;
      const { xVars: csXVars = [], csCompGroup = "nevertreated",
              csEstMethod = "dr", csAnticipation = 0 } = model;

      // Map est_method to Stata csdid method names
      const methodMap = { dr: "dripw", reg: "drimp", ipw: "ipw" };
      const csdidMethod = methodMap[csEstMethod] || "dripw";

      // Build covariates flag: if xVars non-empty, add them after csdid Y
      const xvarsLine = (csXVars && csXVars.length && !csXVars.includes("~1"))
        ? `* Add covariates\ncsdid ${csY} ${csXVars.map(stVar).join(" ")}`
        : `csdid ${csY}`;

      // Build notyet flag
      const notyet_flag = csCompGroup === "notyettreated" ? " notyet" : "";

      // Build pre flag for anticipation
      const pre_flag = csAnticipation > 0 ? ` pre(${csAnticipation})` : "";

      lines.push(`* Callaway-Sant'Anna (2021) Staggered DiD`);
      lines.push(`* Install: net install csdid, from(https://friosavila.github.io/stpackages)`);
      lines.push(``);
      lines.push(xvarsLine);
      lines.push(`  ivar(${entityCol}) time(${timeCol}) gvar(${treatVar})${notyet_flag} ///`);
      lines.push(`  method(${csdidMethod})${pre_flag}`);
      lines.push(``);
      lines.push(`* Aggregations`);
      lines.push(`estat simple`);
      lines.push(`estat dynamic`);
      lines.push(`estat group`);
      lines.push(`estat calendar`);
      break;
    }

    default:
      lines.push(`* Model type "${type}" — add estimation command here`);
  }

  return lines;
}

// ─── MULTI-MODEL HELPERS ─────────────────────��────────────────────────────────

function detectMapPatternStata(configs) {
  if (configs.length < 2) return "separate";
  const allHaveMeta = configs.every(c => Array.isArray(c.subsetFilters));
  if (!allHaveMeta) return "separate";
  const first = configs[0].model;
  const xKey  = arr => JSON.stringify([...(arr ?? [])].sort());
  return configs.every(c =>
    c.model.type === first.type &&
    c.model.yVar === first.yVar &&
    xKey(c.model.xVars) === xKey(first.xVars)
  ) ? "map" : "separate";
}

function subsetFiltersToStata(filters) {
  if (!filters?.length) return null;
  return filters.map(f => {
    const val = isNaN(Number(f.val)) ? `"${f.val}"` : f.val;
    return `${f.col} ${f.op} ${val}`;
  }).join(" & ");
}

// Safe Stata local name: lowercase, spaces → underscores, strip special chars
function stataLocalName(label) {
  return label.toLowerCase().replace(/[^a-z0-9_]/g, "_").replace(/^[0-9]/, "_").slice(0, 28);
}

// ─── MULTI-MODEL EXPORT ────────────────────────────────────────────────────────
// configs: Array of { model: ModelConfig, label: string, subsetName?, subsetFilters? }
export function generateMultiModelStataScript(configs = [], dataDictionary = null, opts = {}) {
  if (!configs.length) return "* No models provided.";

  const filename     = opts.filename ?? "dataset.csv";
  const pipeline     = opts.pipeline ?? [];
  const dataLoadOpts = opts.dataLoadOpts ?? null;
  const stataFile    = filename.replace(/\\/g, "/");
  const ts = new Date().toISOString().slice(0, 10);
  const lines = [];

  lines.push(`* ${"─".repeat(71)}`);
  lines.push(`* Multi-model replication do-file — generated by Litux`);
  lines.push(`* Models: ${configs.map((c, i) => `(${i+1}) ${c.label ?? c.model?.type}`).join(", ")}`);
  lines.push(`* Generated: ${ts}`);
  lines.push(`* ${"─".repeat(71)}`);
  lines.push("");
  lines.push("clear all");
  lines.push("set more off");
  lines.push("version 17");
  lines.push("");

  lines.push(`* ── Load data ────────────────────────────────────────────────────────────`);
  lines.push(buildStataLoadLine(stataFile, dataLoadOpts));
  lines.push("");

  if (pipeline.length) {
    lines.push(`* ── Data pipeline ────────────────────────────────────────────────────────`);
    pipeline.forEach(step => {
      const out = isGridEditStep(step) ? transpileStep(step, opts.allDatasets ?? {}) : toStata(step, "df");
      if (Array.isArray(out)) out.forEach(l => lines.push(l));
      else if (out) lines.push(out);
    });
    lines.push("");
  }

  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push(`* ── Variable definitions ─────────────────────────────────────────────────`);
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => {
      const clean = String(v).replace(/`/g, "'").replace(/\n/g, " ").slice(0, 120);
      lines.push(`* ${k}: ${clean}`);
    });
    lines.push("");
  }

  const pattern = detectMapPatternStata(configs);

  if (pattern === "map") {
    // ── Same spec, different subsets → preserve/restore per subset ────────────
    lines.push(`* ── Subset estimation (preserve/restore) ─────────────────────────────────`);
    const estoreNames = [];
    const { type = "OLS", yVar = "y", xVars = [], wVars = [], zVars = [],
            entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel,
            treatedUnit, treatTime, feCols, cohortCol, periodCol, controlMode, refPeriod,
            interactionTerms: ixm = [], xVarsRaw: xrm = null, wVarsRaw: wrm = null,
            seType: seM = "classical", clusterVar: clM = null, clusterVar2: cl2M = null, noIntercept: niM = false } = configs[0].model ?? {};
    const allX = [...xVars, ...wVars];

    configs.forEach((c) => {
      const estName = stataLocalName(c.subsetName ?? c.label);
      estoreNames.push({ name: estName, label: c.subsetName ?? c.label });
      const filterExpr = subsetFiltersToStata(c.subsetFilters);
      lines.push(`preserve`);
      if (filterExpr) lines.push(`  keep if ${filterExpr}`);
      else            lines.push(`  * Full sample — no filter`);
      const modelLines = transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, treatedUnit, treatTime, feCols: feCols ?? null, cohortCol: cohortCol ?? null, periodCol: periodCol ?? null, controlMode: controlMode ?? null, refPeriod: refPeriod ?? null, interactionTerms: ixm, xVarsRaw: xrm, wVarsRaw: wrm, seType: seM, clusterVar: clM, clusterVar2: cl2M, noIntercept: niM });
      let hasStore = false;
      modelLines.forEach(l => {
        const ov = l.replace(/^estimates store \S+/, `estimates store ${estName}`);
        if (ov !== l) hasStore = true;
        lines.push(`  ${ov}`);
      });
      if (!hasStore) lines.push(`  estimates store ${estName}`);
      lines.push(`restore`);
      lines.push(``);
    });

    lines.push(`* ── Joint table (esttab) ─────────────────────────────────────────────────`);
    lines.push(`* If esttab not installed: ssc install estout`);
    const mList    = estoreNames.map(e => e.name).join(" ");
    const mlabels  = estoreNames.map(e => `"${e.label}"`).join(" ");
    lines.push(`esttab ${mList} using comparison_results.rtf, ///`);
    lines.push(`  mtitles(${mlabels}) ///`);
    lines.push(`  star(* 0.1 ** 0.05 *** 0.01) ///`);
    lines.push(`  se r2 N replace`);
    lines.push("");
  } else {
    // ── Different specs → one block per model ────────────────────────────────
    lines.push(`* ── Estimation ───────────────────────────────────────────────────────────`);
    const estoreNames = [];
    configs.forEach((c, i) => {
      const estName = `m_${i + 1}`;
      estoreNames.push({ name: estName, label: c.label ?? c.model?.type ?? `Model ${i+1}` });
      const { type = "OLS", yVar = "y", xVars = [], wVars = [], zVars = [],
              entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel,
              treatedUnit, treatTime, feCols, cohortCol, periodCol, controlMode, refPeriod,
              interactionTerms: ixc = [], xVarsRaw: xrc = null, wVarsRaw: wrc = null,
              seType: seC = "classical", clusterVar: clC = null, clusterVar2: cl2C = null, noIntercept: niC = false } = c.model ?? {};
      const allX = [...xVars, ...wVars];
      lines.push(`* Model ${i+1}: ${c.label ?? type}`);
      const modelLines = transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, treatedUnit, treatTime, feCols: feCols ?? null, cohortCol: cohortCol ?? null, periodCol: periodCol ?? null, controlMode: controlMode ?? null, refPeriod: refPeriod ?? null, interactionTerms: ixc, xVarsRaw: xrc, wVarsRaw: wrc, seType: seC, clusterVar: clC, clusterVar2: cl2C, noIntercept: niC });
      let hasStore = false;
      modelLines.forEach(l => {
        const overridden = l.replace(/^estimates store \S+/, `estimates store ${estName}`);
        if (overridden !== l) hasStore = true;
        lines.push(overridden);
      });
      if (!hasStore) lines.push(`estimates store ${estName}`);
      lines.push("");
    });

    lines.push(`* ── Joint table (esttab) ─────────────────────────────────────────────────`);
    lines.push(`* If esttab not installed: ssc install estout`);
    const mList   = estoreNames.map(e => e.name).join(" ");
    const mlabels = estoreNames.map(e => `"${e.label}"`).join(" ");
    lines.push(`esttab ${mList} using comparison_results.rtf, ///`);
    lines.push(`  mtitles(${mlabels}) ///`);
    lines.push(`  star(* 0.1 ** 0.05 *** 0.01) ///`);
    lines.push(`  se r2 N replace`);
    lines.push("");
  }

  return lines.join("\n");
}

// ─── SUBSET REPLICATION SCRIPT (H6/H10) ───────────────────────────────────────
// config: { filename, pipeline, perSubsetSteps, subsets, model, dataDictionary }
export function generateSubsetStataScript({ filename = "dataset.csv", pipeline = [], perSubsetSteps = [], subsets = [], model = {}, dataDictionary = null, dataLoadOpts = null } = {}) {
  const ts   = new Date().toISOString().slice(0, 10);
  const stem = filename.replace(/\.[^.]+$/, "");
  const lines = [];

  function filterCond(filters) {
    if (!filters?.length) return null;
    return filters.map(f => {
      const col  = f.col.replace(/[^a-zA-Z0-9_]/g, "_");
      const isNum = f.val !== "" && !isNaN(Number(f.val));
      const val  = isNum ? f.val : `"${f.val}"`;
      return `${col} ${f.op} ${val}`;
    }).join(" & ");
  }

  lines.push(`* ${"─".repeat(71)}`);
  lines.push(`* Multi-subset replication do-file — generated by Litux`);
  lines.push(`* Dataset: ${filename}  |  Model: ${model.type ?? "OLS"}  |  ${ts}`);
  lines.push(`* ${"─".repeat(71)}`);
  lines.push("");
  lines.push("clear all");
  lines.push("set more off");
  lines.push("version 17");
  lines.push("");

  lines.push(`* ── Load data ────────────────────────────────────────────────────────────`);
  lines.push(buildStataLoadLine(filename.replace(/\\/g, "/"), dataLoadOpts));
  lines.push("");

  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push(`* ── Variable definitions ─────────────────────────────────────────────────`);
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => {
      lines.push(`* ${k}: ${String(v).replace(/`/g, "'").replace(/\n/g, " ").slice(0, 120)}`);
    });
    lines.push("");
  }

  if (pipeline.length) {
    lines.push(`* ── Shared pipeline ─────────────────────────────────────────────────────`);
    pipeline.forEach(step => { const c = transpileStep(step); if (c) lines.push(c); });
    lines.push("");
  }

  const { type = "OLS", yVar = "y", xVars = [], wVars = [] } = model;
  const allX = [...(xVars ?? []), ...(wVars ?? [])];
  const estoreNames = [];

  // ── Full sample
  lines.push(`* ── Full sample ──────────────────────────────────────────────────────────`);
  const fullName = `s_full`;
  estoreNames.push({ name: fullName, label: "Full sample" });
  transpileModel({ ...model, allX }).forEach(l => lines.push(l));
  lines.push(`estimates store ${fullName}`);
  lines.push("");

  // ── Named subsets (preserve / restore pattern)
  subsets.forEach((s, i) => {
    const safeName = `s_${i + 1}`;
    estoreNames.push({ name: safeName, label: s.name });
    const cond = filterCond(s.filters);
    lines.push(`* ── Subset: ${s.name} ──────────────────────────────────────────────────`);
    lines.push(`preserve`);
    if (cond) lines.push(`keep if ${cond}`);
    if (perSubsetSteps.length) {
      lines.push(`* Per-subset pipeline`);
      perSubsetSteps.forEach(step => { const c = transpileStep(step); if (c) lines.push(c); });
    }
    transpileModel({ ...model, allX }).forEach(l => lines.push(l));
    lines.push(`estimates store ${safeName}`);
    lines.push(`restore`);
    lines.push("");
  });

  lines.push(`* ── Comparison table (esttab) ────────────────────────────────────────────`);
  lines.push(`* If not installed: ssc install estout`);
  const mList    = estoreNames.map(e => e.name).join(" ");
  const mlabels  = estoreNames.map(e => `"${e.label}"`).join(" ");
  lines.push(`esttab ${mList} using "${stem}_subsets.rtf", ///`);
  lines.push(`  mtitles(${mlabels}) ///`);
  lines.push(`  star(* 0.1 ** 0.05 *** 0.01) ///`);
  lines.push(`  se r2 N replace`);
  lines.push("");

  return lines.join("\n");
}
