// ─── LITUX · services/export/stataScript.js ────────────────────────────
// Generates a self-contained Stata .do replication file.
//
// Config shape (same as rScript.js / pythonScript.js):
//   { filename, pipeline, model, auditTrail, dataDictionary }
//
// model shape:
//   { type, yVar, xVars, wVars, zVars, entityCol, timeCol,
//     postVar, treatVar, runningVar, cutoff, bandwidth, kernel }

import { toStata, jsExprToStata, stataRightLoad } from "../../pipeline/stepTranslators.js";
import { buildStataLoadLine } from "./loadLine.js";

export function generateStataScript(config = {}) {
  const {
    filename       = "dataset.csv",
    pipeline       = [],
    model          = {},
    dataDictionary = null,
    dataLoadOpts   = null,
    allDatasets    = {},
  } = config;

  const {
    type       = "OLS",
    yVar       = "y",
    xVars      = [],
    wVars      = [],
    zVars      = [],
    entityCol  = null,
    timeCol    = null,
    postVar    = null,
    treatVar   = null,
    runningVar    = null,
    cutoff        = null,
    bandwidth     = null,
    kernel        = "triangular",
    distCol       = null,
    treatmentCol  = null,
  } = model;

  const stem     = filename.replace(/\.[^.]+$/, "");
  const stataFile = filename.replace(/\\/g, "/");  // forward slashes — safe in Stata
  const allX = [...(xVars ?? []), ...(wVars ?? [])];

  const lines = [];

  // ── Header ──────────────────────────────────────────────────────────────────
  lines.push(`* ${"─".repeat(71)}`);
  lines.push(`* Replication do-file — ${stem}`);
  lines.push(`* Generated by Litux · ${new Date().toISOString().slice(0, 10)}`);
  lines.push(`* Estimator: ${type}`);
  lines.push(`* ${"─".repeat(71)}`);
  lines.push("");
  lines.push("clear all");
  lines.push("set more off");
  lines.push(`version 17`);
  lines.push("");

  // ── Load data ───────────────────────────────────────────────────────────────
  lines.push(`* ── Load data ────────────────────────────────────────────────────────────`);
  lines.push(buildStataLoadLine(stataFile, dataLoadOpts));
  lines.push("");

  // ── Data dictionary ─────────────────────────────────────────────────────────
  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push(`* ── Variable definitions ─────────────────────────────────────────────────`);
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => {
      const clean = String(v).replace(/`/g, "'").replace(/\n/g, " ").slice(0, 120);
      lines.push(`* ${k}: ${clean}`);
    });
    lines.push("");
  }

  // ── Pipeline steps ──────────────────────────────────────────────────────────
  if (pipeline.length) {
    lines.push(`* ── Data pipeline ────────────────────────────────────────────────────────`);
    pipeline.forEach(step => {
      const code = transpileStep(step, allDatasets);
      if (code) lines.push(code);
    });
    lines.push("");
  }

  // ── Model ───────────────────────────────────────────────────────────────────
  lines.push(`* ── Estimation ───────────────────────────────────────────────────────────`);
  lines.push(...transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, factorVars: model.factorVars ?? [] }));
  lines.push("");

  return lines.join("\n");
}

// ─── STEP TRANSPILER ─────────────────────────────────────────────────────────
function transpileStep(step, allDatasets = {}) {
  const { type, params = {} } = step;
  switch (type) {
    case "rename":
      return `rename ${params.from} ${params.to}`;
    case "drop":
      return `drop ${(params.cols ?? []).join(" ")}`;
    case "filter": {
      const { col, op, val } = params;
      const v = typeof val === "string" ? `"${val}"` : val;
      return `keep if ${col} ${op ?? "=="} ${v}`;
    }
    case "drop_na":
      if (params.cols?.length) return `drop if missing(${params.cols.join(", ")})`;
      return `drop if missing(*)`;
    case "fill_na": {
      const { col, mode, value } = params;
      if (mode === "mean")   return `egen _tmp = mean(${col})\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
      if (mode === "median") return `egen _tmp = median(${col})\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
      if (mode === "mode") {
        return [
          `egen _tmp_grp = group(${col})`,
          `* Note: mode fill — manually select most frequent value`,
          `replace ${col} = .  // replace with computed mode`,
          `drop _tmp_grp`,
        ].join("\n");
      }
      if (mode === "ffill") return `* forward fill local obs = _N forval i = 2/\`obs' {
     if missing(${col}[\`i']) replace ${col} = ${col}[\`i'-1] in \`i'
}
`;
      const v = typeof value === "string" ? `"${value}"` : value ?? 0;
      return `replace ${col} = ${v} if missing(${col})`;
    }
    case "fill_na_grouped": {
      const { col, groupCol, mode } = params;
      if (mode === "mean")   return `bysort ${groupCol}: egen _tmp = mean(${col})\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
      if (mode === "median") return `bysort ${groupCol}: egen _tmp = median(${col})\nreplace ${col} = _tmp if missing(${col})\ndrop _tmp`;
      return `* fill_na_grouped (${mode}) by ${groupCol}: add custom logic`;
    }
    case "type_cast": {
      const { col, targetType } = params;
      if (targetType === "numeric") return `destring ${col}, replace force`;
      if (targetType === "string")  return `tostring ${col}, replace`;
      return `* type_cast ${col} to ${targetType}`;
    }
    case "log":
      return `gen log_${params.col} = log(${params.col})`;
    case "sq":
      return `gen ${params.col}_sq = ${params.col}^2`;
    case "std":
      return `egen _mn = mean(${params.col})\negen _sd = sd(${params.col})\ngen ${params.col}_z = (${params.col} - _mn) / _sd\ndrop _mn _sd`;
    case "winz": {
      const { col, p1, p99 } = params;
      if (p1 != null && p99 != null) {
        return `replace ${col} = max(${p1}, min(${p99}, ${col}))`;
      }
      return `winsor2 ${col}, cuts(1 99) replace`;
    }
    case "dummy":
      return `tabulate ${params.col}, generate(${params.col}_)`;
    case "lag":
      if (params.entityCol) {
        return `xtset ${params.entityCol} ${params.timeCol ?? "_t"}\ngen ${params.col}_lag${params.n ?? 1} = L${params.n ?? 1}.${params.col}`;
      }
      return `gen ${params.col}_lag${params.n ?? 1} = L${params.n ?? 1}.${params.col}`;
    case "lead":
      if (params.entityCol) {
        return `xtset ${params.entityCol} ${params.timeCol ?? "_t"}\ngen ${params.col}_lead${params.n ?? 1} = F${params.n ?? 1}.${params.col}`;
      }
      return `gen ${params.col}_lead${params.n ?? 1} = F${params.n ?? 1}.${params.col}`;
    case "diff":
      if (params.entityCol) {
        return `xtset ${params.entityCol} ${params.timeCol ?? "_t"}\ngen ${params.col}_d = D.${params.col}`;
      }
      return `gen ${params.col}_d = D.${params.col}`;
    case "ix":
      return `gen ${params.col1}_x_${params.col2} = ${params.col1} * ${params.col2}`;
    case "did":
      return `gen did = ${params.postVar} * ${params.treatVar}`;
    case "mutate": {
      const nn     = step.nn ?? params.newCol ?? "newcol";
      const stExpr = jsExprToStata(step.expr ?? params.expr);
      if (stExpr) return `gen ${nn} = ${stExpr}`;
      return [
        `* mutate: ${nn} = ${step.expr ?? params.expr}`,
        `* NOTE: expression uses JS syntax — translate to Stata manually`,
        `* gen ${nn} = <Stata expression>`,
      ].join("\n");
    }
    case "arrange":
      return `sort ${params.col}`;
    case "group_summarize": {
      const { groupCol, agg = {} } = params;
      const cmds = Object.entries(agg).map(([col, fn]) => `  egen ${col}_${fn} = ${fn}(${col}), by(${groupCol})`);
      return [`collapse (${Object.values(agg)[0] ?? "mean"}) ${Object.keys(agg).join(" ")}, by(${groupCol})`, ...cmds].join("\n");
    }
    case "pivot_longer": {
      const { idCols = [], valueName = "value", variableName = "variable", valueCols = [] } = params;
      return `reshape long ${valueCols.join(" ")}, i(${idCols.join(" ")}) j(${variableName}) string`;
    }
    case "date_parse":
      return `gen ${params.col}_dt = date(${params.col}, "YMD")`;
    case "date_extract":
      return `gen ${params.newCol} = ${params.part ?? "year"}(${params.col}_dt)`;
    case "recode": {
      const entries = Object.entries(params.map ?? {});
      return entries.map(([from, to]) => {
        const f = isNaN(Number(from)) ? `"${from}"` : from;
        const t = isNaN(Number(to))   ? `"${to}"`   : to;
        return `replace ${params.col} = ${t} if ${params.col} == ${f}`;
      }).join("\n");
    }
    case "trim_outliers": {
      const { col } = params;
      return [`_pctile ${col}, percentiles(25 75)`, `local q1 = r(r1)`, `local q3 = r(r2)`, `local iqr = \`q3' - \`q1'`, `drop if ${col} < \`q1' - 1.5*\`iqr' | ${col} > \`q3' + 1.5*\`iqr'`].join("\n");
    }
    case "flag_outliers": {
      const { col } = params;
      return [`_pctile ${col}, percentiles(25 75)`, `local q1 = r(r1)`, `local q3 = r(r2)`, `local iqr = \`q3' - \`q1'`, `gen ${col}_outlier = (${col} < \`q1' - 1.5*\`iqr') | (${col} > \`q3' + 1.5*\`iqr')`].join("\n");
    }
    case "quickclean":
      return `duplicates drop\ndrop if missing(*)`;
    case "normalize_cats":
      if (params.col) return `replace ${params.col} = strtrim(lower(${params.col}))`;
      return `* normalize_cats: manual step`;
    case "extract_regex":
      return `* regex extract: gen ${params.newCol} from ${params.col} using pattern "${params.regex}"\n* Use -regexm()- / -regexs()-:\n* gen ${params.newCol} = regexs(1) if regexm(${params.col}, "${params.regex}")`;
    case "join": {
      const how      = step.how === "inner" ? "1:1" : "1:1";  // Stata: 1:1 for both; user adjusts to m:1/1:m as needed
      const lk       = step.leftKey  ?? "id";
      const rk       = step.rightKey ?? lk;
      const sfx      = step.suffix   ?? "_r";
      const sameKey  = lk === rk ? lk : `${lk} = ${rk}`;
      const keepInner = step.how === "inner" ? "\nkeep if _merge == 3" : "\nkeep if _merge == 1 | _merge == 3";
      return [
        `* Join: load right dataset, merge on ${sameKey}`,
        `preserve`,
        `  ${stataRightLoad(step.rightId, allDatasets)}`,
        `  rename ${rk} ${lk}  /* align key names */`,
        `  save "__right_tmp.dta", replace`,
        `restore`,
        `merge ${how} ${lk} using "__right_tmp.dta", keep(master match) nogen suffixes("" "${sfx}")${keepInner}`,
        `erase "__right_tmp.dta"`,
      ].join("\n");
    }
    case "append": {
      return [
        `* Append: stack right dataset below current`,
        `preserve`,
        `  ${stataRightLoad(step.rightId, allDatasets)}`,
        `  save "__append_tmp.dta", replace`,
        `restore`,
        `append using "__append_tmp.dta"`,
        `erase "__append_tmp.dta"`,
      ].join("\n");
    }
    case "ai_tr": {
      const col    = step.col ?? "col";
      const jsCode = step.js  ?? "";
      const arrowMatch = jsCode.match(/^\s*\(?\s*(\w+)\s*\)?\s*=>\s*([\s\S]+)$/);
      if (arrowMatch) {
        const [, param, body] = arrowMatch;
        const substituted = body.trim().replace(new RegExp(`\\b${param}\\b`, "g"), col);
        const stExpr = jsExprToStata(substituted);
        if (stExpr) return `replace ${col} = ${stExpr}`;
      }
      return [
        `* AI transform on "${col}"`,
        `* JS: ${jsCode}`,
        `* replace ${col} = <Stata expression>`,
      ].join("\n");
    }
    case "factor_interactions": {
      const { cols } = params;
      if (cols?.length >= 2) return `gen ${cols.join("_x_")} = ${cols[0]} * ${cols[1]}`;
      return `* factor_interactions`;
    }
    case "patch": {
      const col = step.col ?? "column";
      const val = typeof step.value === "string" ? `"${step.value}"` : (step.value ?? ".");
      if (step.rowId) {
        return `replace ${col} = ${val} if __row_id == "${step.rowId}"`;
      }
      return `replace ${col} = ${val} if __ri == ${step.ri}  /* __ri-based: may misalign after sort */`;
    }

    case "geocode": {
      const addrCol = step.addressCol ?? "address";
      const latCol  = step.latCol  ?? "lat";
      const lonCol  = step.lonCol  ?? "lon";
      return [
        `* Geocode: ${addrCol} -> ${latCol} / ${lonCol}`,
        `* Stata has no native geocoding — export addresses, geocode externally, merge back.`,
        `* Step 1: export addresses`,
        `preserve`,
        `keep ${addrCol}`,
        `duplicates drop`,
        `export delimited using "addresses_to_geocode.csv", replace`,
        `restore`,
        `* Step 2: geocode the CSV externally (Python/R with geopy/tidygeocoder)`,
        `* Step 3: merge geocoded coordinates back`,
        `* merge m:1 ${addrCol} using "geocoded_coords.dta", keep(master match) nogenerate`,
        `* rename _lat ${latCol}`,
        `* rename _lon ${lonCol}`,
      ].join("\n");
    }

    default:
      return `* [${type}] — not yet transpiled`;
  }
}

// ─── MODEL TRANSPILER ─────────────────────────────────────────────────────────
function transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, factorVars = [], treatedUnit, treatTime, weightCol = null }) {
  const lines = [];
  const fvSet = new Set(factorVars);
  const fmtS  = v => fvSet.has(v) ? `i.${v}` : v;
  const xList = allX.map(fmtS).join(" ");

  switch (type) {
    case "OLS":
      lines.push(`reg ${yVar} ${xList}, robust`);
      lines.push(`estimates store m_ols`);
      break;

    case "WLS":
      if (!weightCol) {
        lines.push(`* WARNING: no weight column supplied; falling back to OLS`);
        lines.push(`reg ${yVar} ${xList}, robust`);
      } else {
        lines.push(`* Weighted Least Squares (analytic weights: ${weightCol})`);
        lines.push(`reg ${yVar} ${xList} [aw=${weightCol}], robust`);
      }
      lines.push(`estimates store m_wls`);
      break;

    case "FE":
      lines.push(`* Fixed Effects (within)`);
      lines.push(`xtset ${entityCol} ${timeCol}`);
      lines.push(`xtreg ${yVar} ${xList}, fe vce(cluster ${entityCol})`);
      lines.push(`estimates store m_fe`);
      break;

    case "FD":
      lines.push(`* First Differences`);
      lines.push(`xtset ${entityCol} ${timeCol}`);
      lines.push(`xtreg ${yVar} ${xList}, fd vce(cluster ${entityCol})`);
      lines.push(`estimates store m_fd`);
      break;

    case "2SLS": {
      const endog = xVars.join(" ");
      const instr = zVars.join(" ");
      const exog  = wVars.join(" ");
      lines.push(`* Two-Stage Least Squares / IV`);
      lines.push(`ivregress 2sls ${yVar} ${exog ? `(${endog} = ${instr}) ${exog}` : `(${endog} = ${instr})`}, robust`);
      lines.push(`estimates store m_2sls`);
      lines.push(`* First-stage F-statistic`);
      lines.push(`estat firststage`);
      break;
    }

    case "DiD": {
      const extra = wVars.length ? ` ${wVars.join(" ")}` : "";
      lines.push(`* Difference-in-Differences (2×2)`);
      lines.push(`gen did = ${postVar} * ${treatVar}`);
      lines.push(`reg ${yVar} ${postVar} ${treatVar} did${extra}, robust`);
      lines.push(`estimates store m_did`);
      break;
    }

    case "TWFE": {
      const extra = wVars.length ? ` ${wVars.join(" ")}` : "";
      lines.push(`* Two-Way Fixed Effects DiD`);
      lines.push(`xtset ${entityCol} ${timeCol}`);
      lines.push(`reghdfe ${yVar} ${treatVar}${extra}, absorb(${entityCol} ${timeCol}) vce(cluster ${entityCol})`);
      lines.push(`* If reghdfe not installed: ssc install reghdfe`);
      lines.push(`estimates store m_twfe`);
      break;
    }

    case "RDD": {
      const kernelOpt = kernel === "uniform" ? "nw(1)" : kernel === "epanechnikov" ? "kernel(epanechnikov)" : "kernel(triangular)";
      const extra = wVars.length ? ` ${wVars.join(" ")}` : "";
      lines.push(`* Sharp RDD — local linear regression`);
      lines.push(`* If rdrobust not installed: ssc install rdrobust`);
      lines.push(`rdrobust ${yVar} ${runningVar}, c(${cutoff ?? 0}) h(${bandwidth ?? "# set bandwidth"}) ${kernelOpt}${extra ? ` covs(${wVars.join(" ")})` : ""}`);
      lines.push(`* Manual approach (WLS local linear):`);
      lines.push(`gen _above = (${runningVar} >= ${cutoff ?? 0})`);
      lines.push(`gen _run_c = ${runningVar} - ${cutoff ?? 0}`);
      lines.push(`gen _above_run = _above * _run_c`);
      lines.push(`* Triangular kernel weights:`);
      lines.push(`gen _w = max(0, 1 - abs(_run_c) / ${bandwidth ?? 1}) if abs(_run_c) <= ${bandwidth ?? 1}`);
      lines.push(`reg ${yVar} _above _run_c _above_run${extra} [aw=_w], robust`);
      lines.push(`drop _above _run_c _above_run _w`);
      break;
    }

    case "Logit":
      lines.push(`logit ${yVar} ${xList}`);
      lines.push(`estimates store m_logit`);
      lines.push(`* Marginal effects at the mean`);
      lines.push(`margins, dydx(*) atmeans`);
      break;

    case "Probit":
      lines.push(`probit ${yVar} ${xList}`);
      lines.push(`estimates store m_probit`);
      lines.push(`* Marginal effects at the mean`);
      lines.push(`margins, dydx(*) atmeans`);
      break;

    case "LSDV": {
      lines.push(`* Panel LSDV — recover entity fixed effects explicitly`);
      lines.push(`xtset ${entityCol} ${timeCol}`);
      lines.push(`* Within (FE) — numerically equivalent to LSDV`);
      lines.push(`xtreg ${yVar} ${xList}, fe vce(cluster ${entityCol})`);
      lines.push(`estimates store m_lsdv`);
      lines.push(``);
      lines.push(`* Recover alpha_i (entity fixed effects) via areg`);
      lines.push(`areg ${yVar} ${xList}, absorb(${entityCol}) vce(cluster ${entityCol})`);
      lines.push(`predict _alpha_i, dresiduals`);
      lines.push(`label var _alpha_i "Entity fixed effect (LSDV alpha_i)"`);
      lines.push(`* List unique entity FEs`);
      lines.push(`bysort ${entityCol}: keep if _n == 1`);
      lines.push(`list ${entityCol} _alpha_i, sep(0)`);
      break;
    }

    case "FuzzyRDD": {
      const kernelOpt = kernel === "uniform" ? "nw(1)"
                      : kernel === "epanechnikov" ? "kernel(epanechnikov)"
                      : "kernel(triangular)";
      const dVar  = treatVar ?? "D";
      const extra = wVars.length ? ` covs(${wVars.join(" ")})` : "";
      lines.push(`* Fuzzy RDD via rdrobust`);
      lines.push(`* If not installed: ssc install rdrobust`);
      lines.push(`rdrobust ${yVar} ${runningVar}, fuzzy(${dVar}) c(${cutoff ?? 0}) h(${bandwidth ?? "# set bandwidth"}) ${kernelOpt}${extra}`);
      lines.push(`* First-stage jump in take-up probability`);
      lines.push(`gen _Z = (${runningVar} >= ${cutoff ?? 0})`);
      lines.push(`gen _run_c = ${runningVar} - ${cutoff ?? 0}`);
      lines.push(`ivregress 2sls ${yVar} _run_c (${dVar} = _Z), robust`);
      lines.push(`drop _Z _run_c`);
      break;
    }

    case "SpatialRDD": {
      const kernelOpt = kernel === "uniform"      ? "nw(1)"
                      : kernel === "epanechnikov" ? "kernel(epanechnikov)"
                      : "kernel(triangular)";
      const distV  = distCol      ?? runningVar ?? "dist";
      const trtV   = treatmentCol ?? treatVar   ?? "treatment";
      const h      = bandwidth ? Number(bandwidth).toFixed(6) : null;
      const extra  = wVars.length ? ` covs(${wVars.join(" ")})` : "";
      lines.push(`* Spatial RD (Keele & Titiunik 2015)`);
      lines.push(`* Build signed running variable: positive on treated side, cutoff = 0`);
      lines.push(`gen _signed_dist = (2 * ${trtV} - 1) * abs(${distV})`);
      lines.push(`* If rdrobust not installed: ssc install rdrobust`);
      if (h) {
        lines.push(`rdrobust ${yVar} _signed_dist, c(0) h(${h}) ${kernelOpt}${extra}`);
      } else {
        lines.push(`rdrobust ${yVar} _signed_dist, c(0) ${kernelOpt}${extra}`);
      }
      lines.push(`* Manual WLS approach (triangular kernel):`);
      lines.push(`gen _above = (_signed_dist >= 0)`);
      lines.push(`gen _above_run = _above * _signed_dist`);
      const bwStata = h ?? "# replace with bandwidth";
      lines.push(`gen _w = max(0, 1 - abs(_signed_dist) / ${bwStata}) if abs(_signed_dist) <= ${bwStata}`);
      lines.push(`reg ${yVar} _above _signed_dist _above_run${wVars.length ? " " + wVars.join(" ") : ""} [aw=_w], robust`);
      lines.push(`drop _signed_dist _above _above_run _w`);
      break;
    }

    case "EventStudy": {
      const extra = wVars.length ? ` ${wVars.join(" ")}` : "";
      lines.push(`* Event Study — relative-time dummies`);
      lines.push(`* Replace treat_time with the variable holding each unit's treatment period`);
      lines.push(`xtset ${entityCol} ${timeCol}`);
      lines.push(`gen rel_time = ${timeCol} - treat_time`);
      lines.push(`* Estimate with unit + time FE, ref = -1`);
      lines.push(`* If reghdfe not installed: ssc install reghdfe`);
      lines.push(`reghdfe ${yVar} ib(-1).rel_time${extra}, absorb(${entityCol} ${timeCol}) vce(cluster ${entityCol})`);
      lines.push(`estimates store m_eventstudy`);
      lines.push(`* Plot coefficients`);
      lines.push(`coefplot m_eventstudy, keep(*rel_time*) vertical yline(0) xline(# replace with ref period index)`);
      break;
    }

    case "SyntheticControl": {
      const ec = entityCol ?? "unit";
      const tc = timeCol   ?? "time";
      const tu = treatedUnit ?? "TreatedUnit";
      const tt = treatTime != null ? Number(treatTime) : "TREAT_TIME";
      const predsStr = (xVars ?? []).length
        ? (xVars ?? []).join(" ")
        : `${yVar}  /* no explicit predictors — outcome mean used */`;
      lines.push(`* ── Synthetic Control (synth package) ──────────────────────────────`);
      lines.push(`* Install: ssc install synth, replace`);
      lines.push(`tsset ${ec} ${tc}`);
      lines.push(``);
      lines.push(`* synth requires balanced panel — verify before running`);
      lines.push(`synth ${yVar} ${predsStr}, ///`);
      lines.push(`    trunit("${tu}") trperiod(${tt}) ///`);
      lines.push(`    xperiod(#pre_start(#)${tt - 1}) ///`);
      lines.push(`    nested allopt figure`);
      lines.push(``);
      lines.push(`* Donor weights are stored in e(W_weights)`);
      lines.push(`mat weights = e(W_weights)`);
      lines.push(`mat list weights`);
      lines.push(``);
      lines.push(`* MSPE ratio (post/pre) for inference`);
      lines.push(`* Use synth_runner for automated placebo inference:`);
      lines.push(`* ssc install synth_runner, replace`);
      lines.push(`* synth_runner ${yVar} ${predsStr}, trunit("${tu}") trperiod(${tt}) gen_vars`);
      break;
    }

    case "GMM": {
      const endog  = wVars.join(" ");
      const exog   = xVars.join(" ");
      const instrs = [...xVars, ...zVars].join(" ");
      lines.push(`* Two-Step Efficient GMM`);
      lines.push(`* Structural: ${yVar} ~ ${exog || "(no exog)"} + (${endog || "endog"}) endogenous`);
      lines.push(`* Instruments: ${instrs || "(instruments)"}`);
      if (wVars.length) {
        lines.push(`ivregress gmm ${yVar}${exog ? ` ${exog}` : ""} (${endog} = ${zVars.join(" ")}), wmatrix(robust)`);
      } else {
        lines.push(`* No endogenous variables specified — using 2SLS form`);
        lines.push(`ivregress gmm ${yVar} ${exog}, robust`);
      }
      lines.push(`estat overid  /* Sargan-Hansen J-test — available after gmm */`);
      break;
    }

    case "LIML": {
      const endog  = wVars.join(" ");
      const exog   = xVars.join(" ");
      lines.push(`* Limited Information Maximum Likelihood (LIML)`);
      if (wVars.length) {
        lines.push(`ivregress liml ${yVar}${exog ? ` ${exog}` : ""} (${endog} = ${zVars.join(" ")}), vce(robust)`);
      } else {
        lines.push(`* No endogenous variables specified — defaulting to OLS`);
        lines.push(`reg ${yVar} ${exog}, robust`);
      }
      lines.push(`estat firststage  /* first-stage F-statistics */`);
      break;
    }

    case "PoissonFE": {
      const ec   = entityCol ?? "entity";
      const cov  = xVars.join(" ");
      lines.push(`* Poisson FE (PPML with entity fixed effects)`);
      lines.push(`* ppmlhdfe recommended — if not installed: ssc install ppmlhdfe`);
      lines.push(`ppmlhdfe ${yVar}${cov ? ` ${cov}` : ""}, absorb(${ec}) vce(cluster ${ec})`);
      lines.push(`* Incidence Rate Ratios (manual — Stata PPML reports log-IRR by default):`);
      lines.push(`* nlcom (exp(_b[${xVars[0] ?? "x"}]))`);
      break;
    }

    case "McCrary": {
      const rv = runningVar ?? "running";
      const c0 = cutoff ?? 0;
      lines.push(`* McCrary / Cattaneo-Jansson-Ma density test`);
      lines.push(`* If rddensity not installed: ssc install rddensity`);
      lines.push(`rddensity ${rv}, c(${c0})`);
      lines.push(`rddensity ${rv}, c(${c0}) plot`);
      break;
    }

    default:
      lines.push(`* Model type "${type}" — add estimation command here`);
  }

  return lines;
}

// ─── MULTI-MODEL HELPERS ─────────────────────��────────────────────────────────

function detectMapPatternStata(configs) {
  if (configs.length < 2) return "separate";
  const allHaveMeta = configs.every(c => Array.isArray(c.subsetFilters));
  if (!allHaveMeta) return "separate";
  const first = configs[0].model;
  const xKey  = arr => JSON.stringify([...(arr ?? [])].sort());
  return configs.every(c =>
    c.model.type === first.type &&
    c.model.yVar === first.yVar &&
    xKey(c.model.xVars) === xKey(first.xVars)
  ) ? "map" : "separate";
}

function subsetFiltersToStata(filters) {
  if (!filters?.length) return null;
  return filters.map(f => {
    const val = isNaN(Number(f.val)) ? `"${f.val}"` : f.val;
    return `${f.col} ${f.op} ${val}`;
  }).join(" & ");
}

// Safe Stata local name: lowercase, spaces → underscores, strip special chars
function stataLocalName(label) {
  return label.toLowerCase().replace(/[^a-z0-9_]/g, "_").replace(/^[0-9]/, "_").slice(0, 28);
}

// ─── MULTI-MODEL EXPORT ────────────────────────────────────────────────────────
// configs: Array of { model: ModelConfig, label: string, subsetName?, subsetFilters? }
export function generateMultiModelStataScript(configs = [], dataDictionary = null, opts = {}) {
  if (!configs.length) return "* No models provided.";

  const filename     = opts.filename ?? "dataset.csv";
  const pipeline     = opts.pipeline ?? [];
  const dataLoadOpts = opts.dataLoadOpts ?? null;
  const stataFile    = filename.replace(/\\/g, "/");
  const ts = new Date().toISOString().slice(0, 10);
  const lines = [];

  lines.push(`* ${"─".repeat(71)}`);
  lines.push(`* Multi-model replication do-file — generated by Litux`);
  lines.push(`* Models: ${configs.map((c, i) => `(${i+1}) ${c.label ?? c.model?.type}`).join(", ")}`);
  lines.push(`* Generated: ${ts}`);
  lines.push(`* ${"─".repeat(71)}`);
  lines.push("");
  lines.push("clear all");
  lines.push("set more off");
  lines.push("version 17");
  lines.push("");

  lines.push(`* ── Load data ────────────────────────────────────────────────────────────`);
  lines.push(buildStataLoadLine(stataFile, dataLoadOpts));
  lines.push("");

  if (pipeline.length) {
    lines.push(`* ── Data pipeline ────────────────────────────────────────────────────────`);
    pipeline.forEach(step => {
      const out = toStata(step, "df");
      if (Array.isArray(out)) out.forEach(l => lines.push(l));
      else if (out) lines.push(out);
    });
    lines.push("");
  }

  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push(`* ── Variable definitions ─────────────────────────────────────────────────`);
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => {
      const clean = String(v).replace(/`/g, "'").replace(/\n/g, " ").slice(0, 120);
      lines.push(`* ${k}: ${clean}`);
    });
    lines.push("");
  }

  const pattern = detectMapPatternStata(configs);

  if (pattern === "map") {
    // ── Same spec, different subsets → preserve/restore per subset ────────────
    lines.push(`* ── Subset estimation (preserve/restore) ─────────────────────────────────`);
    const estoreNames = [];
    const { type = "OLS", yVar = "y", xVars = [], wVars = [], zVars = [],
            entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel,
            treatedUnit, treatTime } = configs[0].model ?? {};
    const allX = [...xVars, ...wVars];

    configs.forEach((c) => {
      const estName = stataLocalName(c.subsetName ?? c.label);
      estoreNames.push({ name: estName, label: c.subsetName ?? c.label });
      const filterExpr = subsetFiltersToStata(c.subsetFilters);
      lines.push(`preserve`);
      if (filterExpr) lines.push(`  keep if ${filterExpr}`);
      else            lines.push(`  * Full sample — no filter`);
      const modelLines = transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, treatedUnit, treatTime });
      let hasStore = false;
      modelLines.forEach(l => {
        const ov = l.replace(/^estimates store \S+/, `estimates store ${estName}`);
        if (ov !== l) hasStore = true;
        lines.push(`  ${ov}`);
      });
      if (!hasStore) lines.push(`  estimates store ${estName}`);
      lines.push(`restore`);
      lines.push(``);
    });

    lines.push(`* ── Joint table (esttab) ─────────────────────────────────────────────────`);
    lines.push(`* If esttab not installed: ssc install estout`);
    const mList    = estoreNames.map(e => e.name).join(" ");
    const mlabels  = estoreNames.map(e => `"${e.label}"`).join(" ");
    lines.push(`esttab ${mList} using comparison_results.rtf, ///`);
    lines.push(`  mtitles(${mlabels}) ///`);
    lines.push(`  star(* 0.1 ** 0.05 *** 0.01) ///`);
    lines.push(`  se r2 N replace`);
    lines.push("");
  } else {
    // ── Different specs → one block per model ────────────────────────────────
    lines.push(`* ── Estimation ───────────────────────────────────────────────────────────`);
    const estoreNames = [];
    configs.forEach((c, i) => {
      const estName = `m_${i + 1}`;
      estoreNames.push({ name: estName, label: c.label ?? c.model?.type ?? `Model ${i+1}` });
      const { type = "OLS", yVar = "y", xVars = [], wVars = [], zVars = [],
              entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel,
              treatedUnit, treatTime } = c.model ?? {};
      const allX = [...xVars, ...wVars];
      lines.push(`* Model ${i+1}: ${c.label ?? type}`);
      const modelLines = transpileModel({ type, yVar, allX, xVars, wVars, zVars, entityCol, timeCol, postVar, treatVar, runningVar, cutoff, bandwidth, kernel, treatedUnit, treatTime });
      let hasStore = false;
      modelLines.forEach(l => {
        const overridden = l.replace(/^estimates store \S+/, `estimates store ${estName}`);
        if (overridden !== l) hasStore = true;
        lines.push(overridden);
      });
      if (!hasStore) lines.push(`estimates store ${estName}`);
      lines.push("");
    });

    lines.push(`* ── Joint table (esttab) ─────────────────────────────────────────────────`);
    lines.push(`* If esttab not installed: ssc install estout`);
    const mList   = estoreNames.map(e => e.name).join(" ");
    const mlabels = estoreNames.map(e => `"${e.label}"`).join(" ");
    lines.push(`esttab ${mList} using comparison_results.rtf, ///`);
    lines.push(`  mtitles(${mlabels}) ///`);
    lines.push(`  star(* 0.1 ** 0.05 *** 0.01) ///`);
    lines.push(`  se r2 N replace`);
    lines.push("");
  }

  return lines.join("\n");
}

// ─── SUBSET REPLICATION SCRIPT (H6/H10) ───────────────────────────────────────
// config: { filename, pipeline, perSubsetSteps, subsets, model, dataDictionary }
export function generateSubsetStataScript({ filename = "dataset.csv", pipeline = [], perSubsetSteps = [], subsets = [], model = {}, dataDictionary = null, dataLoadOpts = null } = {}) {
  const ts   = new Date().toISOString().slice(0, 10);
  const stem = filename.replace(/\.[^.]+$/, "");
  const lines = [];

  function filterCond(filters) {
    if (!filters?.length) return null;
    return filters.map(f => {
      const col  = f.col.replace(/[^a-zA-Z0-9_]/g, "_");
      const isNum = f.val !== "" && !isNaN(Number(f.val));
      const val  = isNum ? f.val : `"${f.val}"`;
      return `${col} ${f.op} ${val}`;
    }).join(" & ");
  }

  lines.push(`* ${"─".repeat(71)}`);
  lines.push(`* Multi-subset replication do-file — generated by Litux`);
  lines.push(`* Dataset: ${filename}  |  Model: ${model.type ?? "OLS"}  |  ${ts}`);
  lines.push(`* ${"─".repeat(71)}`);
  lines.push("");
  lines.push("clear all");
  lines.push("set more off");
  lines.push("version 17");
  lines.push("");

  lines.push(`* ── Load data ────────────────────────────────────────────────────────────`);
  lines.push(buildStataLoadLine(filename.replace(/\\/g, "/"), dataLoadOpts));
  lines.push("");

  if (dataDictionary && Object.keys(dataDictionary).length) {
    lines.push(`* ── Variable definitions ─────────────────────────────────────────────────`);
    Object.entries(dataDictionary).slice(0, 20).forEach(([k, v]) => {
      lines.push(`* ${k}: ${String(v).replace(/`/g, "'").replace(/\n/g, " ").slice(0, 120)}`);
    });
    lines.push("");
  }

  if (pipeline.length) {
    lines.push(`* ── Shared pipeline ─────────────────────────────────────────────────────`);
    pipeline.forEach(step => { const c = transpileStep(step); if (c) lines.push(c); });
    lines.push("");
  }

  const { type = "OLS", yVar = "y", xVars = [], wVars = [] } = model;
  const allX = [...(xVars ?? []), ...(wVars ?? [])];
  const estoreNames = [];

  // ── Full sample
  lines.push(`* ── Full sample ──────────────────────────────────────────────────────────`);
  const fullName = `s_full`;
  estoreNames.push({ name: fullName, label: "Full sample" });
  transpileModel({ ...model, allX }).forEach(l => lines.push(l));
  lines.push(`estimates store ${fullName}`);
  lines.push("");

  // ── Named subsets (preserve / restore pattern)
  subsets.forEach((s, i) => {
    const safeName = `s_${i + 1}`;
    estoreNames.push({ name: safeName, label: s.name });
    const cond = filterCond(s.filters);
    lines.push(`* ── Subset: ${s.name} ──────────────────────────────────────────────────`);
    lines.push(`preserve`);
    if (cond) lines.push(`keep if ${cond}`);
    if (perSubsetSteps.length) {
      lines.push(`* Per-subset pipeline`);
      perSubsetSteps.forEach(step => { const c = transpileStep(step); if (c) lines.push(c); });
    }
    transpileModel({ ...model, allX }).forEach(l => lines.push(l));
    lines.push(`estimates store ${safeName}`);
    lines.push(`restore`);
    lines.push("");
  });

  lines.push(`* ── Comparison table (esttab) ────────────────────────────────────────────`);
  lines.push(`* If not installed: ssc install estout`);
  const mList    = estoreNames.map(e => e.name).join(" ");
  const mlabels  = estoreNames.map(e => `"${e.label}"`).join(" ");
  lines.push(`esttab ${mList} using "${stem}_subsets.rtf", ///`);
  lines.push(`  mtitles(${mlabels}) ///`);
  lines.push(`  star(* 0.1 ** 0.05 *** 0.01) ///`);
  lines.push(`  se r2 N replace`);
  lines.push("");

  return lines.join("\n");
}
