# ─── Goodman-Bacon decomposition — R ground truth ─────────────────────────────
# Generates baconFixture_<scenario>.csv + baconBenchmarks.json from
# bacondecomp::bacon(), for src/math/did/baconDecomp.js.
#
# Run:  Rscript src/math/__validation__/baconRValidation.R
# (R is installed but not on PATH — see CLAUDE.md for the full invocation path.)
#
# Scenarios deliberately cover the cases where the weights differ structurally:
#   het    — heterogeneous effects; the Later-vs-Earlier 2x2 flips sign
#   hom    — homogeneous effects; every 2x2 recovers the same number
#   t5     — 3 cohorts x 5 periods; 9 comparisons, all three types
#   nonev  — NO never-treated group; only timing comparisons exist
suppressMessages({ library(bacondecomp); library(fixest) })
set.seed(123)
# Run from the repo root.
out <- "src/math/__validation__"

mk <- function(TE, cohorts, periods, nEach = 100) {
  rows <- list(); pid <- 0
  for (cn in names(cohorts)) {
    start <- cohorts[[cn]]$start; pe_mean <- cohorts[[cn]]$pe
    for (i in 1:nEach) {
      pid <- pid + 1; pe <- rnorm(1, pe_mean, 0.5)
      for (t in periods) {
        d <- if (!is.na(start) && t >= start) 1 else 0
        key <- paste0(cn, "_", t)
        eff <- if (!is.null(TE[[key]])) TE[[key]] else 0
        rows[[length(rows) + 1]] <- data.frame(
          person_id = pid, time_id = t, treated = d,
          outcome = pe + t + eff + rnorm(1, 0, 0.25))
      }
    }
  }
  do.call(rbind, rows)
}

esc <- function(s) gsub('"', '\\\\"', s)
blocks <- c()

run <- function(label, df) {
  write.csv(df, file.path(out, paste0("baconFixture_", label, ".csv")), row.names = FALSE)
  b  <- bacon(outcome ~ treated, data = df, id_var = "person_id", time_var = "time_id")
  tw <- feols(outcome ~ treated | person_id + time_id, data = df)
  b  <- b[order(-b$weight), ]
  rws <- paste0(sprintf(
    '      {"type":"%s","treated":%s,"control":%s,"weight":%.12f,"estimate":%.12f}',
    esc(as.character(b$type)), b$treated,
    ifelse(b$untreated == 99999, "null", as.character(b$untreated)),
    b$weight, b$estimate), collapse = ",\n")
  blocks <<- c(blocks, sprintf(
    '  "%s": {\n    "twfe": %.12f,\n    "comparisons": [\n%s\n    ]\n  }',
    label, coef(tw)[["treated"]], rws))
}

run("het", mk(list(early_2 = 4, early_3 = 40, late_3 = 4),
              list(early = list(start = 2, pe = 5), late = list(start = 3, pe = 10),
                   never = list(start = NA, pe = 15)), 1:3))
run("hom", mk(list(early_2 = 3, early_3 = 3, late_3 = 3),
              list(early = list(start = 2, pe = 5), late = list(start = 3, pe = 10),
                   never = list(start = NA, pe = 15)), 1:3))
run("t5",  mk(list(early_2 = 2, early_3 = 3, early_4 = 3, early_5 = 3,
                   mid_3 = 2, mid_4 = 3, mid_5 = 3, late_4 = 2, late_5 = 3),
              list(early = list(start = 2, pe = 5), mid = list(start = 3, pe = 8),
                   late = list(start = 4, pe = 11), never = list(start = NA, pe = 15)), 1:5))
run("nonev", mk(list(early_2 = 3, early_3 = 3, late_3 = 3),
                list(early = list(start = 2, pe = 5), late = list(start = 3, pe = 10)), 1:3))

meta <- sprintf('  "meta": {"source": "R bacondecomp %s + fixest, generated by baconRValidation.R", "rVersion": "%s"}',
                as.character(packageVersion("bacondecomp")), getRversion())
writeLines(paste0("{\n", meta, ",\n", paste(blocks, collapse = ",\n"), "\n}"),
           file.path(out, "baconBenchmarks.json"))
cat("wrote baconBenchmarks.json +", length(blocks), "fixtures\n")
