# ─── CR2 / CR3 cluster-robust SE — R ground truth ─────────────────────────────
# Generates clusterRobustFixture_<case>.csv + clusterRobustBenchmarks.json from
# clubSandwich::vcovCR(), for src/core/inference/robustSE.js.
#
# Run from the repo root:
#   Rscript src/math/__validation__/clusterRobustRValidation.R
# (R is installed but not on PATH — see CLAUDE.md for the invocation path.)
#
# Cases target where CR2/CR3 actually diverge from CR1:
#   balanced — 20 clusters x 8 obs; the comfortable case
#   small    — 8 clusters x 4 obs; few/small clusters, where CR2 matters most
#   uneven   — unbalanced cluster sizes
#
# NOTE ON CONVENTIONS: clubSandwich's CR1S is G/(G-1) * (n-1)/(n-k), which is
# what robustSE.js's "clustered" implements (Stata's default). Plain CR1 in
# clubSandwich is G/(G-1) only — do not compare against that one.
suppressMessages(library(clubSandwich))
set.seed(2024)
out <- "src/math/__validation__"

mk <- function(G, ng, k) {
  n <- G * ng
  d <- data.frame(g = rep(1:G, each = ng))
  for (j in 1:k) d[[paste0("x", j)]] <- rnorm(n)
  ge <- rnorm(G, 0, 1.5)[d$g]
  d$y <- 1 + rowSums(as.matrix(d[, paste0("x", 1:k)]) %*% rep(0.7, k)) + ge + rnorm(n)
  d
}

blocks <- c()
run <- function(label, d, k) {
  write.csv(d, file.path(out, paste0("clusterRobustFixture_", label, ".csv")), row.names = FALSE)
  f <- as.formula(paste("y ~", paste0("x", 1:k, collapse = " + ")))
  m <- lm(f, data = d)
  ses <- lapply(c(CR1S = "CR1S", CR2 = "CR2", CR3 = "CR3"), function(ty)
    sqrt(diag(vcovCR(m, cluster = d$g, type = ty))))
  fmt <- function(v) paste0("[", paste(sprintf("%.12f", v), collapse = ","), "]")
  blocks <<- c(blocks, sprintf(
    '  "%s": {\n    "k": %d, "nClusters": %d, "n": %d,\n    "coef": %s,\n    "CR1S": %s,\n    "CR2": %s,\n    "CR3": %s\n  }',
    label, k, length(unique(d$g)), nrow(d), fmt(coef(m)),
    fmt(ses$CR1S), fmt(ses$CR2), fmt(ses$CR3)))
}

run("balanced", mk(20, 8, 3), 3)
run("small",    mk(8, 4, 2),  2)
d <- mk(15, 10, 2); d <- d[-(1:20), ]                     # drop 20 rows → uneven sizes
run("uneven",   d, 2)

meta <- sprintf('  "meta": {"source": "R clubSandwich %s vcovCR, generated by clusterRobustRValidation.R", "rVersion": "%s"}',
                as.character(packageVersion("clubSandwich")), getRversion())
writeLines(paste0("{\n", meta, ",\n", paste(blocks, collapse = ",\n"), "\n}"),
           file.path(out, "clusterRobustBenchmarks.json"))
cat("wrote clusterRobustBenchmarks.json +", length(blocks), "fixtures\n")
