# src/math/__validation__/panelNwayFeRValidation.R
# Validates PanelEngine.js's runFEMulti / runTWFEDiDMulti against fixest for:
#   (a) 2 independent (non-nested) FE dims: state + industry
#   (b) 3 independent FE dims: state + industry + year
#   (c) a nested pair: state + (state × year) — tests the df-collinearity risk
#       flagged in PanelWithinEngine.js's feDegreesOfFreedom() comment
library(fixest)
library(jsonlite)

set.seed(42)
n_state <- 8; n_industry <- 5; n_year <- 6
df <- expand.grid(state = 1:n_state, industry = 1:n_industry, year = 1:n_year)
df$x1 <- rnorm(nrow(df))
df$x2 <- rnorm(nrow(df))
df$y  <- 2 + 0.5*df$x1 - 0.3*df$x2 + df$state*0.1 + df$industry*0.2 + df$year*0.05 + rnorm(nrow(df))

fit_2way <- feols(y ~ x1 + x2 | state + industry, data = df)
fit_3way <- feols(y ~ x1 + x2 | state + industry + year, data = df)
df$state_year <- interaction(df$state, df$year)
fit_nested <- feols(y ~ x1 + x2 | state + state_year, data = df)

extract <- function(fit) list(
  coef = as.numeric(coef(fit)), se = as.numeric(se(fit)),
  df = fit$nobs - fit$nparams, nobs = fit$nobs
)

benchmarks <- list(
  meta = list(source = "R fixest, generated by panelNwayFeRValidation.R"),
  two_way_independent = extract(fit_2way),
  three_way_independent = extract(fit_3way),
  nested_state_stateyear = extract(fit_nested)
)
write_json(benchmarks, "panelNwayFeBenchmarks.json", auto_unbox = TRUE, digits = 10)
write.csv(df, "panelNwayFeFixture.csv", row.names = FALSE)
