// Pure-JS: Equation Workbench session -> reproducible R / Python / Stata script.
// No React. Emits idiomatic commands so the target language does the symbolic /
// numeric work (so an economist can re-run & verify in R/Stata/Python), rather
// than hard-coding nerdamer's answers.
//
// Translation strategy: normalize the user expression's power operator to `^`
// for R/Stata/Mata; convert `^` -> `**` for Python (sympy). Function names
// (sqrt, exp, log, sin, ...) are passed through unchanged.

function objectives(s) { return (s.equations || []).filter((e) => e.kind !== "constraint" && e.expr && e.expr.trim()); }
function constraints(s) { return (s.equations || []).filter((e) => e.kind === "constraint"); }
function num(v) { return Number.isFinite(v) ? String(v) : "0"; }

// `^` power, whitespace collapsed. Strips stray newlines from stored exprs.
function rPow(expr) { return String(expr || "").replace(/\*\*/g, "^").replace(/\s+/g, " ").trim(); }
function pyPow(expr) { return rPow(expr).replace(/\^/g, "**"); }

function integralBounds(eq, s) {
  const ir = eq.integralRange;
  if (Array.isArray(ir) && Number.isFinite(ir[0]) && Number.isFinite(ir[1]) && ir[0] < ir[1]) return [ir[0], ir[1]];
  return s.view.xRange;
}

export function buildWorkbenchScript(lang, session) {
  if (lang === "r") return buildR(session);
  if (lang === "python") return buildPython(session);
  if (lang === "stata") return buildStata(session);
  return "";
}

// ── R ─────────────────────────────────────────────────────────────────────────
function buildR(s) {
  const L = [`# Equation Workbench export — session "${s.name}"`, `# Generated by Litux`, ``];
  const params = s.params || [];
  if (params.length) {
    L.push(`# Parameters`);
    for (const p of params) L.push(`${p.name} <- ${num(p.value)}`);
    L.push(``);
  }
  const [x0, x1] = s.view.xRange;
  for (const eq of objectives(s)) {
    const expr = rPow(eq.expr), ax = eq.axis, name = eq.label || "f";
    L.push(`# === ${name} ===`);
    if (!ax) { L.push(`# ${name} = ${expr}  (no axis selected — set the free variable to enable calculus)`, ``); continue; }
    L.push(`${name} <- function(${ax}) ${expr}`);
    if (eq.ops.deriv) L.push(`# symbolic derivative`, `D(quote(${expr}), "${ax}")`);
    if (eq.ops.integral) { const [a, b] = integralBounds(eq, s); L.push(`# definite integral over [${a}, ${b}]`, `integrate(${name}, ${a}, ${b})$value`); }
    if (eq.ops.solveZero) L.push(`# root of ${name}(${ax}) = 0 on [${x0}, ${x1}]`, `uniroot(${name}, c(${x0}, ${x1}))$root`);
    if (eq.ops.optimize) L.push(`# ${eq.sense === "max" ? "maximize" : "minimize"} on [${x0}, ${x1}]`, `optimize(${name}, c(${x0}, ${x1}), maximum = ${eq.sense === "max" ? "TRUE" : "FALSE"})`);
    L.push(``);
  }
  appendConstraintNote(L, constraints(s), "#");
  return L.join("\n");
}

// ── Python (sympy) ──────────────────────────────────────────────────────────────
function buildPython(s) {
  const L = [`# Equation Workbench export — session "${s.name}"`, `import sympy as sp`, ``];
  const axes = [...new Set(objectives(s).map((e) => e.axis).filter(Boolean))];
  if (axes.length) L.push(`${axes.join(", ")} = sp.symbols("${axes.join(" ")}")`);
  const params = s.params || [];
  if (params.length) { L.push(``, `# Parameters`); for (const p of params) L.push(`${p.name} = ${num(p.value)}`); }
  L.push(``);
  for (const eq of objectives(s)) {
    const expr = pyPow(eq.expr), ax = eq.axis, name = eq.label || "f";
    L.push(`# === ${name} ===`);
    if (!ax) { L.push(`# ${name} = ${expr}  (no axis selected)`, ``); continue; }
    L.push(`${name} = ${expr}`);
    if (eq.ops.deriv) L.push(`print("d${name}/d${ax}:", sp.diff(${name}, ${ax}))`);
    if (eq.ops.integral) { const [a, b] = integralBounds(eq, s); L.push(`print("integral [${a}, ${b}]:", sp.integrate(${name}, (${ax}, ${a}, ${b})))`); }
    if (eq.ops.solveZero) L.push(`print("roots:", sp.solve(${name}, ${ax}))`);
    if (eq.ops.optimize) L.push(`print("critical points (${eq.sense}):", sp.solve(sp.diff(${name}, ${ax}), ${ax}))`);
    L.push(``);
  }
  appendConstraintNote(L, constraints(s), "#");
  return L.join("\n");
}

// ── Stata (numeric Mata; no symbolic engine) ────────────────────────────────────
function buildStata(s) {
  const L = [`* Equation Workbench export — session "${s.name}"`,
    `* Stata has no symbolic engine — this uses native function plots + numeric Mata.`, ``];
  const params = s.params || [];
  for (const p of params) L.push(`scalar ${p.name} = ${num(p.value)}`);
  if (params.length) L.push(``);
  const [x0, x1] = s.view.xRange;
  for (const eq of objectives(s)) {
    const expr = rPow(eq.expr), ax = eq.axis, name = (eq.label || "f").replace(/\W/g, "_");
    L.push(`* === ${eq.label || name} ===`);
    if (!ax) { L.push(`* ${name} = ${expr}  (no axis selected)`, ``); continue; }
    L.push(`twoway function y = ${expr}, range(${x0} ${x1}) title("${eq.label || name}")`);
    L.push(`mata:`);
    L.push(`real scalar ${name}(real scalar ${ax}) {`);
    for (const p of params) L.push(`    real scalar ${p.name}; ${p.name} = st_numscalar("${p.name}")`);
    L.push(`    return(${expr})`);
    L.push(`}`);
    if (eq.ops.deriv) L.push(`// numeric derivative at the interval midpoint (central difference)`,
      `xm = (${x0}+${x1})/2; hh = 1e-6`, `("d${name}/d${ax} @midpoint", (${name}(xm+hh)-${name}(xm-hh))/(2*hh))`);
    if (eq.ops.integral) { const [a, b] = integralBounds(eq, s);
      L.push(`// trapezoid integral over [${a}, ${b}]`,
        `n = 1000; a = ${a}; b = ${b}; h = (b-a)/n; sI = (${name}(a)+${name}(b))/2`,
        `for (i=1; i<n; i++) sI = sI + ${name}(a+i*h)`,
        `("integral", sI*h)`);
    }
    if (eq.ops.optimize) L.push(`// ${eq.sense} via grid search on [${x0}, ${x1}]`,
      `ng = 2000; ag = ${x0}; bg = ${x1}; hg = (bg-ag)/ng; bestX = ag; bestF = ${name}(ag)`,
      `for (j=1; j<=ng; j++) { xj = ag+j*hg; fj = ${name}(xj); if (fj ${eq.sense === "max" ? ">" : "<"} bestF) { bestF = fj; bestX = xj } }`,
      `("${eq.sense} x*, f*", bestX, bestF)`);
    if (eq.ops.solveZero) L.push(`// sign-change root scan on [${x0}, ${x1}]`,
      `nr = 2000; ar = ${x0}; br = ${x1}; hr = (br-ar)/nr; prev = ${name}(ar); px = ar`,
      `for (k=1; k<=nr; k++) { xk = ar+k*hr; fk = ${name}(xk); if (sign(fk) != sign(prev)) ("root near", (px+xk)/2); prev = fk; px = xk }`);
    L.push(`end`, ``);
  }
  appendConstraintNote(L, constraints(s), "*");
  return L.join("\n");
}

function appendConstraintNote(L, cons, c) {
  if (!cons.length) return;
  L.push(`${c} NOTE: ${cons.length} constraint(s) defined in the Workbench are not translated`);
  L.push(`${c} to a constrained solver here. Constraints:`);
  for (const g of cons) L.push(`${c}   ${g.relation.lhs} = ${g.relation.rhs}`);
}
